<?php
/*************************************************************************************
 * latex.php
 * -----
 * Author: efi, Matthias Pospiech (matthias@pospiech.eu)
 * Copyright: (c) 2006 efi, Matthias Pospiech (matthias@pospiech.eu), Nigel McNie (http://qbnz.com/highlighter)
 * Release Version: 1.0.9.1
 * Date Started: 2006/09/23
 *
 * LaTeX language file for GeSHi.
 *
 * CHANGES
 * -------
 * 2020/02/25 (1.0.9.1)
 *  - Removed list of command-keywords i) because incomplete and
 *    ii) because relative urls point to documentation not in English language
 *  - Provided a complete list of package-keywords from https://ctan.org/pkg/
 *  - Removed color for [options] because they could be for a
 *    package/environment or in a math context
 *  - Removed color for math because it's not applied to its commands leaving
 *    the text multicolored
 *  - In general, less colors and less regular expressions
 * 2008/08/18 (1.0.8.1)
 *  - Changes in color and some additional command recognition
 *  - No special Color for Brackets, it is only distracting
 *    if color should be reintroduced it should be less bright
 *  - Math color changed from green to violett, since green is now used for comments
 *  - Comments are now colored and the only green. The reason for coloring the comments
 *    is that often important information is in the comments und was merely unvisible before.
 *  - New Color for [Options]
 *  - color for labels not specialised anymore. It makes sence in large documents but less in
 *    small web examples.
 *  - \@keyword introduced
 *  - Fixed \& escaped ampersand
 * 2006/09/23 (1.0.0)
 *  -  First Release
 *
 * TODO
 * -------------------------
 * *
 *
 *************************************************************************************
 *
 *     This file is part of GeSHi.
 *
 *   GeSHi is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   GeSHi is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with GeSHi; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ************************************************************************************/

$language_data = array (
    'LANG_NAME' => 'LaTeX',
    'COMMENT_SINGLE' => array(
        1 => '%'
        ),
    'COMMENT_MULTI' => array(),
    'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
    'QUOTEMARKS' => array(),
    'ESCAPE_CHAR' => '',
    'KEYWORDS' => array(
        1 => array(
            'a0poster', 'a2ac', 'a2ping', 'a4', 'a4wide', 'a5comb', 'aaai', 'aaai-named', 'aalok', 'aastex', 'abbr',
            'abbrevs', 'abc', 'abc2mtex', 'abnt', 'abntex2', 'abntexto', 'aboensis', 'abraces', 'abspos', 'abstbook',
            'abstr-collect', 'abstract', 'abstyles-babel', 'abstyles-orig', 'academicons', 'accanthis', 'accenti',
            'accents', 'accents-cs', 'accessibility', 'accfonts', 'accsupp', 'achemso', 'achicago', 'achicago-bst',
            'acm', 'acmart', 'acmconf', 'acmproc', 'acmtrans', 'acro', 'acroflex', 'acromake', 'acromemory', 'acronym',
            'acronym209', 'acroreloadpdf', 'acrosort', 'acroterm', 'acrotex', 'acrotex-js', 'acrotex-web', 'acroweb',
            'acs', 'active-conf', 'actuarialangle', 'actuarialsymbol', 'adami', 'add-wes', 'addfont', 'addindex',
            'addliga', 'addlines', 'address', 'addtex2eps', 'adfathesis', 'adforn', 'adfsymbols', 'adhocfilelist',
            'adigraph', 'adjmulticol', 'adjustbox', 'adobe-euro', 'adobecaslon', 'adobemapping', 'adrconv', 'adrlist',
            'adtrees', 'advdate', 'ae', 'aeb-minitoc', 'aeb-mlink', 'aeb-mobile', 'aeb-pro', 'aeb-tilebg', 'aeb_dad',
            'aebenvelope', 'aebslicing', 'aebxmp', 'aecc', 'aeguill', 'aesupp', 'afmtopl-clark', 'afmtopl-elwell',
            'afmtopl-wolczko', 'afparticle', 'afterpackage', 'afterpage', 'afthesis', 'aguplus', 'aiaa', 'aichej',
            'aifont', 'ajl', 'akktex', 'akletter', 'akshar', 'alatex', 'albatross', 'alchemist', 'alegreya', 'aleph',
            'alertmessage', 'alfaslabone', 'alg', 'algobox', 'algolrevived', 'algorithm2e', 'algorithmicx', 'algorithms',
            'algpseudocodex', 'algxpar', 'aliascnt', 'aligned-overset', 'alkalami', 'alleqno', 'allrunes', 'alltt',
            'alltt2', 'almendra', 'almfixed', 'alnumsec', 'alpha', 'alpha-persian', 'alphabib', 'alphalph', 'alphanum',
            'alphanum-bst', 'alphanumb', 'alterqcm', 'altfont', 'altnline', 'altsubsup', 'altverse', 'ama', 'ametsoc',
            'amiri', 'amiweb2c', 'amiweb2c-guide', 'ams-cd', 'ams2bib', 'amsaddr', 'amsart', 'amsbook', 'amsbsy',
            'amscd', 'amscdx', 'amscls', 'amscls-doc', 'amsfonts', 'amslatex', 'amslatex-primer', 'amslatexdoc-vietnamese',
            'amsltx11', 'amsmath', 'amsmath-it', 'amsmidx', 'amsopn', 'amspell', 'amsppt', 'amsppt1', 'amsproc',
            'amsrefs', 'amstex', 'amstext', 'amsthm', 'analogclock', 'andika', 'animate', 'anleitung', 'annee-scolaire',
            'annot-pro', 'annotate', 'annotate-equations', 'annotation', 'annotation-pkg', 'anonchap', 'anonymous-acm',
            'anonymouspro', 'ans', 'answers', 'ant', 'ant-worker-tasks', 'antanilipsum', 'anti', 'antomega', 'antp',
            'antt', 'anttvf', 'anufinalexam', 'anyfontsize', 'anysize', 'aobs-tikz', 'aomart', 'apa', 'apa5', 'apa6',
            'apa6e', 'apa7', 'apabst', 'apacite', 'apalike-ejor', 'apalike-german', 'apalike2', 'apasoft', 'apeqnum',
            'apl', 'aplweb', 'apnum', 'appelt-chess', 'appendix', 'appendixnumberbeamer', 'apprendre-a-programmer-en-tex',
            'apprends-latex', 'apptools', 'apxproof', 'ar', 'arabi', 'arabi-add', 'arabic', 'arabic-book', 'arabicfront',
            'arabluatex', 'arabtex', 'arabxetex', 'aramaic', 'aramaic-serto', 'arara', 'arbeit', 'archaeologie',
            'archaic', 'archivo', 'arcs', 'arev', 'arimo', 'arlatex', 'armtex', 'armymemo', 'aro-bend', 'arosgn',
            'around-the-bend', 'arphic', 'arphic-ttf', 'array', 'arraycols', 'arrayjob', 'arrayjobx', 'arraymaker',
            'arraysort', 'arrow', 'arsclassica', 'artex', 'article', 'articleingud', 'artthreads', 'arvo', 'arxivbib',
            'arydshln', 'asaetr', 'asana-math', 'asapsym', 'asc2tex', 'ascelike', 'ascii-chart', 'ascii-cyrillic',
            'ascii-font', 'asciilist', 'ascmac', 'askinclude', 'askmaps', 'asmeconf', 'asmejour', 'aspectratio',
            'aspell', 'assignment', 'assoccnt', 'association-matrix', 'asternote', 'astro', 'astron', 'astyped',
            'asyfig', 'asymptote', 'asymptote-by-example-zh-cn', 'asymptote-faq-zh-cn', 'asymptote-manual-zh-cn',
            'asypictureb', 'at', 'atari-cstex', 'atbegshi', 'atenddvi', 'atendofenv', 'atkinson', 'attachfile',
            'attachfile2', 'attrib', 'atveryend', 'aucklandthesis', 'auctex', 'augie', 'auncial', 'auncial-new',
            'aurical', 'aurl', 'aurora', 'authblk', 'authoraftertitle', 'authorarchive', 'authordate', 'authorindex',
            'auto-pst-pdf', 'auto-pst-pdf-lua', 'auto1', 'autoaligne', 'autobreak', 'autoconf', 'autofancyhdr',
            'autoinst', 'autolatex', 'autolist', 'automagic', 'automata', 'automatica', 'autonum', 'autopdf', 'autopict',
            'autopuncitems', 'autosp', 'autotab', 'autotoc', 'autoview', 'auxhook', 'avremu', 'aweb', 'awesomebox',
            'axessibility', 'axodraw', 'axodraw2', 'b1encoding', 'babel', 'babel-albanian', 'babel-azerbaijani',
            'babel-bahasa', 'babel-basque', 'babel-belarusian', 'babel-bosnian', 'babel-breton', 'babel-bulgarian',
            'babel-catalan', 'babel-contrib', 'babel-croatian', 'babel-czech', 'babel-danish', 'babel-dutch', 'babel-english',
            'babel-esperanto', 'babel-estonian', 'babel-finnish', 'babel-french', 'babel-friulan', 'babel-galician',
            'babel-georgian', 'babel-german', 'babel-greek', 'babel-hebrew', 'babel-hungarian', 'babel-icelandic',
            'babel-indonesian', 'babel-interlingua', 'babel-irish', 'babel-italian', 'babel-japanese', 'babel-kurmanji',
            'babel-latin', 'babel-latvian', 'babel-lithuanian', 'babel-macedonian', 'babel-malay', 'babel-norsk',
            'babel-occitan', 'babel-piedmontese', 'babel-polish', 'babel-portuges', 'babel-romanian', 'babel-romansh',
            'babel-russian', 'babel-samin', 'babel-scottish', 'babel-serbian', 'babel-serbianc', 'babel-slovak',
            'babel-slovenian', 'babel-sorbian', 'babel-spanglish', 'babel-spanish', 'babel-swedish', 'babel-thai',
            'babel-turkish', 'babel-ukrainian', 'babel-vietnamese', 'babel-welsh', 'babelbib', 'babeltools', 'babyloniannum',
            'backgrnd', 'background', 'backnaur', 'backref', 'backrefx', 'badge', 'baekmuk', 'bagpipe', 'bahyph',
            'bakoma', 'bakoma-fonts', 'bakoma-games', 'bakoma-mac', 'balance', 'balanced', 'balancedquotes', 'bangla',
            'bangorcsthesis', 'bangorexam', 'bangtex', 'bankstatement', 'bar', 'barcodes', 'barcodes-vulis', 'bard',
            'bardi', 'bardiag', 'bargraph-js', 'barkom', 'barracuda', 'bartel-chess-fonts', 'base', 'bashful', 'bashkirian',
            'basicarith', 'basiclatex-ru', 'basix', 'baskervaldadf', 'baskervaldx', 'baskervillef', 'basque-book',
            'basque-date', 'bath-bst', 'battleship', 'baum', 'bbcard', 'bbding', 'bbfig', 'bbl2html', 'bbm', 'bbm-macros',
            'bbold', 'bbold-type1', 'bboldx', 'bbs', 'bchart', 'bclogo', 'bdfchess', 'beamer', 'beamer-fuberlin',
            'beamer-rl', 'beamer-tut-pt', 'beamer-verona', 'beamer2thesis', 'beamerappendixnote', 'beameraudience',
            'beamerauxtheme', 'beamercolorthemeowl', 'beamerdarkthemes', 'beamerposter', 'beamersubframe', 'beamerswitch',
            'beamertheme-arguelles', 'beamertheme-cuerna', 'beamertheme-detlevcm', 'beamertheme-epyt', 'beamertheme-focus',
            'beamertheme-light', 'beamertheme-metropolis', 'beamertheme-npbt', 'beamertheme-phnompenh', 'beamertheme-pure-minimalistic',
            'beamertheme-saintpetersburg', 'beamertheme-simpledarkblue', 'beamertheme-simpleplus', 'beamertheme-tcolorbox',
            'beamertheme-trigon', 'beamertheme-upenn-bc', 'beamerthemeamurmaple', 'beamerthemejltree', 'beamerthemelalic',
            'beamerthemenirma', 'beamerthemenord', 'beamerthemetamu', 'bearwear', 'beaulivre', 'beebe-dvi', 'begingreek',
            'beginlatex', 'begriff', 'beilstein', 'beletter', 'belleek', 'bellmac', 'bengali-omega', 'bengali-pandey',
            'bera', 'berenisadf', 'besjournals-bst', 'bestpapers', 'betababel', 'beton', 'beuron', 'bewerbung',
            'bez123', 'bezierplot', 'bfh-ci', 'bfsymb', 'bg', 'bghyphen', 'bgreek', 'bgteubner', 'bguq', 'bhcexam',
            'bib-fr', 'bib-greek', 'bib2dvi', 'bib2gls', 'bib2ml', 'bib2xhtml', 'bibarts', 'bibbuild', 'bibcard',
            'bibcheck', 'bibclean', 'bibcop', 'bibdb', 'bibentry', 'biber', 'biber-cygwin', 'biber-freebsd', 'biber-linux',
            'biber-linux-musl', 'biber-macos', 'biber-ms', 'biber-ms-linux', 'biber-ms-macos', 'biber-ms-windows',
            'biber-solaris', 'biber-windows', 'bibex', 'bibexport', 'bibextract', 'bibfile-reformat-pages', 'bibfilex',
            'bibfind', 'bibhtml', 'bibindex', 'biblatex', 'biblatex-abnt', 'biblatex-ajc2020unofficial', 'biblatex-anonymous',
            'biblatex-apa', 'biblatex-apa6', 'biblatex-archaeology', 'biblatex-arthistory-bonn', 'biblatex-authoryear-icomp-tt',
            'biblatex-bath', 'biblatex-bookinarticle', 'biblatex-bookinother', 'biblatex-bwl', 'biblatex-caspervector',
            'biblatex-cheatsheet', 'biblatex-chem', 'biblatex-chicago', 'biblatex-claves', 'biblatex-cv', 'biblatex-dw',
            'biblatex-enc', 'biblatex-ext', 'biblatex-fiwi', 'biblatex-gb7714-2015', 'biblatex-german-legal', 'biblatex-gost',
            'biblatex-historian', 'biblatex-ieee', 'biblatex-ijsra', 'biblatex-iso690', 'biblatex-jura', 'biblatex-jura2',
            'biblatex-juradiss', 'biblatex-license', 'biblatex-lncs', 'biblatex-lni', 'biblatex-luh-ipw', 'biblatex-manuscripts-philology',
            'biblatex-mla', 'biblatex-morenames', 'biblatex-ms', 'biblatex-multiple-dm', 'biblatex-musuos', 'biblatex-nature',
            'biblatex-nejm', 'biblatex-nottsclassic', 'biblatex-opcit-booktitle', 'biblatex-oxref', 'biblatex-philosophy',
            'biblatex-phys', 'biblatex-publist', 'biblatex-readbbl', 'biblatex-realauthor', 'biblatex-sbl', 'biblatex-science',
            'biblatex-shortfields', 'biblatex-socialscienceshuberlin', 'biblatex-software', 'biblatex-source-division',
            'biblatex-spbasic', 'biblatex-subseries', 'biblatex-swiss-legal', 'biblatex-trad', 'biblatex-true-citepages-omit',
            'biblatex-unified', 'biblatex-vancouver', 'biblatex2bibitem', 'bible', 'bibleref', 'bibleref-french',
            'bibleref-german', 'bibleref-lds', 'bibleref-mouth', 'bibleref-parse', 'bibletext', 'biblio', 'biblio-perl',
            'biblist', 'biblook', 'biblos', 'bibmods', 'bibplain', 'bibsort', 'bibtex', 'bibtex-examples', 'bibtex-gen',
            'bibtex-help', 'bibtex-test', 'bibtex8', 'bibtex8bit', 'bibtexmng', 'bibtexperllibs', 'bibtexu', 'bibtool',
            'bibtools', 'bibtopic', 'bibtopicprefix', 'bibunits', 'bibutils', 'bibview', 'bibview-x', 'bibweb',
            'bicaption', 'bickham', 'bidi', 'bidi-atbegshi', 'bidicontour', 'bidihl', 'bidipagegrid', 'bidipresentation',
            'bidishadowtext', 'bidstobibtex', 'bigdelim', 'bigfoot', 'bigintcalc', 'bigints', 'bigsign', 'bigstrut',
            'bigtable', 'bigtabular', 'biihead', 'bilingualpages', 'binarytree', 'binhex', 'binomexp', 'biochemistry-colors',
            'biocon', 'biokey', 'biolett-bst', 'biolinum-type1', 'biolist', 'birkhaeuser', 'bit2spr', 'bitelist',
            'bitfield', 'bithesis', 'bitpattern', 'bits', 'bitset', 'bitstrea', 'bitter', 'bizcard', 'bjfuthesis',
            'blackboard', 'blackletter', 'blacklettert1', 'blanks', 'blindtext', 'blkarray', 'blkcntrl', 'blochsphere',
            'block', 'blockdraw_mp', 'blopentype', 'bloques', 'blowup', 'blox', 'blue', 'bm', 'bm2font', 'bm2ltx',
            'bmeps', 'bmpp', 'bmpsize', 'bmstu', 'bmstu-iu8', 'bnf-plain', 'bnumexpr', 'bodegraph', 'bodeplot',
            'bohr', 'boisik', 'boites', 'bold-extra', 'boldline', 'boldtensors', 'bondgraph', 'bondgraphs', 'book',
            'book-examples', 'book-of-common-prayer', 'bookcover', 'bookdb', 'bookest', 'bookform', 'bookhands',
            'booklet', 'bookmark', 'bookshelf', 'booktabs', 'booktabs-de', 'booktabs-fr', 'boolexpr', 'boondox',
            'bophook', 'borceux', 'border', 'bosisio', 'boxedart4mac', 'boxedeps', 'boxedminipage', 'boxedminipage2e',
            'boxhandler', 'boxit', 'boxit-ltx', 'bpchem', 'bpolynomial', 'br-lex', 'bracketkey', 'braids', 'braille',
            'braket', 'brandeis-dissertation', 'brandeis-problemset', 'brandeis-thesis', 'brclc', 'breakcites',
            'breakurl', 'bredzenie', 'breqn', 'bridge', 'bridge-pln', 'brief-t', 'brief_t', 'bropd', 'brushscr',
            'bsf', 'bsheaders', 'bsl', 'bsr2dvi', 'btable', 'btool', 'bubblesort', 'buctthesis', 'bullcntr', 'bundledoc',
            'burmese', 'buscard', 'business-research', 'businesscard-qrcode', 'bussproofs', 'bussproofs-extra',
            'bxbase', 'bxcalc', 'bxcjkjatype', 'bxdpx-beamer', 'bxdvidriver', 'bxeepic', 'bxenclose', 'bxghost',
            'bxjaholiday', 'bxjalipsum', 'bxjaprnind', 'bxjatoucs', 'bxjscls', 'bxnewfont', 'bxorigcapt', 'bxpapersize',
            'bxpdfver', 'bxtexlogo', 'bxwareki', 'byo-twemojis', 'byrne', 'bytefield', 'byzantinemusic', 'byzfonts',
            'c-pascal', 'c2cweb', 'c2latex', 'cabin', 'cachepic', 'caesarcm', 'cahyph', 'caladea', 'calc', 'calcage',
            'calctab', 'calculation', 'calculator', 'calendar', 'calendar-barr', 'calendarweek', 'calligra', 'calligra-type1',
            'callouts', 'calorie', 'calrsfs', 'cals', 'calxxxx', 'calxxxx-yyyy', 'camel', 'cancel', 'canoniclayout',
            'cantarell', 'capbas', 'capparmode', 'capt-of', 'captcont', 'captdef', 'caption', 'caption2', 'carbohydrates',
            'card', 'card-set', 'carlisle', 'carlito', 'carolmin', 'carolmin-t1', 'cartonaugh', 'cascade', 'cascadia-code',
            'cascadilla', 'cascover', 'cases', 'casiofont', 'cassette', 'cassette-shipunov', 'cassette209', 'casslbl',
            'casyl', 'catalan', 'catalanbib', 'catalogue', 'catchfile', 'catchfilebetweentags', 'catcodes', 'catdoc',
            'catdvi', 'catechis', 'catoptions', 'causets', 'cbcoptic', 'cbe', 'cbfonts-fd', 'cbgreek-complete',
            'cc-pl', 'ccaption', 'ccfonts', 'cchess', 'ccicons', 'cclicenses', 'ccool', 'ccref', 'cd', 'cdcmd',
            'cdcover', 'cdlabeler', 'cdpbundl', 'cea', 'cell', 'cellprops', 'cellspace', 'cellular', 'cellwise',
            'celtic', 'censor', 'centeredline', 'centerlastline', 'centernot', 'cep', 'cesenaexam', 'cfgguide',
            'cfr-initials', 'cfr-lm', 'changebar', 'changelayout', 'changelog', 'changepage', 'changes', 'chappg',
            'chapref', 'chapterbib', 'chapterfolder', 'charissil', 'charter', 'chbar', 'chbibref', 'cheatsheet',
            'check', 'check-parens', 'checkcites', 'checkend', 'checklab', 'checklistings', 'chem-journal', 'chemarr',
            'chemarrow', 'chembst', 'chemcompounds', 'chemcono', 'chemexec', 'chemfig', 'chemformula', 'chemgreek',
            'chemmacros', 'chemnum', 'chemobabel', 'chemplants', 'chemscheme', 'chemschemex', 'chemsec', 'chemstruct',
            'chemstyle', 'chemsym', 'chemtex', 'cheq', 'cherokee', 'chess', 'chess-problem-diagrams', 'chessboard',
            'chessfss', 'chessmin', 'chet', 'chextras', 'chgbar', 'chhaya', 'chicago', 'chicago-annote', 'chicagoa',
            'chickenize', 'chifoot', 'childdoc', 'china2e', 'chinese-jfm', 'chinesechess', 'chitex', 'chivo', 'chkfloat',
            'chklref', 'chktex', 'chletter', 'chngcntr', 'chngpage', 'chomsky', 'chordbars', 'chordbox', 'chroma',
            'chronology', 'chronosys', 'chs-physics-report', 'chscite', 'churchslavonic', 'cinzel', 'circ', 'circle',
            'circledsteps', 'circledtext', 'circuit-macros', 'circuitikz', 'cirth', 'citation-style-language', 'cite',
            'cite-bundle', 'citeall', 'citeref', 'citesidx', 'cj', 'cje', 'cjhebrew', 'cjk', 'cjk-fonts', 'cjk-gs-integrate',
            'cjk-ko', 'cjkpunct', 'cjw', 'clara', 'classes', 'classico', 'classics', 'classicthesis', 'classif2',
            'classlist', 'classpack', 'cleanthesis', 'clearsans', 'clefval', 'cleveref', 'cleveref-usedon', 'clicks',
            'clip', 'clipboard', 'clistmap', 'clock', 'clojure-pamphlet', 'closefrm', 'cloze', 'clrdblpg', 'clrscode',
            'clrscode3e', 'clrstrip', 'clsguide', 'cluttex', 'cm', 'cm-afm', 'cm-gf', 'cm-lgc', 'cm-mf', 'cm-mf-extra-bold',
            'cm-mf-opt-kern', 'cm-pk', 'cm-super', 'cm-tfm', 'cm-unicode', 'cmactex', 'cmap', 'cmarrows', 'cmastro',
            'cmathbb', 'cmbright', 'cmcyr', 'cmcyr-patch', 'cmcyralt-fonts', 'cmcyralt-ltx', 'cmdstring', 'cmdtrack',
            'cmextra-latex', 'cmfrak', 'cmll', 'cmoefont', 'cmolddig', 'cmoutlines', 'cmpica', 'cmpj', 'cms4talks',
            'cmsd', 'cmslup', 'cmsrb', 'cmtest', 'cmtiup', 'cmtt', 'cmtype3', 'cmupint', 'cmyk-hax', 'cnbwp', 'cnltx',
            'cnoweb', 'cntdwn', 'cntformats', 'cntperchap', 'cochineal', 'code', 'code128', 'codeanatomy', 'codebox',
            'codedescribe', 'codedoc', 'codehigh', 'codepage', 'codesection', 'codicefiscaleitaliano', 'coelacanth',
            'coffeestains', 'collcell', 'collect', 'collectbox', 'collref', 'colonequals', 'colophon', 'color',
            'color-edits', 'colordoc', 'colordvi', 'coloremoji', 'colorframed', 'colorinfo', 'coloring', 'colorist',
            'colorprofiles', 'colors', 'colorsep', 'colorspace', 'colortab', 'colortbl', 'colortex', 'colorwav',
            'colorweb', 'colourchange', 'combelow', 'combine', 'combinedgraphics', 'combofont', 'comfortaa', 'comicneue',
            'comicsans', 'comma', 'commado', 'commath', 'commedit', 'comment', 'comment-pln', 'comment_io', 'committee-font',
            'commonunicode', 'commutative-diagrams', 'comp-fonts-faq', 'compact-symbols', 'compactbib', 'compare',
            'competences', 'complexity', 'components', 'comprehensive', 'compsci', 'computational-complexity', 'computer-typesetting-using-latex',
            'concepts', 'concmath', 'concmath-fonts', 'concmath-otf', 'concprog', 'concrete', 'concrete-macros',
            'conditext', 'confproc', 'consdiag', 'constants', 'conteq', 'context', 'context-account', 'context-algorithmic',
            'context-animation', 'context-annotation', 'context-bnf', 'context-calendar-examples', 'context-chromato',
            'context-cmscbf', 'context-cmttbf', 'context-collatingmarks', 'context-construction-plan', 'context-cyrillicnumbers',
            'context-degrade', 'context-fancybreak', 'context-filter', 'context-fixme', 'context-french', 'context-fullpage',
            'context-gantt', 'context-gnuplot', 'context-handlecsv', 'context-inifile', 'context-interval-calendar',
            'context-layout', 'context-letter', 'context-lettrine', 'context-lilypond', 'context-mathsets', 'context-notes-zh-cn',
            'context-pocketdiary', 'context-rst', 'context-ruby', 'context-sgf', 'context-simplefonts', 'context-simpleslides',
            'context-taspresent', 'context-title', 'context-top-ten', 'context-transliterator', 'context-typearea',
            'context-typescripts', 'context-urwgaramond', 'context-urwgothic', 'context-vim', 'context-visualcounter',
            'continue', 'contour', 'contracard', 'conv-xkv', 'convbkmk', 'convert', 'cooking', 'cooking-units',
            'cookingsymbols', 'cookybooky', 'cool', 'coolfn', 'coollist', 'coolstr', 'coolthms', 'cooltooltips',
            'coop-writing', 'cooperhewitt', 'coordsys', 'copac-clean', 'coptic', 'copyedit', 'copypaste', 'copyrightbox',
            'corelfonts', 'corelpak', 'corelpak-contrib', 'cormorantgaramond', 'correctmathalign', 'corrects', 'corridx-latex',
            'corridx-obsolete', 'coseoul', 'count1to', 'countriesofeurope', 'counttexruns', 'courier', 'courier-scaled',
            'courierten', 'courseoutline', 'coursepaper', 'coverpage', 'covfonts', 'covington', 'cprog', 'cprotect',
            'cprotectinside', 'cpssp', 'cptex', 'cqubeamer', 'cquthesis', 'crbox', 'create-struktex', 'create-theorem',
            'crefthe', 'crimson', 'crimsonpro', 'croatian', 'crop', 'cropmark', 'cropmark-pu', 'cropmarks-pt', 'cropmrks',
            'crossrefenum', 'crossreference', 'crossreftools', 'crossrefware', 'crosstex', 'crossword', 'crosswrd',
            'crudetype', 'crumbs', 'crw', 'cryptocode', 'cryst', 'csassignments', 'csbulletin', 'csfonts', 'csfonts-t1',
            'csindex', 'cslatex', 'csname-doc', 'csplain', 'cspsfonts', 'csquotes', 'csquotes-de', 'css-colors',
            'cstex', 'cstypo', 'csv2latex', 'csvmerge', 'csvsimple', 'csvtolatex', 'csvtools', 'csx', 'ctable',
            'ctablestack', 'ctan-bibdata', 'ctan-o-mat', 'ctan_chk', 'ctanbib', 'ctanify', 'ctantools', 'ctanupload',
            'ctex', 'ctex-faq', 'ctib4tex', 'ctie', 'cuisine', 'cun', 'cuprum', 'currency', 'currfile', 'currvita',
            'cursolatex', 'cursor', 'curve', 'curve2e', 'curves', 'custom-bib', 'customdice', 'cuted', 'cutwin',
            'cv', 'cv4tw', 'cvss', 'cvsty', 'cweb', 'cweb-latex', 'cwebbin', 'cwebhy', 'cwebx', 'cyber', 'cybercic',
            'cyklop', 'cypriot', 'cypriote', 'cyrguide', 'cyrillic209', 'cyrmemo', 'cyrtug', 'czhyph', 'czhyph2e',
            'dad', 'dancers', 'dante-book-reviews', 'dantelogo', 'darkmode', 'dashbox', 'dashrule', 'dashundergaps',
            'dataref', 'datatool', 'datatooltk', 'datax', 'dateiliste', 'datenumber', 'datepicker-pro', 'dates',
            'dates209', 'datestamp', 'datetime', 'datetime2', 'datetime2-bahasai', 'datetime2-basque', 'datetime2-breton',
            'datetime2-bulgarian', 'datetime2-catalan', 'datetime2-croatian', 'datetime2-czech', 'datetime2-danish',
            'datetime2-dutch', 'datetime2-en-fulltext', 'datetime2-english', 'datetime2-esperanto', 'datetime2-estonian',
            'datetime2-finnish', 'datetime2-french', 'datetime2-galician', 'datetime2-german', 'datetime2-greek',
            'datetime2-hebrew', 'datetime2-icelandic', 'datetime2-irish', 'datetime2-it-fulltext', 'datetime2-italian',
            'datetime2-latin', 'datetime2-lsorbian', 'datetime2-magyar', 'datetime2-norsk', 'datetime2-polish',
            'datetime2-portuges', 'datetime2-romanian', 'datetime2-russian', 'datetime2-samin', 'datetime2-scottish',
            'datetime2-serbian', 'datetime2-slovak', 'datetime2-slovene', 'datetime2-spanish', 'datetime2-swedish',
            'datetime2-turkish', 'datetime2-ukrainian', 'datetime2-usorbian', 'datetime2-welsh', 'dayofweek', 'dayroman',
            'daytime', 'db', 'dblfloatfix', 'dblfnote', 'dblfont', 'dbprocess', 'dbshow', 'dccpaper', 'dco', 'dcolumn',
            'dcounter', 'dcpic', 'ddphonism', 'de-macro', 'debate', 'decimal', 'decision-table', 'declare', 'decorule',
            'decsci', 'dectab', 'default', 'deflist', 'defstring', 'degrade', 'dehyph', 'dehyph-exptl', 'dejavu',
            'dejavu-otf', 'delarray', 'deleq', 'delig', 'delim', 'delimseasy', 'delimset', 'delimtxt', 'democodetools',
            'denisbdoc', 'deproc', 'derivative', 'desclist', 'designcon', 'detex', 'detexfaq', 'devanagari', 'devanagari-omega',
            'development', 'dfgproposal', 'dhua', 'diabetes-logbook', 'diadia', 'diagbox', 'diagmac', 'diagmac2',
            'diagnose', 'diagramf', 'diagrams', 'diagxy', 'dialogl', 'dialogue', 'dice', 'dichokey', 'dickimaw',
            'dictsym', 'diffcoeff', 'digestif', 'digicap-pro', 'digiconfigs', 'dijkstra', 'dimnum', 'din1505', 'dinat',
            'dinbrief', 'dinbrief-gui', 'dingbat', 'directory', 'directtex', 'dirtree', 'dirtytalk', 'disser', 'ditaa',
            'dithesis', 'divine', 'djgpp', 'dk-bib', 'dkhyphen', 'dktools', 'dlfltxb', 'dmfonts', 'dmhgener', 'dnaseq',
            'do-it-yourself-tex', 'doafter', 'doc', 'doc-pictex', 'docarc', 'docassembly', 'docbytex', 'doclicense',
            'docmfp', 'docmute', 'docshots', 'docstrip', 'docsurvey', 'doctools', 'documentation', 'docutils', 'dogma',
            'doi', 'doipubmed', 'domitian', 'dos-dc', 'dosepsbin', 'dot2tex', 'dot2texi', 'dotarrow', 'dotlessi',
            'dotlessj', 'dotseqn', 'dottex', 'doublecol', 'doublespace', 'doublestroke', 'doulossil', 'dow', 'dowith',
            'download', 'dox', 'dozenal', 'dpcircling', 'dpfloat', 'dprogress', 'dps', 'drac', 'draft', 'draftcopy',
            'draftfigure', 'drafthead', 'draftmark', 'draftwatermark', 'drama', 'dramatist', 'dratex', 'drawing',
            'drawing-with-metapost', 'drawmatrix', 'drawstack', 'drcaps', 'drftcite', 'drm', 'droid', 'droit-fr',
            'drop', 'dropcaps', 'dropping', 'drs', 'drv', 'dsptricks', 'dsserif', 'dtk', 'dtk-1.32', 'dtk-bibliography',
            'dtl', 'dtxdescribe', 'dtxgallery', 'dtxgen', 'dtxtut', 'ducksay', 'duckuments', 'duerer', 'duerer-latex',
            'duotenzor', 'duplicat', 'dutchcal', 'dvdcoll', 'dvgloss', 'dvgt', 'dvgtk', 'dvi-economic', 'dvi2bitmap',
            'dvi2ln3', 'dvi2tty', 'dvi2xx', 'dviasm', 'dvibit', 'dvibook', 'dvichk', 'dviconcat', 'dvicopy', 'dvidvi',
            'dvii', 'dviincl', 'dviinfox', 'dviljk', 'dvimerge', 'dviout', 'dvipaste', 'dvipdfm', 'dvipdfmx', 'dvipdfmx-def',
            'dvipng', 'dvips', 'dvips-os2', 'dvips-shell', 'dvipscol', 'dvipsconfig', 'dvipsk', 'dvisirule', 'dvistd',
            'dvisun', 'dvisvgm', 'dvisvgm-def', 'dvitoln03', 'dvitops', 'dvitty', 'dvitype', 'dviview', 'dvivue',
            'dviwin', 'dynamicnumber', 'dynblocks', 'dynbrackets', 'dynkin-diagrams', 'dyntree', 'e-french', 'ean',
            'ean13isbn', 'easing', 'easy', 'easy-todo', 'easybib', 'easybmat', 'easybook', 'easyeqn', 'easyfig',
            'easyfloats', 'easyformat', 'easylatex', 'easylist', 'easymat', 'easyreview', 'easytable', 'easyvector',
            'ebezier', 'ebgaramond', 'ebgaramond-maths', 'ebib', 'ebnf', 'ebong', 'ebook', 'ebproof', 'ebsthesis',
            'ec', 'ec-plain', 'ecards', 'ecc', 'ecclesiastic', 'ecgdraw', 'ecltree', 'eco', 'ecobiblatex', 'econ-bst',
            'econlipsum', 'econometrica', 'econometrics', 'economic', 'ecothesis', 'ecta', 'ecv', 'eczar', 'ed',
            'eddi4tex', 'edfnotes', 'edichokey', 'editbar', 'edmac', 'edmargin', 'ednotes', 'eehyph', 'eemeir',
            'eepic', 'efbox', 'eforms', 'ega2mf', 'egameps', 'egothic', 'egpeirce', 'egplot', 'ehhline', 'eiad',
            'eiad-ltx', 'eijkhout', 'einfart', 'einfuehrung', 'einfuehrung2', 'eitl', 'ejpecp', 'ekaia', 'ekdosis',
            'ektype-tanka', 'elbioimp', 'electrumadf', 'eledform', 'eledmac', 'eledpar', 'elegantbook', 'elegantnote',
            'elegantpaper', 'elements', 'elhyphen', 'ellipse', 'ellipsis', 'elmath', 'elocalloc', 'elpres', 'els-cas-templates',
            'elsarticle', 'elteiktdk', 'elteikthesis', 'eltex', 'elvish', 'elzcards', 'emarks', 'embedall', 'embedfile',
            'embrac', 'emerald', 'emf', 'emisa', 'emo', 'emoji', 'emojicite', 'emp', 'empheq', 'emptypage', 'emtex',
            'emtexgi', 'emtrees', 'emulateapj', 'encguide', 'enctex', 'encxvlna', 'endfloat', 'endheads', 'endiagram',
            'endnote', 'endnote2bib', 'endnotes', 'endnotes-hy', 'endnotesj', 'endofproofwd', 'engord', 'engpron',
            'engrec', 'engtlc', 'engwar', 'enigma', 'enotez', 'enparen', 'enpassant', 'enumerate', 'enumitem', 'enumitem-zref',
            'enumspec', 'envbig', 'envelope', 'environ', 'envlab', 'envmath', 'eolang', 'eolgrab', 'epic', 'epigrafica',
            'epigram', 'epigraph', 'epigraph-keys', 'epiolmec', 'epix', 'eplain', 'epmtfe', 'eppstein-trees', 'eps2pdf',
            'epsdice', 'epsf', 'epsf-dvipdfmx', 'epsfig', 'epsfig209', 'epsfview', 'epsfx', 'epsincl', 'epslatex',
            'epspdf', 'epspdf-extra', 'epspdf-setup', 'epspdfconversion', 'epstool', 'epstopdf', 'epstopdf-pkg',
            'eptex', 'eq-fetchbbl', 'eq-pin2corr', 'eq-save', 'eq2db', 'eqell', 'eqexam', 'eqexpl', 'eqlist', 'eqmark',
            'eqmlite', 'eqnalign', 'eqname', 'eqnarray', 'eqnarray209', 'eqnnumwarn', 'eqparbox', 'equationauthor',
            'erdc', 'erewhon', 'erewhon-math', 'errata', 'erw-l3', 'esami', 'escapetext', 'esdiff', 'esieecv', 'esindex',
            'esint', 'esint-type1', 'esk', 'eskd', 'eskdx', 'eslides', 'eso-pic', 'esperant', 'espo', 'esrelation',
            'esstix', 'estcpmm', 'esvect', 'et', 'etaremune', 'etbb', 'etdipa', 'etex', 'etex-pkg', 'etexcmds',
            'etextools', 'ethiop', 'ethiop-t1', 'ethtex', 'etl', 'etoc', 'etoolbox', 'etoolbox-de', 'etruscan',
            'etsvthor', 'euclideangeometry', 'euenc', 'euflag', 'eukdate', 'eukleides', 'euler', 'euler-math', 'eulerpx',
            'eulervm', 'euproposal', 'euptex', 'euro', 'euro-ce', 'eurofont', 'euroitc', 'europasscv', 'europecv',
            'europs', 'eurosans', 'eurosym', 'eurotex', 'euxunicode', 'evangelion-jfm', 'evautofl', 'evenpage',
            'everyhook', 'everypage', 'everysel', 'everyshi', 'evweek', 'exam', 'exam-lite', 'exam-n', 'exam-randomizechoices',
            'exam-zh', 'exam209', 'examdesign', 'example', 'examplep', 'exams', 'excalibur', 'excel2latex', 'exceltex',
            'excludeonly', 'exercise', 'exercisebank', 'exercisepoints', 'exercises', 'exerquiz', 'exesheet', 'exframe',
            'exp-testopt', 'expdlist', 'expex', 'expex-acro', 'expkv', 'expkv-bundle', 'expkv-cs', 'expkv-def',
            'expkv-opt', 'expl3', 'export', 'expose-expl3-dunkerque-2019', 'expressg', 'exscale', 'exsheets', 'exsol',
            'extarrows', 'extdash', 'exteps', 'extpfeil', 'extract', 'extractpdfmark', 'extradefs', 'extsizes',
            'fac', 'facsimile', 'factura', 'facture', 'facture-belge-simple-sans-tva', 'fahyph', 'fakebold', 'faktor',
            'faltblat', 'familytree', 'famt', 'fancybox', 'fancychapters', 'fancyfolien', 'fancyhandout', 'fancyhdr',
            'fancyhdr-it', 'fancyhdrboxed', 'fancyheadings', 'fancylabel', 'fancynum', 'fancypar', 'fancyqr', 'fancyref',
            'fancyslides', 'fancytabs', 'fancytooltips', 'fancyvrb', 'fandol', 'faq-de', 'faq-es', 'faq-fr', 'fascicules',
            'fast-diagram', 'fastpictex', 'fax', 'fbb', 'fbithesis', 'fbox', 'fbs', 'fc', 'fc-arith', 'fcavtex',
            'fchart', 'fcltxdoc', 'fcolumn', 'fdsymbol', 'fduthesis', 'featpost', 'fei', 'fenetrecas', 'fenixpar',
            'fepslatex', 'fetamont', 'fetchbibpes', 'fetchcls', 'feupphdteses', 'fewerfloatpages', 'feyn', 'feynman',
            'feynmf', 'feynmp-auto', 'ffcode', 'ffslides', 'fge', 'fgruler', 'fi2t1', 'fibeamer', 'fibnum', 'fifinddo',
            'fifinddo-info', 'fifo-stack', 'fig2eng', 'fig2lat', 'fig2mf', 'fig2mfpic', 'fig2sty', 'fig2vect', 'fig4latex',
            'figbas', 'figbib', 'figcaps', 'figchild', 'figflow', 'figfrag', 'figplace', 'figput', 'figsinltx',
            'figsize', 'fihyph', 'filecontents', 'filecontentsdef', 'filedate', 'fileerr', 'filehdr', 'filehook',
            'fileinfo', 'filemod', 'fillform', 'findbib', 'findfont', 'findhyph', 'findpkg', 'fink', 'finomaton',
            'finplain', 'finstrut', 'fira', 'firamath', 'firamath-otf', 'firefox-ctan-plugins', 'firefox_ctan_plugins',
            'first-latex-doc', 'first-packages', 'firstline', 'firststeps-xampl', 'fistrum', 'fitbox', 'fithesis',
            'fitr', 'fix-cm', 'fix2col', 'fixbbl', 'fixcmex', 'fixdif', 'fixfoot', 'fixjfm', 'fixlatvian', 'fixltx2e',
            'fixltxhyph', 'fixmath', 'fixme', 'fixmetodonotes', 'fixocgx', 'fixpdfmag', 'fiziko', 'fjodor', 'flabels',
            'flacards', 'flagderiv', 'flags', 'flashcard', 'flashcards', 'flashmovie', 'flatex', 'flatten', 'fldigigal',
            'flexipage', 'flexisym', 'flipbook', 'flippdf', 'float', 'floatfig', 'floatflt', 'floatnohead', 'floatpag',
            'floatrow', 'flow', 'flowchart', 'flowfram', 'flowframtk', 'fltpage', 'fltpoint', 'flushend', 'fmp',
            'fmtcount', 'fn2end', 'fnbreak', 'fncychap', 'fncylab', 'fnlineno', 'fnote', 'fnpara', 'fnpara-pln',
            'fnpct', 'fnpos', 'fnspe', 'fntguide', 'fntproof', 'fnumprint', 'foekfont', 'foilhtml', 'foiltex', 'foliono',
            'fonetika', 'font-change', 'font-change-xetex', 'font-selection', 'fontawesome', 'fontawesome5', 'fontaxes',
            'fontbl', 'fontbook', 'fontch', 'fontchart', 'fonteinf', 'fontenc', 'fontinst', 'fontinstallationguide',
            'fontload', 'fontloader-luaotfload', 'fontmfizz', 'fontname', 'fontools', 'fonts-arundina', 'fonts-churchslavonic',
            'fonts-tlwg', 'fontsampler', 'fontsetup', 'fontsetup-nonfree', 'fontsize', 'fontsmpl', 'fontspec', 'fonttable',
            'fontwrap', 'footbib', 'footmisc', 'footmisx', 'footnote', 'footnotebackref', 'footnotehyper', 'footnoterange',
            'footnpag', 'forarray', 'foreign', 'forest', 'forest-quickstart', 'forindex', 'forloop', 'formal-grammar',
            'format', 'formation-latex-ul', 'formlett', 'forms16be', 'formula', 'formular', 'fortran', 'forum',
            'fotex', 'fouridx', 'fourier', 'fouriernc', 'fourproject', 'fourspell', 'fp', 'fpl', 'fptex', 'fragmaster',
            'fragments', 'frame', 'framed', 'francais-bst', 'frankenbundle', 'frankenstein', 'frankenstein-unsupported',
            'frcursive', 'frederika2016', 'free-math-font-survey', 'free-math-font-survey-vn', 'freetype', 'frege',
            'french-translations', 'frenchle', 'frenchmath', 'frenchponct', 'frenchpro', 'frenchquote', 'frhyph',
            'fribidixetex', 'fribrief', 'frimurer', 'frletter', 'frontespizio', 'froufrou', 'frpseudocode', 'ftc-notebook',
            'ftcap', 'ftetx', 'ftn', 'ftnright', 'ftnxtra', 'fullblck', 'fullminipage', 'fullpage', 'fullpict',
            'fullwidth', 'functan', 'functional', 'fundus', 'fundus-calligra', 'fundus-cyr', 'fundus-la', 'fundus-outline',
            'fundus-pvscript', 'fundus-startrek', 'fundus-sueterlin', 'fundus-twcal', 'fundus-va', 'funnelweb',
            'futhark', 'futhorc', 'futurans', 'fvextra', 'fweb', 'fwlw', 'g-brief', 'gaceta', 'gahyph', 'galois',
            'gamebook', 'gamebooklib', 'gammas', 'gandhi', 'gapfill', 'garamond-libre', 'garamond-math', 'garamondx',
            'garrigues', 'gastex', 'gatech-thesis', 'gates', 'gatherenum', 'gauss', 'gb4e', 'gbrief-creator', 'gbt7714',
            'gcard', 'gchords', 'gcite', 'gckanbun', 'gelasio', 'gellmu', 'gen', 'gender', 'gene-logic', 'genealogy',
            'genealogytree', 'genfam', 'genindex', 'genmpage', 'gensymb', 'gentabtex', 'gentium', 'gentium-original',
            'gentium-tug', 'gentl-gr', 'gentle', 'gentombow', 'geometry', 'geometry-de', 'geomsty', 'geophysics',
            'georgian', 'georgian-stanier', 'geradwp', 'german', 'germbib', 'germdoc', 'germkorr', 'geschichtsfrkl',
            'getargs', 'getfiledate', 'getitems', 'getmap', 'getoptk', 'getrefs', 'gettitlestring', 'gfdl', 'gfnotation',
            'gfs', 'gfsartemisia', 'gfsbaskerville', 'gfsbodoni', 'gfscomplutum', 'gfsdidot', 'gfsdidotclassic',
            'gfsneohellenic', 'gfsneohellenicmath', 'gfsporson', 'gfssolomos', 'ghab', 'ghostscript', 'ghsystem',
            'ghyphen', 'gillcm', 'gillius', 'gincltex', 'gindex', 'ginpenc', 'git-latexdiff', 'gitfile-info', 'gitinfo',
            'gitinfo2', 'gitlog', 'gitstatus', 'gitver', 'gkpmac', 'gl-tree', 'gladtex', 'gleitobjekte', 'glhyph',
            'globalvals', 'glonti', 'glosmathtools', 'gloss', 'gloss-occitan', 'glossaries', 'glossaries-accsupp',
            'glossaries-danish', 'glossaries-dutch', 'glossaries-english', 'glossaries-estonian', 'glossaries-extra',
            'glossaries-finnish', 'glossaries-french', 'glossaries-german', 'glossaries-irish', 'glossaries-italian',
            'glossaries-magyar', 'glossaries-nynorsk', 'glossaries-polish', 'glossaries-portuges', 'glossaries-serbian',
            'glossaries-slovene', 'glossaries-spanish', 'glossaries-swedish', 'glossary', 'glosstex', 'glotex',
            'gmdoc', 'gmdoc-enhance', 'gmeometric', 'gmiflink', 'gmp', 'gmutils', 'gmverb', 'gmverse', 'gnhyph',
            'gnu-freefont', 'gnuplot', 'gnuplottex', 'go', 'go-make', 'gobble', 'goblin', 'gofonts', 'gost', 'gothic',
            'gotoh', 'gpdata', 'gplot', 'grabbox', 'gradback', 'gradient-text', 'gradientframe', 'grading-scheme',
            'gradstudentresume', 'grafcet', 'grafik', 'grant', 'graph35', 'graphbase', 'graphbox', 'graphconv',
            'grapher', 'graphfig', 'graphicp', 'graphics', 'graphics-cfg', 'graphics-def', 'graphics-pln', 'graphicscache',
            'graphicx', 'graphicx-psmin', 'graphicxbox', 'graphicxpsd', 'graphicxsp', 'graphpap', 'graphpaper',
            'graphtex', 'graphviz', 'gray', 'grayhints', 'grchyph', 'greek-fontenc', 'greek-inputenc', 'greek-makeindex',
            'greek4cbc', 'greek6cbc', 'greekctr', 'greekdates', 'greekinfo3', 'greektex', 'greektex-fd', 'greektonoi',
            'greenpoint', 'gregoriotex', 'grfext', 'grffile', 'grfguide', 'grfpaste', 'grid', 'grid-system', 'gridpapers',
            'gridset', 'gridslides', 'grkfinst', 'grnumalt', 'grtimes', 'grundgesetze', 'grverb', 'gs1', 'gsemthesis',
            'gsftopk', 'gsview', 'gtex-letter', 'gtl', 'gtrcrd', 'gtrlib-largetrees', 'gu', 'guarani', 'gudea',
            'guia-bibtex', 'guide-latex-fr', 'guit-corso', 'guitar', 'guitarchordschemes', 'guitartabs', 'guitbeamer',
            'guitlogo', 'gurmukhi', 'gurmukhi-singh', 'gurps', 'gutenberg', 'gv', 'gv-savepos', 'gzt', 'h2020proposal',
            'ha-prosper', 'hackalloc', 'hackthefootline', 'hacm', 'hagenberg-thesis', 'halftone', 'halloweenmath',
            'hamnosys', 'handin', 'handout', 'handoutwithnotes', 'hands', 'hang', 'hangcaption', 'hanging', 'hanoi',
            'hanzibox', 'happy4th', 'har2nat', 'haranoaji', 'haranoaji-extra', 'hardwrap', 'harmony', 'harnon-cv',
            'harpoon', 'harvard', 'harvard-obsolete', 'harveyballs', 'harvmac', 'hatching', 'hausarbeit-jura', 'havannah',
            'hc', 'he-le-na', 'he-she', 'headerfooter', 'hebtex', 'hecthese', 'hellas', 'helmholtz-ellis-ji-notation',
            'helvet', 'hep', 'hep-acronym', 'hep-bibliography', 'hep-float', 'hep-font', 'hep-gen', 'hep-math',
            'hep-math-font', 'hep-paper', 'hep-reference', 'hep-text', 'hep-title', 'hepnames', 'hepparticles',
            'hepthesis', 'hepunits', 'here', 'hereapplies', 'heros-otf', 'hershey', 'hershey-mp', 'heuristica',
            'hex', 'hexboard', 'hexdump', 'hexgame', 'hf-tikz', 'hfbright', 'hfoldsty', 'hfutexam', 'hfutthesis',
            'hge', 'hhline', 'hhtensor', 'hideanswer', 'hieroglf', 'hieroglyph', 'highlight', 'highlightlatex',
            'hilowres', 'hindawi-latex-template', 'hindmadurai', 'hint', 'histogr', 'historische-zeitschrift', 'histyle',
            'hitec', 'hitex', 'hitex-def', 'hithesis', 'hitreport', 'hitszbeamer', 'hitszthesis', 'hktex', 'hlatex',
            'hlatex-fonts', 'hletter', 'hlist', 'hmtrump', 'hobby', 'hobete', 'hobsub', 'hoffset-voffset', 'hologo',
            'holtpolt', 'holtxdoc', 'hook-pre-commit-pkg', 'hopatch', 'horoscop', 'hp2pl', 'hp2xx', 'hpgl2ps', 'hpsdiss',
            'href-ul', 'hrefhide', 'hrhyph', 'hrlatex', 'hsindex', 'html2latex', 'htmlhelp', 'hu-berlin-bundle',
            'huawei', 'huaz', 'huffman', 'huhyph', 'hulipsum', 'humanbio', 'humanist', 'humannat', 'huncial', 'hungarian',
            'hustthesis', 'hvarabic', 'hvdashln', 'hvextern', 'hvfloat', 'hvindex', 'hvlogos', 'hvmath', 'hvmath-fonts',
            'hvpygmentex', 'hvqrurl', 'hwemoji', 'hwkatakana', 'hyacc-cm', 'hybrid-latex', 'hycolor', 'hypbmsec',
            'hypcap', 'hypdestopt', 'hypdoc', 'hypdvips', 'hyper', 'hyperbar', 'hyperlatex', 'hypernat', 'hyperref',
            'hyperxmp', 'hypgotoe', 'hyph-utf8', 'hyphen-accent', 'hyphen-spanish', 'hyphenat', 'hyphenation-greek',
            'hyphenex', 'hyphsubst', 'hypht1', 'hyplain', 'i-ching', 'iagproc', 'iahyphen', 'ibarra', 'ibm', 'ibmres-tex',
            'ibrackets', 'ibycus-babel', 'ibygrk', 'icehyph', 'icelandic', 'iching', 'icite', 'icomma', 'icon-appr',
            'icons', 'icsv', 'idealfonts', 'identkey', 'idverb', 'idxcmds', 'idxlayout', 'idxtex', 'ieeeannot',
            'ieeeconf', 'ieeepes', 'ieeetran', 'ieeetrantools', 'ieejtran', 'ietfbibs', 'iexec', 'ifacmtg', 'ifallfalse',
            'ifdraft', 'ifetex', 'iffont', 'iflang', 'ifluatex', 'ifmslide', 'ifmtarg', 'ifnextok', 'ifoddpage',
            'ifpdf', 'ifplatform', 'ifptex', 'ifsym', 'iftex', 'ifthen', 'ifthenx', 'ifvtex', 'ifxetex', 'ifxptex',
            'igo', 'iitem', 'ijc', 'ijcai89', 'ijmart', 'ijqc', 'ijsra', 'imac', 'image-gallery', 'imakeidx', 'imaketex',
            'imfellenglish', 'imfellflowers', 'impatient', 'impnattypo', 'import', 'impose', 'imprintmtshadow',
            'imsproc', 'imtekda', 'incgraph', 'includernw', 'includex', 'inconsolata', 'indent', 'indentfirst',
            'index', 'indextools', 'indic-type1', 'induni-om', 'indxcite', 'infpic', 'infwarerr', 'inhyph', 'initials',
            'inkpaper', 'inline-images', 'inlinebib', 'inlinedef', 'inlinelabel', 'innerscript', 'inputenc', 'inputenx',
            'inputfile', 'inputnormalization', 'inputtrc', 'inriafonts', 'inrstex', 'insbox', 'inscrutable', 'insdljs',
            'inslrmaj', 'inslrmin', 'install-latex-guide-zh-cn', 'installfont', 'intcalc', 'inter', 'interactiveanimation',
            'interactiveplot', 'interactiveworkbook', 'interchar', 'interfaces', 'interpol', 'interpreter', 'interval',
            'intex', 'intopdf', 'intro-scientific', 'inversepath', 'invertedparagraphs', 'invoice', 'invoice-class',
            'invoice2', 'iodhbwm', 'ionumbers', 'iopart-num', 'ipa', 'ipaex', 'ipaex-type1', 'is-bst', 'iscram',
            'isf', 'ishyph', 'isi2bib', 'isi2bibtex', 'iso', 'iso-tex', 'iso10303', 'iso209', 'isodate', 'isodoc',
            'isolatin1', 'isomath', 'isonums', 'isopt', 'isorot', 'isotope', 'ispell', 'issuulinks', 'ist21', 'istgame',
            'ital', 'italic', 'ite', 'ithyph', 'itnumpar', 'itrans-processor', 'ivd2dvi', 'iwhdp', 'iwona', 'izhitsa',
            'jablantile', 'jabref', 'jacow', 'jadetex', 'jamtimes', 'japanese-mathformulas', 'japanese-otf', 'japanese-otf-uptex',
            'jas99', 'jas99m', 'jasthesis', 'javabib', 'javadoc', 'javadvi', 'javascript-texed', 'javatex', 'jbact',
            'jbibtexmanager', 'jcc', 'jeep', 'jeopardy', 'jeuxcartes', 'jflap2tikz', 'jfmutil', 'jfontmaps', 'jhep',
            'jieeetran', 'jigsaw', 'jj-game', 'jkmath', 'jknappen', 'jkthesis', 'jlabels', 'jlm', 'jlreq', 'jlreq-deluxe',
            'jmakepdfx', 'jmb', 'jmlr', 'jmsdelim', 'jneurosci', 'jnuexam', 'jobname-suffix', 'josefin', 'jourcl',
            'joy-of-tex', 'jpeg2ps-os2', 'jpgfdraw', 'jphysiol', 'jpicedt', 'jpneduenumerate', 'jpnedumathsymbols',
            'jpsj', 'jqt1999', 'js-misc', 'jsclasses', 'jslectureplanner', 'jspell', 'jtb', 'jtbnew', 'jumplines',
            'junicode', 'jupynotex', 'jura', 'juraabbrev', 'jurabib', 'juramisc', 'jurarsp', 'justfontitte', 'jvlisting',
            'jwjournal', 'kalendarium', 'kalender', 'kalender-209', 'kanaparser', 'kanbun', 'kantlipsum', 'karnaugh',
            'karnaugh-map', 'karnaughmap', 'karta', 'kaytannollista-latexia', 'kblocks', 'kbordermatrix', 'kdgdocs',
            'kdgreek', 'kdpcover', 'kelly-greek-font', 'kerkis', 'kerntest', 'ketcindy', 'keycommand', 'keyfloat',
            'keyindex', 'keyparse', 'keyreader', 'keystroke', 'keyval', 'keyval2e', 'keyvaltable', 'kfupm-math-exam',
            'kile', 'kinematikz', 'kix', 'kixfont', 'klinz', 'kmrhyph', 'knit', 'knitting', 'knittingpattern', 'knot',
            'knowledge', 'knst', 'knuth-base', 'knuth-dist', 'knuth-errata', 'knuth-hint', 'knuth-letter', 'knuth-lib',
            'knuth-local', 'knuth-pdf', 'koi8', 'koma-moderncvclassic', 'koma-script', 'koma-script-examples', 'koma-script-examples-3',
            'koma-script-examples-4', 'koma-script-examples-5', 'koma-script-obsolete', 'koma-script-sfs', 'komacv',
            'komacv-rg', 'konwerter', 'korigamik', 'kotex-oblivoir', 'kotex-plain', 'kotex-utf', 'kotex-utils',
            'kpathsea', 'kpfonts', 'kpfonts-otf', 'ksfh-nat', 'ksp-thesis', 'ktexshell', 'ktv-texdata', 'ku-template',
            'kurdishlipsum', 'kurier', 'kuvio', 'kvdefinekeys', 'kvmap', 'kvoptions', 'kvsetkeys', 'l2a', 'l2picfaq',
            'l2tabu', 'l2tabu-english', 'l2tabu-french', 'l2tabu-italian', 'l2tabu-spanish', 'l2x', 'l3backend',
            'l3build', 'l3docstrip', 'l3experimental', 'l3kernel', 'l3keys2e', 'l3packages', 'l3regex', 'la', 'laansort',
            'labbook', 'label-pln', 'labelcas', 'labelfig', 'labelmac3', 'labelmag', 'labels', 'labels4easylist',
            'labelschanged', 'lablst-pkg', 'labtex', 'labyrinth', 'lacheck', 'ladder', 'lahyph', 'laletter', 'lambda-lists',
            'lambdax', 'lamemo', 'lametex', 'lamstex', 'lamstex-index', 'landscape', 'langcode', 'langnames', 'langsci',
            'langsci-affiliations', 'langsci-avm', 'lapdf', 'laps', 'lastbib', 'lastpackage', 'lastpage', 'latable',
            'lated', 'latex', 'latex-amsmath', 'latex-amsmath-dev', 'latex-base', 'latex-base-dev', 'latex-bib-ex',
            'latex-bib2-ex', 'latex-bnf', 'latex-brochure', 'latex-context-ppchtex', 'latex-course', 'latex-cyrillic',
            'latex-doc', 'latex-doc-ptr', 'latex-errata', 'latex-essential', 'latex-firstaid', 'latex-firstaid-dev',
            'latex-fonts', 'latex-for-undergraduates', 'latex-git-log', 'latex-graphics', 'latex-graphics-dev',
            'latex-hlp', 'latex-info', 'latex-lab', 'latex-lab-dev', 'latex-make', 'latex-mr', 'latex-notes-zh-cn',
            'latex-papersize', 'latex-pro-pragmatiky', 'latex-referenz', 'latex-refsheet', 'latex-sciences-humaines',
            'latex-tabellen', 'latex-tds', 'latex-tools', 'latex-tools-dev', 'latex-uni8', 'latex-veryshortguide',
            'latex-via-exemplos', 'latex209', 'latex2e-help-texinfo', 'latex2e-help-texinfo-fr', 'latex2e-reference',
            'latex2html', 'latex2man', 'latex2nemeth', 'latex2rtf', 'latex4jed', 'latex4musicians', 'latex4wp',
            'latex4wp-it', 'latexalpha2', 'latexbangla', 'latexbug', 'latexcad', 'latexcheat', 'latexcheat-de',
            'latexcheat-esmx', 'latexcheat-ptbr', 'latexcolors', 'latexcount', 'latexcourse-rug', 'latexdb', 'latexdemo',
            'latexdiff', 'latexdraw', 'latexfileinfo-pkgs', 'latexfileversion', 'latexgit', 'latexindent', 'latexinfo',
            'latexmake', 'latexmk', 'latexmng', 'latexmp', 'latexn', 'latexpand', 'latexpix', 'latexrelease', 'latexrender',
            'latexwide', 'latexwizard', 'latin', 'latin1jk', 'latin2jk', 'latin3jk', 'latino-sine-flexione', 'lato',
            'layaureo', 'layout', 'layouts', 'lazylist', 'lb2-examples', 'lccaps', 'lcd', 'lcdf-typetools', 'lcg',
            'lcircuit', 'lcyw', 'ldiff', 'leading', 'leadsheets', 'leaflet', 'leawood', 'lebhart', 'lecturer', 'lectures',
            'lectureslides', 'led', 'ledarab', 'ledmac', 'ledpar', 'leftidx', 'leftindex', 'leiletter', 'leipzig',
            'lengthconvert', 'letgut', 'letltxmacro', 'letter', 'letter-plain', 'letter1', 'letterformat', 'lettergothic',
            'lettermac', 'letterspacing', 'letterswitharrows', 'lettre', 'lettrine', 'levy-font', 'levy-latex',
            'lewis', 'lexend', 'lexikon', 'lexitex', 'lexref', 'lextex', 'lfb', 'lfonts-ams', 'lgc-examples', 'lgc2-examples',
            'lgraph', 'lgreek', 'lgrind', 'lgrmath', 'lgrx', 'lh', 'lhcyr', 'lhelp', 'libertine', 'libertine-legacy',
            'libertine-type1', 'libertinegc', 'libertineotf', 'libertinus', 'libertinus-fonts', 'libertinus-otf',
            'libertinus-type1', 'libertinust1math', 'libgreek', 'librarian', 'librebaskerville', 'librebodoni',
            'librecaslon', 'librefranklin', 'libris', 'lie-hasse', 'lifia-th', 'liftarm', 'ligatex', 'light-latex-make',
            'ligtype', 'lilyglyphs', 'limap', 'limecv', 'lineara', 'linearb', 'linebreaker', 'linegoal', 'lineno',
            'linenoamsmath', 'ling-macros', 'lingtrees', 'linguex', 'linguisticspro', 'linop', 'linsys', 'lintex',
            'lion-msc', 'lips', 'lipsum', 'lisp-on-tex', 'list', 'listbib', 'listing', 'listing-pln', 'listings',
            'listings-ext', 'listingsutf8', 'listlbls', 'listliketab', 'listofanswers', 'listofitems', 'listofsymbols',
            'literate', 'literaturnaya', 'lithuanian', 'lithuanian-babel', 'liturg', 'ljmetrics', 'lkort', 'lkproof',
            'llist', 'llmk', 'llncs', 'llncs209', 'llncsconf', 'lm', 'lm-math', 'lmacs', 'lmake', 'lmodern', 'lms',
            'ln03dvi', 'lni', 'lobster2', 'locality', 'localloc', 'logbox', 'logfilter', 'loggates', 'logic', 'logical-markup-utils',
            'logicproof', 'logicpuzzle', 'logix', 'logpap', 'logreq', 'logsys', 'lollipop', 'longdiv', 'longdivision',
            'longfbox', 'longfigure', 'longnamefilelist', 'longtable', 'longtocline', 'lookbibtex', 'loops', 'losymbol',
            'lout', 'loval', 'lparse', 'lpform', 'lpic', 'lplfitch', 'lps', 'lpw', 'lroundrect', 'lsabon', 'lsc',
            'lscape', 'lshort', 'lshort-bulgarian', 'lshort-czech', 'lshort-dutch', 'lshort-english', 'lshort-estonian',
            'lshort-finnish', 'lshort-french', 'lshort-german', 'lshort-italian', 'lshort-japanese', 'lshort-korean',
            'lshort-mongol', 'lshort-mongolian', 'lshort-persian', 'lshort-polish', 'lshort-portuguese', 'lshort-portuguese-br',
            'lshort-russian', 'lshort-slovak', 'lshort-slovenian', 'lshort-spanish', 'lshort-thai', 'lshort-turkish',
            'lshort-ukr', 'lshort-vietnamese', 'lshort-zh-cn', 'lstaddons', 'lstbayes', 'lstfiracode', 'lt3graph',
            'lt3luabridge', 'lt3rawobjects', 'ltablex', 'ltabptch', 'ltb2bib', 'ltcaption', 'ltnews', 'ltoh', 'ltt',
            'ltugboat', 'ltx2mathml', 'ltx2rtf', 'ltx2x', 'ltx3pub', 'ltx4yt', 'ltxcmds', 'ltxdiff', 'ltxdoc', 'ltxdockit',
            'ltxfileinfo', 'ltxgrid', 'ltxguidex', 'ltximg', 'ltxindex', 'ltxinput', 'ltxkeys', 'ltxmisc', 'ltxnew',
            'ltxtable', 'ltxtools', 'ltxutil', 'lua-alt-getopt', 'lua-check-hyphen', 'lua-physical', 'lua-tinyyaml',
            'lua-typo', 'lua-uca', 'lua-ul', 'lua-uni-algos', 'lua-visual-debug', 'lua-widow-control', 'lua2dox',
            'luaaddplot', 'luabibentry', 'luabidi', 'luacas', 'luacensor', 'luacode', 'luacolor', 'luacomplex',
            'luafindfont', 'luagcd', 'luahyphenrules', 'luaimageembed', 'luaindex', 'luainputenc', 'luaintro', 'luakeys',
            'lualatex-doc', 'lualatex-doc-de', 'lualatex-math', 'lualatex-platform', 'lualatex-truncate', 'lualibs',
            'lualinalg', 'luamathalign', 'luamaths', 'luamesh', 'luamodulartables', 'luamplib', 'luaoptions', 'luaotfload',
            'luapackageloader', 'luaprogtable', 'luapstricks', 'luaquotes', 'luarandom', 'luaset', 'luasseq', 'luatex',
            'luatex-def', 'luatex-pkg', 'luatex85', 'luatexbase', 'luatexja', 'luatexko', 'luatextra', 'luatodonotes',
            'luatruthtable', 'luavlna', 'luaxml', 'lucida', 'lucida-otf', 'lucidabr', 'lucold', 'lug', 'lutabulartools',
            'luximono', 'lwarp', 'lwc-examples', 'lxfonts', 'lxmail', 'ly1', 'lyluatex', 'lyx', 'm-pictex', 'm-tx',
            'm3d', 'maad', 'mab2bib', 'macbibtex', 'macfont', 'macrolist', 'macros2e', 'macroswap', 'mactex', 'mactex-basic',
            'mactextras', 'mactotex', 'mafr', 'magaz', 'magic', 'magicnum', 'magicwatermark', 'magra', 'mahjong',
            'mailing', 'mailmerge', 'make-env', 'make-latex', 'make4ht', 'makebarcode', 'makebase', 'makebox', 'makecell',
            'makecirc', 'makecmds', 'makecookbook', 'makedoc', 'makedtx', 'makefonts', 'makeglos', 'makeglossariesgui',
            'makeidx', 'makeindex', 'makeindexk', 'makelabels', 'makeplot', 'makeprog', 'maker', 'makerobust', 'makerobust209',
            'makeshape', 'maketable', 'makor2', 'malayalam-latex', 'malayalam-obsolete', 'malayalam-omega', 'maltese',
            'malvern', 'mandel', 'mandi', 'manfnt', 'manjutex', 'manpage', 'manual', 'manual209', 'manuscript',
            'manyfoot', 'manyind', 'mapcodes', 'maple', 'marathi', 'marcellus', 'margbib', 'marginal', 'marginfit',
            'marginfix', 'marginnote', 'marginote', 'markdown', 'marnote', 'marvosym', 'matapli', 'matc3', 'matc3mem',
            'match_parens', 'math-e', 'math-into-latex-4', 'mathabx', 'mathabx-type1', 'mathalfa', 'mathalpha',
            'mathalphabets', 'mathastext', 'mathbbol', 'mathcmd', 'mathcommand', 'mathcomp', 'mathdesign', 'mathdots',
            'mathematica', 'mathesatz-examples', 'mathexam', 'mathfam256', 'mathfixs', 'mathfont', 'mathgifg', 'mathinst',
            'mathkit', 'mathlig', 'mathpartir', 'mathpazo', 'mathpple', 'mathptm', 'mathptmx', 'mathpunctspace',
            'mathrsfs', 'maths-symbols', 'mathsci2bibtex', 'mathscinet', 'mathsemantics', 'mathspad', 'mathspec',
            'mathspic', 'mathstone', 'mathstyle', 'mathtex', 'mathtime-ltx', 'mathtime-metrics', 'mathtime-pln',
            'mathtools', 'mathtrip', 'mathtype', 'matlab-prettifier', 'matlabweb', 'matrix-skeleton', 'mattens',
            'mattex', 'maybeload', 'maybemath', 'maze', 'mbboard', 'mbenotes', 'mboxfill', 'mcaption', 'mceinleger',
            'mcexam', 'mcf2graph', 'mcite', 'mciteplus', 'mcmthesis', 'mctex', 'mdframed', 'mdputu', 'mdsymbol',
            'mdvi', 'mdwfonts', 'mdwlist', 'mdwmath', 'mdwtab', 'mdwtools', 'mecaso', 'media4svg', 'media9', 'medstarbeamer',
            'meetingmins', 'megatape', 'mem', 'membranecomputing', 'memdesign', 'memexsupp', 'memhfixc', 'memo-pln',
            'memo2', 'memo209', 'memoir', 'memoirchapterstyles', 'memory', 'memorygraphs', 'mendex-doc', 'mensa-tex',
            'mentis', 'menu', 'menucard', 'menukeys', 'meparticle', 'meper', 'mercatormap', 'merge', 'merriweather',
            'messagebubbles', 'messagepassing', 'meta-mode', 'metafont', 'metafont-beginners', 'metafp', 'metago',
            'metainfo', 'metalogo', 'metalogox', 'metanorma', 'metaobj', 'metaplot', 'metapost', 'metapost-colorbrewer',
            'metapost-examples', 'metapost-matlab', 'metastr', 'metatex', 'metatype1', 'metauml', 'method', 'metre',
            'metrix', 'mewltx', 'mex', 'mf', 'mf-ps', 'mf2ps', 'mf2pt1', 'mf2pt3', 'mf2tex', 'mfbook', 'mff', 'mff-util',
            'mfirstuc', 'mflogo', 'mflogo-font', 'mflogo209', 'mfnfss', 'mfpic', 'mfpic4ode', 'mftinc', 'mftrace',
            'mfware', 'mfwl', 'mgltex', 'mh', 'mhack', 'mhchem', 'mhequ', 'mhs', 'mhsetup', 'mi-solns', 'miama',
            'microimp', 'microtype', 'microtype-de', 'mid2tex', 'midfloat', 'midi2tex', 'midnight', 'midpage', 'mif2xfig',
            'miktex', 'miktex-portable', 'miktex_update', 'mil', 'mil3', 'miller', 'milog', 'milstd', 'milsymb',
            'mimetex', 'mindflow', 'minibox', 'minidocument', 'minifp', 'miniltx', 'minim', 'minim-hatching', 'minim-math',
            'minim-mp', 'minim-pdf', 'minim-xmp', 'minimal', 'minimalist', 'minion2newtx', 'minionpro', 'minipage-marginpar',
            'miniplot', 'minitoc', 'minorrevision', 'minted', 'mintspirit', 'minutes', 'mirr', 'mismath', 'missaali',
            'mitpress', 'mk', 'mkbangtex', 'mkbib', 'mkjobtexmf', 'mkpattern', 'mkpic', 'mkpkfontdir', 'mkstmp_pro',
            'mla', 'mla-paper', 'mlacls', 'mlbib', 'mleftright', 'mlist', 'mlmath', 'mlmodern', 'mltex', 'mltex-ltx',
            'mluexercise', 'mm', 'mma2ltx', 'mmafm', 'mmap', 'mmpfb', 'mmtools', 'mnhyphn', 'mnotes', 'mnras', 'mnras-plain',
            'mnsymbol', 'mnttex', 'modeles-factures-belges-assocs', 'moderncv', 'modernposter', 'moderntimeline',
            'modes', 'modguide', 'modiagram', 'modref', 'modroman', 'modular', 'modulus', 'mol2chemfig', 'mongolian-babel',
            'monofill', 'monster', 'montex', 'montserrat', 'moodle', 'moonphase', 'moredefs', 'moreenum', 'morefloats',
            'morehelp', 'morehype', 'moresize', 'moreverb', 'morewrites', 'morisawa', 'morse', 'movie15', 'mp',
            'mp3d', 'mparhack', 'mparrows', 'mpattern', 'mpchess', 'mpcolornames', 'mpdinbrief', 'mpedit', 'mpfonts',
            'mpgraphics', 'mpman-ru', 'mpost', 'mpostinl', 'mpstoeps', 'mptrees', 'mrcheckbib', 'mrecog', 'ms',
            'msc', 'msg', 'mslapa', 'msu-thesis', 'msx2msa', 'msym', 'mt11p', 'mtbe', 'mtex', 'mtgreek', 'mtp2lite',
            'mucproc', 'mugsthesis', 'muling', 'multenum', 'multiaudience', 'multibbl', 'multibib', 'multibibliography',
            'multibox', 'multicap', 'multicol', 'multicolpar', 'multicolrule', 'multidef', 'multido', 'multienv',
            'multiexpand', 'multifootnote', 'multilang', 'multind', 'multiobjective', 'multiple-choice', 'multirow',
            'multitoc', 'munich', 'musical', 'musicography', 'musictex', 'musikui', 'musixguit', 'musixtex', 'musixtex-egler',
            'musixtex-fonts', 'musixtex-t1fonts', 'musixtnt', 'musuos', 'muthesis', 'mversion', 'mwcls', 'mwe',
            'mweights', 'mwrite', 'mxd', 'mxedruli', 'mychemistry', 'mycv', 'myfilist', 'mylatex', 'mylatexformat',
            'myletter', 'mynsfc', 'na-border', 'na-box', 'na-position', 'nabatean', 'nag', 'nahuatl', 'naive-ebnf',
            'nameauth', 'named', 'namedef', 'namedtensor', 'nameref', 'namespc', 'namunsrt', 'nanicolle', 'nanumtype1',
            'nar', 'nassflow', 'natbib', 'natded', 'nath', 'natmove', 'nature', 'navigator', 'navydocs', 'nb4latex',
            'nbaseprt', 'nbaskerv', 'nccbbb', 'nccboxes', 'ncccomma', 'ncccropbox', 'ncccropmark', 'nccfancyhdr',
            'nccfloats', 'nccfoots', 'ncclatex', 'nccmath', 'nccparskip', 'nccpic', 'nccrules', 'nccsect', 'nccstretch',
            'nccthm', 'ncctools', 'nchairx', 'nddiss', 'ndsu-thesis', 'ndsu-thesis-2022', 'nedit-latex-extensions',
            'needspace', 'nehyph', 'nemocal', 'neo-euler', 'nestquot', 'neufont', 'neuralnetwork', 'neuron', 'nevelok',
            'newalg', 'newapa', 'newcastle-bst', 'newclude', 'newcm', 'newcommand', 'newcomputermodern', 'newenviron',
            'newfile', 'newfloat', 'newinsert', 'newlfm', 'newpax', 'newproof', 'newpx', 'newsletr', 'newspaper',
            'newthm', 'newtx', 'newtxsf', 'newtxtt', 'newunicodechar', 'newvbtm', 'newverbs', 'nextpage', 'nexus-otf',
            'nfssext-cfr', 'nfssfont', 'ngerman', 'nicefilelist', 'nicefrac', 'niceframe', 'niceframe-type1', 'nicematrix',
            'nicetext', 'niceverb', 'nidanfloat', 'nih', 'nihbiosketch', 'nimbus15', 'nimsticks', 'ninecolors',
            'njurepo', 'njustthesis', 'njuthesis', 'njuvisual', 'nkarta', 'nl-interval', 'nlatexdb', 'nlctdoc',
            'nmbib', 'nndraw', 'nnext', 'nnfootnote', 'noconflict', 'nodetree', 'nofill', 'nohyph', 'nohyphbx',
            'noindentafter', 'noitcrul', 'nolbreaks', 'nomencl', 'nomentbl', 'nonfloat', 'nonumonpart', 'nopageno',
            'noprot', 'norbib', 'normalcolor', 'nostarch', 'notes', 'notes2bib', 'notespages', 'notestex', 'notex-bst',
            'noto', 'noto-emoji', 'notoccite', 'notocjksc', 'notocondensed', 'notomath', 'novel', 'noweb', 'nowidow',
            'nox', 'npp-for-context', 'nrc', 'ntabbing', 'ntg', 'ntg-maps', 'ntgclass', 'nth', 'ntheorem', 'ntheorem-vn',
            'nts', 'nts-l', 'ntsfaq', 'nuc', 'nucleardata', 'numalg', 'numberedblock', 'numberpt', 'numending',
            'numerica', 'numerica-plus', 'numerica-tables', 'numericplots', 'numline', 'numname', 'numnameru', 'numprint',
            'numspell', 'nunito', 'nwafuthesis', 'nwejm', 'oands', 'obas', 'oberdiek', 'objectz', 'obnov', 'obsolete',
            'oca', 'occam', 'ocg-p', 'ocgtools', 'ocgx', 'ocgx2', 'ochem', 'ocherokee', 'ocr-a', 'ocr-b', 'ocr-b-outline',
            'ocr-latex', 'octave', 'octavo', 'odsfile', 'oesch', 'ofntinst', 'ofs', 'ogham', 'ogonek', 'oinuit',
            'okuda', 'old-arrows', 'old-faq-en', 'old-fontch', 'oldlatin', 'oldprsn', 'oldstandard', 'oldstandardt1',
            'oldstyle', 'oletex', 'olsak-misc', 'omega', 'onedown', 'onepagem', 'onlyamsmath', 'onrannual', 'oops',
            'opacity-pro', 'opcit', 'opencolor', 'opensans', 'oplotsymbl', 'opteng', 'optex', 'optexcount', 'optidef',
            'optional', 'options', 'optparams', 'orcidlink', 'orderer', 'orderrefs', 'ordinalpt', 'oriental', 'orientation',
            'oriya', 'orkhun', 'os2tex', 'osa', 'oscola', 'osda', 'osmanian', 'oststud', 'oswald', 'ot-tableau',
            'ot2cyr', 'ot2woff', 'otfinst', 'otftofd', 'othello', 'othelloboard', 'oubraces', 'oup-authoring-template',
            'outerhbox', 'outilsgeomtikz', 'outline', 'outliner', 'outlines', 'outlining', 'oval', 'ovalfbox', 'overarrows',
            'overcite', 'overlays', 'overlock', 'overpic', 'overrightarrow', 'overword', 'oxford', 'oztex', 'oztex-fonts',
            'oztex-german', 'pacioli', 'padauk', 'padcount', 'pagecolor', 'pagecont', 'pagedraw', 'pagefoots', 'pageframe',
            'pagegrid', 'pagelayout', 'pagella-otf', 'pageno', 'pagenote', 'pagerange', 'pagereference', 'pagesel',
            'pageslts', 'palatino-nfss', 'palette', 'palladam', 'pandora', 'pandora-latex', 'pandora-type1', 'pangram',
            'paper', 'papercdcase', 'papermas', 'papertex', 'paracol', 'parades', 'paragraphs', 'paralist', 'parallel',
            'paratype', 'parboxx', 'parcolumns', 'paresse', 'parisa', 'parnotes', 'parrun', 'parsa', 'parselines',
            'parsitex', 'parskip', 'pas-cours', 'pas-crosswords', 'pas-cv', 'pas-tableur', 'pascaltriangle', 'passivetex',
            'patch', 'patchcmd', 'patgen', 'patgen2-tutorial', 'path', 'pauldoc', 'pawpict', 'pax', 'pb-diagram',
            'pbalance', 'pbibtex-base', 'pbibtex-manual', 'pbm2tex', 'pbmtogf', 'pbmtopk', 'pbox', 'pbsheet', 'pcarl',
            'pcfonts', 'pclnfss', 'pdbf-toolkit', 'pdcmac', 'pdf-forms-tutorial', 'pdf-mps-supp', 'pdf-trans', 'pdf14',
            'pdfarticle', 'pdfbook', 'pdfbook2', 'pdfcol', 'pdfcolfoot', 'pdfcolmk', 'pdfcolparallel', 'pdfcolparcolumns',
            'pdfcomment', 'pdfcprot', 'pdfcrop', 'pdfcrypt', 'pdfescape', 'pdfextra', 'pdfjam', 'pdflatexpicscale',
            'pdflscape', 'pdfmanagement-testphase', 'pdfmarginpar', 'pdfmsym', 'pdfoverlay', 'pdfpagediff', 'pdfpages',
            'pdfpc', 'pdfpc-movie', 'pdfprivacy', 'pdfrack', 'pdfrender', 'pdfreview', 'pdfscreen', 'pdfslide',
            'pdfsync', 'pdftex', 'pdftex-def', 'pdftex-djgpp', 'pdftex-oztex', 'pdftex-quiet', 'pdftex_oztex', 'pdftexcmds',
            'pdftricks', 'pdftricks2', 'pdfx', 'pdfxup', 'pecha', 'pedigree-perl', 'penlight', 'penrose', 'perception',
            'perfectcut', 'perltex', 'permute', 'perpage', 'persian-bib', 'petiteannonce', 'petri-nets', 'pf2afm',
            'pfarrei', 'pfdicons', 'pfm2afm', 'pfnote', 'pgf', 'pgf-blur', 'pgf-cmykshadings', 'pgf-interference',
            'pgf-periodictable', 'pgf-pie', 'pgf-soroban', 'pgf-spectra', 'pgf-umlcd', 'pgf-umlsd', 'pgfgantt',
            'pgfkeys', 'pgfkeyx', 'pgfmath-xfp', 'pgfmolbio', 'pgfmorepages', 'pgfopts', 'pgfornament', 'pgfornament-han',
            'pgfplots', 'pgfplotstable', 'pgothic', 'phaistos', 'phfcc', 'phfextendedabstract', 'phffullpagefigure',
            'phfnote', 'phfparen', 'phfqit', 'phfquotetext', 'phfsvnwatermark', 'phfthm', 'philex', 'philokalia',
            'philosophersimprint', 'phoenician', 'phoncard', 'phonenumbers', 'phonetic', 'phonrule', 'photo', 'photobook',
            'phy-bstyles', 'physconst', 'physe', 'physics', 'physics2', 'physunits', 'physymb', 'phyzzx', 'pi',
            'piano', 'picinpar', 'picins', 'picmac', 'pict2e', 'pictex', 'pictex-autoarea', 'pictex2', 'pictexsum',
            'pictexwd', 'picture', 'piechart', 'piechartmp', 'piff', 'piff-ams', 'pifont', 'pigpen', 'pinlabel',
            'pinoutikz', 'pitex', 'piton', 'pittetd', 'pitthesis', 'pixelart', 'pixelarttikz', 'pkbbox', 'pkfind',
            'pkfix', 'pkfix-helper', 'pkgcheck', 'pkgloader', 'pkuthss', 'pkware', 'pl', 'pl-mf', 'placeat', 'placeins',
            'placeins-plain', 'plain', 'plain-cm', 'plain-ltx', 'plainmisc', 'plainpkg', 'plainyr', 'plantslabels',
            'plantuml', 'plari', 'plates', 'platex', 'platex-tools', 'platexcheat', 'plautopatch', 'play', 'play-font',
            'playcards', 'playfair', 'plcalendar', 'plex', 'plex-otf', 'plfonts', 'plhyph', 'plimsoll', 'plipsum',
            'plnfss', 'plpsfont', 'plstmary', 'pm-isomath', 'pmat', 'pmboxdraw', 'pmcstex', 'pmdb', 'pmdpl', 'pmgraph',
            'pmhanguljamo', 'pmtex', 'pmx', 'pmxchords', 'pnas', 'pnas2009', 'png2pdf', 'poemscol', 'poetica', 'poetry',
            'poetrytex', 'pointruler', 'poiretone', 'polexpr', 'poligraf', 'polishlipsum', 'polski', 'poltawski',
            'polyglossia', 'polynom', 'polynomial', 'polytable', 'poorman', 'poormanlog', 'popupmenu', 'portable-miktex',
            'portland', 'pos-at', 'postage', 'postcards', 'poster', 'poster-mac', 'postnotes', 'powerdot', 'powerdot-fuberlin',
            'powerdot-tuliplab', 'ppchtex', 'pphlp', 'ppower4', 'ppr-prv', 'ppt-slides', 'pracjourn', 'practical-latex',
            'practicalreports', 'precattl', 'prelim', 'prelim2e', 'prepr', 'preprint', 'prerex', 'present', 'presentations',
            'presentations-en', 'pressrelease', 'prettyref', 'prettytok', 'preview', 'preview-latex', 'prftree',
            'principia', 'printbib', 'printlen', 'proba', 'probsoln', 'proc', 'processkv', 'prociagssymp', 'prodint',
            'productbox', 'profcollege', 'proflabo', 'proflycee', 'progkeys', 'program', 'progress', 'progressbar',
            'projlib', 'proof', 'proof-at-the-end', 'proofread', 'proofs', 'prooftrees', 'properties', 'proposal',
            'prosper', 'protecteddef', 'protex', 'protext', 'protocol', 'protosem', 'prtec', 'prv', 'przechlewski-book',
            'ps2eps', 'ps2mf', 'ps2pk', 'ps4mf', 'ps4mf-dos', 'ps4pdf', 'ps_conv', 'ps_view', 'psbao', 'psbox',
            'psboxit', 'pseudo', 'pseudocode', 'psfig', 'psfixbb', 'psfont', 'psfonts', 'psfonts-tools', 'psfrag',
            'psfrag-italian', 'psfragger', 'psfragx', 'psgo', 'psgreek', 'psizzl', 'pslatex', 'psmerge', 'psnfss',
            'psnfss-source', 'psnfssx', 'psnfssx-8r', 'psnfssx-adobe', 'psnfssx-em', 'psnfssx-luc', 'pspic', 'pspicture',
            'psrip', 'pssplit', 'pst-2dplot', 'pst-3d', 'pst-3dplot', 'pst-abspos', 'pst-am', 'pst-antiprism', 'pst-arrow',
            'pst-asr', 'pst-bar', 'pst-barcode', 'pst-bezier', 'pst-blur', 'pst-bspline', 'pst-calculate', 'pst-calendar',
            'pst-cie', 'pst-circ', 'pst-coil', 'pst-contourplot', 'pst-cox', 'pst-dart', 'pst-dbicons', 'pst-diffraction',
            'pst-electricfield', 'pst-eps', 'pst-eucl', 'pst-eucl-translation-bg', 'pst-exa', 'pst-feyn', 'pst-fill',
            'pst-fit', 'pst-flags', 'pst-fp', 'pst-fr3d', 'pst-fractal', 'pst-fun', 'pst-func', 'pst-gantt', 'pst-geo',
            'pst-geometrictools', 'pst-gr3d', 'pst-grad', 'pst-graphicx', 'pst-hsb', 'pst-infixplot', 'pst-intersect',
            'pst-jtree', 'pst-knot', 'pst-labo', 'pst-layout', 'pst-lens', 'pst-light3d', 'pst-lsystem', 'pst-magneticfield',
            'pst-marble', 'pst-math', 'pst-mirror', 'pst-moire', 'pst-node', 'pst-ob3d', 'pst-ode', 'pst-optexp',
            'pst-optic', 'pst-osci', 'pst-ovl', 'pst-pad', 'pst-pdf', 'pst-pdgr', 'pst-perspective', 'pst-platon',
            'pst-plot', 'pst-poker', 'pst-poly', 'pst-pulley', 'pst-qtree', 'pst-rputover', 'pst-rubans', 'pst-shell',
            'pst-sigsys', 'pst-slpe', 'pst-solarsystem', 'pst-solides3d', 'pst-soroban', 'pst-spectra', 'pst-spinner',
            'pst-spirograph', 'pst-stru', 'pst-support', 'pst-text', 'pst-thick', 'pst-tools', 'pst-tree', 'pst-turtle',
            'pst-tvz', 'pst-uml', 'pst-vectorian', 'pst-vehicle', 'pst-venn', 'pst-vowel', 'pst-vue3d', 'pst-xkey',
            'pst2pdf', 'pstdoc', 'pstex', 'pstoedit', 'pstool', 'pstotext', 'pstrees', 'pstricks', 'pstricks-add',
            'pstricks-base', 'pstricks-calcnotes', 'pstricks-examples', 'pstricks-examples-7', 'pstricks-examples-en',
            'pstring', 'psu-thesis', 'psutils', 'ptex', 'ptex-base', 'ptex-fontmaps', 'ptex-fonts', 'ptex-manual',
            'ptex-texmf', 'ptex2pdf', 'ptext', 'pthyphs', 'ptmsc', 'ptolemaicastronomy', 'ptptex', 'ptsans', 'ptserif',
            'punk', 'punk-latex', 'punknova', 'purifyeps', 'puyotikz', 'pwebmac', 'pwt', 'pxbase', 'pxchfon', 'pxcjkcat',
            'pxfonts', 'pxgreeks', 'pxjahyper', 'pxjodel', 'pxpgfmark', 'pxpic', 'pxrubrica', 'pxtatescale', 'pxtxalfa',
            'pxufont', 'pybib', 'pybliographer', 'pydocstrip', 'pygmentex', 'pyluatex', 'python', 'pythonhighlight',
            'pythonimmediate', 'pythontex', 'pzccal', 'qbibman', 'qcircuit', 'qcm', 'qdtexvpl', 'qed', 'qfig', 'qfonts',
            'qm', 'qms', 'qobitree', 'qrbill', 'qrcode', 'qrcstamps', 'qsharp', 'qstest', 'qsymbols', 'qtree', 'qualitype',
            'quantikz', 'quantumarticle', 'quattrocento', 'quickreaction', 'quicktype', 'quiz2socrative', 'quotation',
            'quotchap', 'quote', 'quotes', 'quoting', 'quotmark', 'quran', 'quran-bn', 'quran-de', 'quran-ur', 'qyxf-book',
            'r-und-s', 'r2bib', 'ragged', 'ragged2e', 'raggedr', 'rail', 'rake4latex', 'raleway', 'ran_toks', 'randbild',
            'random', 'randomlist', 'randomwalk', 'randtext', 'rangecite', 'rangen', 'rank-2-roots', 'ransom', 'ratex',
            'ratexdb', 'rawfonts', 'rawprint', 'rbt-mathnotes', 'rccol', 'rcs', 'rcs-multi', 'rcs-pln', 'rcsinfo',
            'readablecv', 'readarray', 'readprov', 'realboxes', 'realcalc', 'realhats', 'realscripts', 'realtranspose',
            'rec-thy', 'recipe', 'recipebook', 'recipecard', 'recorder-fingering', 'rectopma', 'recycle', 'redefine',
            'redis', 'redit', 'refcheck', 'refcount', 'refenums', 'refer', 'refer-tools', 'references', 'reflectgraphics',
            'refman', 'refreshpdf', 'refstyle', 'regcount', 'regexpatch', 'register', 'regstats', 'reledmac', 'reledpar',
            'relenc', 'relsize', 'removefr', 'remreset', 'renditions', 'reotex', 'repeat', 'repeatindex', 'repere',
            'repltext', 'report', 'required', 'rerunfilecheck', 'res', 'rescansync', 'resizegather', 'resmes', 'resolsysteme',
            'resphilosophica', 'rest-api', 'resumecls', 'resumemac', 'returntogrid', 'reverxii', 'revnum', 'revquantum',
            'revtex', 'revtex4-0', 'revtex4-1', 'rfc2bib', 'rfil', 'rgb', 'rgltxdoc', 'ribbonproofs', 'richtext',
            'rjlparshap', 'rlepsf', 'rmannot', 'rmathbr', 'rmligs', 'rmpage', 'rmthm', 'rnototex', 'robot-man',
            'robotarm', 'roboto', 'robustcommand', 'robustindex', 'rojud', 'romanbar', 'romanbarpagenumber', 'romandeadf',
            'romaniantex', 'romanneg', 'romannum', 'rosario', 'rotate', 'rotate-textures', 'rotating', 'rotchiffre',
            'rotfloat', 'rotpages', 'rotunda', 'roundbox', 'roundrect', 'rpg-module', 'rplain', 'rputover', 'rrgtrees',
            'rsc', 'rsfs', 'rsfso', 'rst', 'rterface', 'rtf2latex2e', 'rtf2tex', 'rtkinenc', 'rtklage', 'rtsched',
            'rubik', 'rubikcube', 'rubikrotation', 'rubiktwocube', 'ruhyphen', 'rule-d', 'ruled-tables', 'ruler',
            'rulerbox', 'rulercompass', 'runcode', 'rune', 'runic', 'runtex', 'russ', 'russian-help', 'rustic',
            'rutitlepage', 'rviewport', 'rvwrite', 'ryersonsgsthesis', 'ryethesis', 's2latex', 'sa-tikz', 'sacsymb',
            'sae', 'saferef', 'sageep', 'sagetex', 'sam2p', 'samples', 'sanhyph', 'sanitize-umlaut', 'sankey', 'sans',
            'sanskrit', 'sanskrit-t1', 'sansmath', 'sansmathaccent', 'sansmathfonts', 'sapthesis', 'sarabian', 'sasnrdisplay',
            'sauerj', 'sauter', 'sauterfonts', 'saveenv', 'savefnmark', 'savesym', 'savetrees', 'sbtex', 'sc21',
            'sc21-wg1', 'scale', 'scalebar', 'scalefnt', 'scalerel', 'scanpages', 'schedule', 'schedule209', 'schemabloc',
            'schemata', 'schemetex', 'schemeweb', 'schola-otf', 'scholax', 'schooldocs', 'schule', 'schulmathematik',
            'schulschriften', 'schwalbe-chess', 'schwell', 'scientific-thesis-cover', 'scientificauthor', 'scientificpaper',
            'scientificviewer', 'scikgtex', 'sciposter', 'sciwordconv', 'sclang-prettifier', 'scmac', 'scontents',
            'scorecard', 'scrabble', 'scraddr', 'scrambledenvs', 'scrartcl', 'scrarticle', 'scratch', 'scratch3',
            'scratchx', 'scrbase', 'scrbook', 'scrdate', 'screen', 'screenplay', 'screenplay-pkg', 'scrextend',
            'scrindex', 'script', 'script-font', 'scriptfonts', 'scripttex', 'scripture', 'scrjrnl', 'scrjura',
            'scrlayer', 'scrlayer-fancyhdr', 'scrlayer-notecolumn', 'scrlayer-scrpage', 'scrletter', 'scrlfile',
            'scrlttr2', 'scrlttr2copy', 'scrpage2', 'scrreport', 'scrreprt', 'scrtime', 'scrwfile', 'scsnowman',
            'scyrillic', 'sdaps', 'sdrt', 'sduthesis', 'se2thesis', 'secdot', 'seceqn', 'secnum', 'secret', 'section',
            'sectionbox', 'sectionbreak', 'sectsty', 'seealso', 'sehyph', 'selectp', 'selectpage', 'selinput', 'selnolig',
            'semantex', 'semantic', 'semantic-markup', 'semaphor', 'semesterplanner', 'seminar', 'semioneside',
            'semproc', 'semtex', 'semtrans', 'sentences', 'sepfootnotes', 'sepnum', 'seqsplit', 'serbian-apostrophe',
            'serbian-book', 'serbian-date-lat', 'serbian-def-cyr', 'serbian-lig', 'serbianpart', 'serial', 'sesamanuel',
            'sesstime', 'setdeck', 'setouterhbox', 'setspace', 'setstrut', 'settobox', 'settosize', 'settosize-ltx',
            'seu-ml-assign', 'seuthesis', 'seuthesix', 'sexam', 'sf298', 'sfarticle', 'sffms', 'sfg', 'sfheaders',
            'sfmath', 'sfwmac', 'sgame', 'sgmlcmpt', 'shadbox', 'shade', 'shadebox', 'shadethm', 'shading', 'shadow',
            'shadowtext', 'shalom', 'shapepar', 'shapepatch', 'shapes', 'shavian', 'shdoc', 'shellesc', 'shhyphl',
            'shipunov', 'shlatex', 'shobhika', 'short-math-guide', 'shortcuttool', 'shortlst', 'shortmathj', 'shorttoc',
            'shortvrb', 'show2e', 'showcharinbox', 'showdim', 'showexpl', 'showframe', 'showhyphenation', 'showhyphens',
            'showkerning', 'showkeys', 'showlabels', 'showtags', 'shsulet', 'shtthesis', 'shuffle', 'si', 'siam',
            'side', 'sidecap', 'sidenotes', 'sidenotesplus', 'sides', 'siggraph', 'signchart', 'sikumuna', 'silence',
            'sillypage', 'simple-resume-cv', 'simple-thesis-dissertation', 'simplebnf', 'simplecd', 'simplecv',
            'simpleicons', 'simpleinvoice', 'simplekv', 'simplenodes', 'simpleoptics', 'simpler-wick', 'simples-matrices',
            'simplewick', 'simplified-latex', 'simplivre', 'simpsons', 'simurgh', 'sines', 'sinhala', 'sirlin',
            'sistyle', 'sitem', 'siunits', 'siunitx', 'skak', 'skaknew', 'skb', 'skdoc', 'skeldoc', 'sketch', 'skeycommand',
            'skeyval', 'skills', 'skmath', 'skrapport', 'skull', 'slantsc', 'slashbox', 'slashed', 'slatex', 'slatex-scheme',
            'slatex_scheme', 'slem', 'slemph', 'slhyph', 'slidenotes', 'slides', 'slideshow', 'sltables', 'smallcap',
            'smaller', 'smalltableof', 'smalltalk', 'smart-eqn', 'smartdiagram', 'smartmn', 'smartref', 'smartunits',
            'smflatex', 'smiletex', 'snapshot', 'snaptodo', 'snote', 'snotez', 'sober', 'sobolev', 'softfonts',
            'softmaker-alteschwabacher', 'softmaker-artistic', 'softmaker-baskervillenova', 'softmaker-bonita',
            'softmaker-broadway', 'softmaker-canossa', 'softmaker-congress', 'softmaker-delanocaps', 'softmaker-digital',
            'softmaker-egyptiennestd', 'softmaker-flagstaff', 'softmaker-freefont', 'softmaker-grenoble', 'softmaker-helium',
            'softmaker-heliumtwo', 'softmaker-henderson', 'softmaker-iceberg', 'softmaker-inverserif', 'softmaker-jugendstil',
            'softmaker-marseille', 'softmaker-moab', 'softmaker-nevada', 'softmaker-newcastle', 'softmaker-oldblackletter',
            'softmaker-quadrat', 'softmaker-stonehand', 'softmaker-sunset', 'softmaker-tampa', 'softmaker-vagrounded',
            'softmaker-velo', 'softmaker-veracruz', 'softmakerfreefont', 'somedefs', 'songbook', 'songproj', 'songs',
            'sorhyph', 'sort-by-letters', 'soton', 'soul', 'soulpos', 'soulutf8', 'soup', 'source2e', 'sourcecodepro',
            'sourcesanspro', 'sourceserifpro', 'southarabian', 'soyombo', 'spacekern', 'spacingtricks', 'spain',
            'spalign', 'spanish', 'spanish-mx', 'spark-otf', 'sparklines', 'spath3', 'spbmark', 'spectral', 'spectralsequences',
            'spelling', 'sphack', 'sphdthesis', 'sphyphb', 'spiderweb', 'spie', 'spix', 'splines', 'splint', 'split',
            'splitbib', 'splitindex', 'spot', 'spotcolor', 'spreadtab', 'springer', 'sprite', 'spverbatim', 'sqltex',
            'sqrcaps', 'sr-half-compound', 'sr-hyphen-spec', 'sr-vorl', 'srbtiks', 'srcltx', 'srcredact', 'srdp-mathematik',
            'srhyphc', 'srune', 'sseq', 'sshdbk10', 'sslides', 'ssqquote', 'stables', 'stabular', 'stack', 'stackengine',
            'stackrel', 'stage', 'stampinclude', 'standalone', 'stanli', 'starfont', 'startex', 'startlatex2e',
            'statex', 'statex2', 'statistics', 'statistik', 'statmath', 'statrep', 'staves', 'stdclsdv', 'stdpage',
            'stealcaps', 'steinmetz', 'stellenbosch', 'step', 'stepgreek', 'stex', 'stfloats', 'stickstoo', 'stix',
            'stix2-otf', 'stix2-type1', 'stmaryrd', 'stoneipa', 'storebox', 'storecmd', 'strands', 'streetex', 'stricttex',
            'stringenc', 'stringstrings', 'structmech', 'struktex', 'sttools', 'stubs', 'studenthandouts', 'studies-lm',
            'sty2dtx', 'style-showcase', 'styledcmd', 'suanpan', 'subcaption', 'subdepth', 'subdocs', 'subeqn',
            'subeqnarray', 'subfig', 'subfigmat', 'subfigure', 'subfiles', 'subfloat', 'sublabel', 'subscript',
            'substances', 'substitutefont', 'substr', 'subsupscripts', 'subtext', 'sudoku', 'sudokubundle', 'sueterlin',
            'suffix', 'suftesi', 'sugconf', 'superiors', 'supertabular', 'suppose', 'susy', 'suthesis', 'sverb',
            'svg', 'svg-inkscape', 'svgcolor', 'svn', 'svn-multi', 'svn-prov', 'svninfo', 'svrsymbols', 'swebib',
            'swetex', 'swfigure', 'swiftex', 'swimgraf', 'switcheml', 'swrule', 'swungdash', 'syllogism', 'symbats3',
            'symbolindex', 'sympycalc', 'sympytex', 'synapsen', 'synctex-parser', 'syngen', 'synproof', 'syntax-mdw',
            'syntax2', 'syntaxdi', 'syntonly', 'syntrace', 'synttree', 'syriac', 'systcontrolletters', 'systeme',
            't-angles', 't1-fraktur', 't1enc', 't1infos', 't1subset', 't1tools', 't1utils', 't2', 'tab4tex', 'tabbing',
            'tabbingbox', 'tabfigures', 'table-fct', 'tableauvariations', 'tableaux', 'tablefootnote', 'tableof',
            'tables', 'tablestyles', 'tablists', 'tablor', 'tabls', 'tablvar', 'tabriz-thesis', 'tabsatz', 'tabstackengine',
            'tabto', 'tabto-generic', 'tabto-ltx', 'tabu', 'tabularborder', 'tabularcalc', 'tabularew', 'tabularht',
            'tabularkv', 'tabularray', 'tabulars-e', 'tabularx', 'tabulary', 'tabvar', 'tabverb', 'tagging', 'tagpair',
            'tagpdf', 'talk', 'talos', 'tamefloats', 'tamethebeast', 'tamil-omega', 'tangle', 'tango-weevil', 'tangocolors',
            'tangramtikz', 'tap', 'tape', 'tapir', 'tasks', 'taylor', 'tbe', 'tccompat', 'tclldoc', 'tcltexed',
            'tcobrowser', 'tcolorbox', 'tcvn', 'tdclock', 'tds', 'tdsfrmath', 'techexplorer', 'technica', 'technics',
            'technion-thesis-template', 'techreport', 'ted', 'teencontrex', 'telprint', 'telugu', 'templates-fenn',
            'templates-sommer', 'templatetools', 'tempora', 'tengtex', 'tengwar', 'tengwarscript', 'tensind', 'tensor',
            'termcal', 'termcal-de', 'termes-otf', 'termlist', 'termmenu', 'termsim', 'tesla', 'testeq', 'testflow',
            'testfont', 'testhyphens', 'testidx', 'testmath', 'tetex', 'tetragonos', 'teubner', 'tex', 'tex--xet',
            'tex-converter', 'tex-ewd', 'tex-extensions', 'tex-font-errors-cheatsheet', 'tex-fpc', 'tex-gpc', 'tex-gyre',
            'tex-gyre-adventor', 'tex-gyre-bonum', 'tex-gyre-chorus', 'tex-gyre-cursor', 'tex-gyre-heros', 'tex-gyre-math',
            'tex-gyre-math-bonum', 'tex-gyre-math-dejavu', 'tex-gyre-math-pagella', 'tex-gyre-math-schola', 'tex-gyre-math-termes',
            'tex-gyre-pagella', 'tex-gyre-schola', 'tex-gyre-termes', 'tex-implementors', 'tex-ini-files', 'tex-it',
            'tex-kurs', 'tex-label', 'tex-locale', 'tex-mag', 'tex-math', 'tex-nutshell', 'tex-overview', 'tex-ps',
            'tex-references', 'tex-virtual-academy-pl', 'tex-vpat', 'tex2bib', 'tex2ltx', 'tex2mail', 'tex2page',
            'tex2rtf', 'tex2tok', 'tex2word', 'tex4ebook', 'tex4ht', 'tex_converter', 'tex_it', 'texaccents', 'texapi',
            'texas', 'texbook', 'texbuch', 'texbytopic', 'texcad32', 'texchord', 'texcount', 'texdate', 'texdef',
            'texdepend', 'texdeps', 'texdiff', 'texdimens', 'texdirflatten', 'texdoc', 'texdoctk', 'texdraw', 'texed',
            'texemplar', 'texfaq', 'texfilt', 'texfindpkg', 'texfot', 'texhax', 'texi2dvi-latest', 'texi2html',
            'texi2roff', 'texi2www', 'texilikechaps', 'texilikecover', 'texindex', 'texinfo', 'texinfo-latest',
            'texlab', 'texline', 'texlipse', 'texlist', 'texlive', 'texlive-dummy-enterprise-linux', 'texlive-dummy-enterprise-linux-6',
            'texlive-dummy-enterprise-linux-7', 'texlive-dummy-enterprise-linux-8', 'texlive-dummy-fedora', 'texlive-dummy-opensuse',
            'texlive-repo', 'texlive-source', 'texliveonfly', 'texlog-extract', 'texlog_extract', 'texloganalyser',
            'texlogfilter', 'texlogos', 'texlogsieve', 'texmacs', 'texmalli', 'texmate', 'texments', 'texmuse',
            'texnegar', 'texniccenter', 'texonly', 'texosquery', 'texpack', 'texperf', 'texpict', 'texpictex', 'texplate',
            'texpower', 'texproject', 'texproposal', 'texref', 'texshade', 'texshell', 'texshell32', 'texshop',
            'texsis', 'texsketch', 'texsort', 'texspell', 'texsurgery', 'text1', 'text2bib', 'textarea', 'textcase',
            'textcomp', 'textcsc', 'textfit', 'textglos', 'textgreek', 'textmerg', 'textool', 'textoolspro', 'textopo',
            'textpath', 'textpos', 'textualicomma', 'textures-metrics', 'texvc', 'texware', 'tfmpk', 'tfmpktest',
            'tfrupee', 'tgothic', 'tgrind', 'tgrind209', 'thai-rmit', 'thai-usl', 'thaienum', 'thaifonts-arundina',
            'thailatex', 'thaispec', 'thalie', 'theanodidot', 'theanomodern', 'theanooldstyle', 'theapa', 'theatre',
            'theorem', 'theoremref', 'thepdfnumber', 'thermodynamics', 'these', 'thesis', 'thesis-ekf', 'thesis-gwu',
            'thesis-qom', 'thesis-titlepage-fhac', 'thinsp', 'thirteen', 'thmbox', 'thmtools', 'thorshammer', 'threadcol',
            'threecol', 'threecolumn', 'threeddice', 'threeparttable', 'threeparttablex', 'thrmappendix', 'thsmc',
            'thuaslogos', 'thubeamer', 'thucoursework', 'thumb', 'thumbpdf', 'thumbs', 'thumby', 'thuthesis', 'tib',
            'tibetan', 'ticket', 'ticollege', 'tidyres', 'tie', 'tif2eps', 'tiff', 'tikz', 'tikz-3dplot', 'tikz-among-us',
            'tikz-bagua', 'tikz-bayesnet', 'tikz-bbox', 'tikz-cd', 'tikz-dependency', 'tikz-dimline', 'tikz-ext',
            'tikz-feynhand', 'tikz-feynman', 'tikz-imagelabels', 'tikz-inet', 'tikz-kalender', 'tikz-karnaugh',
            'tikz-ladder', 'tikz-lake-fig', 'tikz-layers', 'tikz-mirror-lens', 'tikz-nef', 'tikz-network', 'tikz-nfold',
            'tikz-opm', 'tikz-optics', 'tikz-page', 'tikz-palattice', 'tikz-planets', 'tikz-qtree', 'tikz-relay',
            'tikz-sfc', 'tikz-swigs', 'tikz-timing', 'tikz-trackschematic', 'tikz-truchet', 'tikz3d-fr', 'tikzbricks',
            'tikzcodeblocks', 'tikzducks', 'tikzfill', 'tikzinclude', 'tikzlings', 'tikzmark', 'tikzmarmots', 'tikzorbital',
            'tikzpackets', 'tikzpagenodes', 'tikzpeople', 'tikzpfeile', 'tikzpingus', 'tikzposter', 'tikzscale',
            'tikzsymbols', 'tikztosvg', 'tikzviolinplots', 'tile-graphic', 'timbreicmc', 'time', 'time-gen', 'timeline',
            'times', 'timetab', 'timetable', 'timing', 'timing-diagrams', 'tinos', 'tinyc2l', 'tip', 'tipa', 'tipa-de',
            'tipauni', 'tipfr', 'tipos', 'tiscreen', 'titlecaps', 'titlefoot', 'titlepage-uni-dortmund', 'titlepages',
            'titlepic', 'titleps', 'titleref', 'titles', 'titlesec', 'titletoc', 'titling', 'tkbibtex', 'tkdvi',
            'tkhyph', 'tktexcad', 'tkz-base', 'tkz-berge', 'tkz-doc', 'tkz-euclide', 'tkz-fct', 'tkz-graph', 'tkz-kiviat',
            'tkz-linknodes', 'tkz-orm', 'tkz-tab', 'tkzexample', 'tlaunch', 'tlc-article', 'tlc2-errata', 'tlc2-examples',
            'tlc3-examples', 'tlcockpit', 'tlg2latex', 'tlmgr-intro-zh-cn', 'tlmgrbasics', 'tmmath', 'tmmath-fonts',
            'tmview', 'to-be-determined', 'toc', 'toc-zar', 'tocbasic', 'tocbibind', 'tocdata', 'tocenter', 'tocloft',
            'tocstyle', 'tocvsec2', 'todo', 'todonotes', 'toil', 'tokcycle', 'tokenizer', 'tolkienfonts', 'tonevalue',
            'toolbox', 'topcapt', 'topfloat', 'topiclongtable', 'topletter', 'topsection', 'toptesi', 'totalcount',
            'totcount', 'totpages', 'tpcmfont', 'tpic2pdftex', 'tpslifonts', 'tpx', 'tqft', 'tr2latex', 'trace',
            'tracking', 'tracklang', 'trademarks', 'trajan', 'tram', 'tramlines', 'trans', 'transfig', 'translation-array-fr',
            'translation-arsclassica-de', 'translation-biblatex-de', 'translation-booktabs-fr', 'translation-chemsym-de',
            'translation-dcolumn-fr', 'translation-ecv-de', 'translation-enumitem-de', 'translation-europecv-de',
            'translation-filecontents-de', 'translation-footmisc-de', 'translation-moreverb-de', 'translation-natbib-fr',
            'translation-pst-jtree-de', 'translation-tabbing-fr', 'translations', 'translator', 'transparent', 'transparent-io',
            'tree-dvips', 'treedef', 'treesvr', 'treetex-ltx209', 'treetex-plain', 'trfsigns', 'trig', 'trigonometry',
            'trimspaces', 'trivfloat', 'trsym', 'truchet', 'truecols', 'truetypemetrics', 'truetypetotype42', 'truncate',
            'truthtable', 'try', 'tsconfig', 'tsemlines', 'tsipa', 'tsvtemplate', 'tt2001', 'ttf-howto', 'ttf2mf',
            'ttf2pfb', 'ttf2pt1', 'ttf2tex', 'ttftogf', 'tth', 'ttn', 'ttt', 'tucv', 'tuda-ci', 'tudscr', 'tufte-latex',
            'tugboat', 'tugboat-plain', 'tugboat-toc', 'tui', 'turabian', 'turabian-formatting', 'turkish', 'turkishintro',
            'turkmen', 'turnstile', 'turnthepage', 'tvs', 'twcal', 'tweb', 'twemoji-colr', 'twemojis', 'twocolumns',
            'twoopt', 'twoside', 'twoup-gen', 'twoupltx', 'txfonts', 'txfontsb', 'txgreeks', 'txp', 'txt', 'txt2latex',
            'txt2tex', 'txuprcal', 'type1cm', 'type1ec', 'typearea', 'typed-checklist', 'typedref', 'typeface',
            'typehtml', 'typeoutfileinfo', 'typespec', 'typewriter', 'typicons', 'typoaid', 'typografie', 'typogrid',
            'tzplot', 'u8tex', 'uaclasses', 'uafthesis', 'uantwerpendocs', 'uassign', 'ucalgmthesis', 'ucbthesis',
            'ucdavisthesis', 'ucharcat', 'ucharclasses', 'ucs', 'ucsmonograph', 'ucthesis', 'ucthesis209', 'udes-genie-these',
            'udesoftec', 'uebungsblatt', 'uestcthesis', 'ufrgscca', 'ugarite', 'ugaritic', 'uhc', 'uhhassignment',
            'uhrzeit', 'uhthesis', 'uiucredborder', 'uiucthesis', 'uk-tex-faq', 'ukbill', 'ukdate', 'ukhyph', 'ukrhyph',
            'uktex', 'uktug-bask', 'ulem', 'ulqda', 'ulsy', 'ulsy-ps', 'ulthese', 'ultratex', 'umbclegislation',
            'umich-thesis', 'uml', 'umlaute', 'umoline', 'umrand', 'umthesis', 'umtypewriter', 'unam-thesis', 'unamth-template',
            'unamthesis', 'unbtex', 'uncial', 'undergradmath', 'underlin', 'underlin-gen', 'underoverlap', 'underscore',
            'undertilde', 'undertilde-gen', 'undolabl', 'undump', 'unfinished', 'unfonts-core', 'unfonts-extra',
            'uni-titlepage', 'uni-wtal-ger', 'uni-wtal-lin', 'unicode', 'unicode-alphabets', 'unicode-bidi', 'unicode-data',
            'unicode-math', 'unicodefonttable', 'unifith', 'unifront', 'unigrazpub', 'unimath-plain-xetex', 'uninormalize',
            'uniquecounter', 'unisc', 'unisugar', 'unitconv', 'unitipa', 'unitn-bimrep', 'units', 'unitsdef', 'universa',
            'universalis', 'univie-ling', 'unixman', 'unizgklasa', 'unouter', 'unpacked', 'unravel', 'unswcover',
            'unswthesis', 'untex', 'uol-physics-report', 'uothesis', 'uowthesis', 'uowthesistitlepage', 'upca',
            'upgreek', 'uplatex', 'upmendex', 'upmethodology', 'uppunctlm', 'upquote', 'upref', 'uptex', 'uptex-base',
            'uptex-fonts', 'upzhkinsoku', 'urcls', 'uri', 'url', 'urlbst', 'urw', 'urw-antiqua', 'urw-arial', 'urw-base35',
            'urw-garamond', 'urw-grotesq', 'urwchancal', 'urwvf', 'uscthesis', 'usebib', 'usenix', 'ushort', 'ushyph',
            'uspace', 'uspatent', 'usrguide', 'ut-backref', 'ut-thesis', 'utexasthesis', 'utf2any', 'utf8add', 'utf8mex',
            'utfsym', 'util-half', 'utopia', 'utorontothesis', 'utthesis', 'uvaletter', 'uwa-colours', 'uwa-letterhead',
            'uwa-pcf', 'uwa-pif', 'uwmslide', 'uwthesis', 'uwthesis209', 'va', 'vak', 'vancouver', 'variablelm',
            'variations', 'varindent', 'varindex', 'varioref', 'varisize', 'varsects', 'varsfromjobname', 'varwidth',
            'vaucanson-g', 'vc', 'vcell', 'vdm', 'vdmlisting', 'vector', 'venn', 'venndiagram', 'venturisadf', 'verbasef',
            'verbatim', 'verbatim-gen', 'verbatim-pln', 'verbatim-tub', 'verbatimbox', 'verbatimcopy', 'verbdef',
            'verbinp', 'verbments', 'verbtext', 'verbtim2', 'verdana', 'verifica', 'verifiche', 'verse', 'version',
            'versions', 'versonotes', 'vertbars', 'vertex', 'vf-howto', 'vf-knuth', 'vfcomb', 'vfinst', 'vfware',
            'vgrid', 'vhistory', 'vicentino', 'vietnet', 'viiptart', 'viking', 'vispeech', 'visualfaq', 'visualfaq-fr',
            'visualpstricks', 'visualtex', 'visualtikz', 'vita', 'vita209', 'vmargin', 'vmspell', 'vmsps', 'vntex',
            'vntex-nonfree', 'vocaltract', 'volumes', 'voss-mathcol', 'voss-mathmode', 'vowel', 'vpage', 'vpe',
            'vplutils', 'vpp', 'vrb', 'vrbexin', 'vrsion', 'vruler', 'vslitex', 'vtable', 'vtex-free', 'vutex',
            'vvcode', 'vwcol', 'vxu', 'w-a-schmidt', 'w32tex', 'wadalab', 'wallcalendar', 'wallpaper', 'wargame',
            'warning', 'warpcol', 'was', 'wasy', 'wasy-type1', 'wasy2', 'wasy2-ps', 'wasysym', 'watermark', 'weave',
            'web', 'web2c', 'web2w', 'web9pt', 'webcomp-errata', 'webfiles', 'webguide', 'webmacss', 'webomints',
            'webquiz', 'weekday', 'wheelchart', 'wheretotrim', 'wichura-table', 'widetable', 'widows-and-orphans',
            'wiggly', 'wiki', 'williams', 'willowtreebook', 'win32-emacs-auctex', 'window', 'windvi', 'windycity',
            'winedt', 'winemtex', 'winfonts', 'winlatex', 'winshell', 'wintex2000', 'withargs', 'witharrows', 'withesis',
            'wmaainf', 'wmf2eps', 'wncyr', 'wnri', 'wnri-latex', 'wntamil', 'wochtag', 'woff2ot', 'word2latex',
            'word2tex', 'word2x', 'wordcount', 'wordlike', 'wordml2latex', 'wordweb', 'worksheet', 'worldflags',
            'wotree', 'wp2latex', 'wrapfig', 'wrapfig2', 'wrapstuff', 'wright', 'writeongrid', 'wrtfile', 'wsemclassic',
            'wsuipa', 'wsuipa2tipa', 'wtref', 'xargs', 'xarticle', 'xassoccnt', 'xbibfile', 'xbibtex', 'xbmks',
            'xcharter', 'xcharter-math', 'xcite', 'xcjk2uni', 'xcmr', 'xcntperchap', 'xcoffins', 'xcolor', 'xcolor-material',
            'xcolor-solarized', 'xcomment', 'xcookybooky', 'xcpdftips', 'xdoc', 'xduthesis', 'xduts', 'xdvi', 'xdvik',
            'xdvipdfmx', 'xebaposter', 'xechangebar', 'xecjk', 'xecolor', 'xecolour', 'xecyr', 'xecyrmongolian',
            'xeindex', 'xellipsis', 'xepersian', 'xepersian-hm', 'xesearch', 'xesoul', 'xespotcolor', 'xet-tex',
            'xetal', 'xetex', 'xetex-def', 'xetex-devanagari', 'xetex-greek', 'xetex-itrans', 'xetex-pstricks',
            'xetex-tibetan', 'xetexfontinfo', 'xetexko', 'xetexref', 'xevlna', 'xfakebold', 'xfig', 'xfor', 'xfp',
            'xfrac', 'xgalley', 'xgreek', 'xhfill', 'xifthen', 'xii', 'xii-lat', 'xindex', 'xindy', 'xindy-persian',
            'xint', 'xintexpr', 'xintsession', 'xistercian', 'xits', 'xkcdcolors', 'xkeyval', 'xkvltxp', 'xkvview',
            'xl2latex', 'xlatex', 'xlop', 'xltabular', 'xltxtra', 'xml2pmx', 'xmlplay', 'xmltex', 'xmpincl', 'xmuthesis',
            'xnewcommand', 'xoptarg', 'xparse', 'xpatch', 'xpdf', 'xpdfopen', 'xpeek', 'xpiano', 'xpicture', 'xpinyin',
            'xprintlen', 'xpunctuate', 'xput', 'xq', 'xr', 'xr-hyper', 'xrefwarn', 'xsavebox', 'xsim', 'xskak',
            'xspace', 'xstring', 'xtab', 'xtcapts', 'xtem', 'xtemplate', 'xtexcad', 'xtexshell', 'xtrcode', 'xtuthesis',
            'xunicode', 'xurl', 'xwatermark', 'xwpick', 'xyling', 'xymatrix', 'xymtex', 'xypic', 'xypic-tut-pt',
            'xytree', 'yacco2', 'yafoot', 'yagusylo', 'yaletter', 'yamlvars', 'yandy', 'yannisgr', 'yathesis', 'yax',
            'yazd-thesis', 'yb-book', 'ycbook', 'ydoc', 'yet-another-guide-latex2e', 'yfonts', 'yfonts-otf', 'yfonts-t1',
            'yfrak', 'ygoth', 'yhmath', 'yi4latex', 'yinit', 'yinit-as', 'yinit-otf', 'york-thesis', 'young', 'youngtab',
            'yplan', 'yquant', 'yswab', 'yt4pdf', 'ytableau', 'ytex', 'zaccone', 'zahl2string', 'zblbuild', 'zbmath-review-template',
            'zebra-goodies', 'zed', 'zed-csp', 'zefonts', 'zennote', 'zero', 'zhlineskip', 'zhlipsum', 'zhmakeindex',
            'zhmcjk', 'zhmetrics', 'zhmetrics-uptex', 'zhnumber', 'zhspacing', 'ziffer', 'zigaretten', 'zip', 'zitie',
            'zlmtt', 'zootaxa-bst', 'zref', 'zref-check', 'zref-clever', 'zref-vario', 'zwgetfdate', 'zwpagelayout',
            'zx-calculus', 'zxjafbfont', 'zxjafont', 'zxjatype', 'zztex',
        ),
    ),
    'SYMBOLS' => array(
        0 => array('&', '$', '\\'),
        ),
    'CASE_SENSITIVE' => array(
        GESHI_COMMENTS => false,
        1 => true,
        ),
    'STYLES' => array(
        'KEYWORDS' => array(
            1 => 'color: #2020C0; font-weight: normal;'
            ),
        'COMMENTS' => array(
            1 => 'color: #2C922C; font-style: italic;'
            ),
        'ESCAPE_CHAR' => array(
            0 =>  'color: #000000; font-weight: bold;'
            ),
        'BRACKETS' => array(),
        'STRINGS' => array(
            0 =>  'color: #000000;'
            ),
        'NUMBERS' => array(),
        'METHODS' => array(),
        'SYMBOLS' => array(
            0 =>  'color: #E02020;',
            ),
        'REGEXPS' => array(
            1 => 'color: #2020C0; font-weight: normal;',
            2 => 'color: #800000; font-weight: normal;',
        ),
        'SCRIPT' => array()
        ),
    'URLS' => array(
        1 => 'https://www.ctan.org/pkg/{FNAME}',
        ),
    'OOLANG' => false,
    'OBJECT_SPLITTERS' => array(),
    'REGEXPS' => array(
        // environment
        1 => array(
            GESHI_SEARCH => '(?<=\\\\)(begin|end)(\{)([\w\*]*)(\})',
            GESHI_REPLACE => '\3',
            GESHI_MODIFIERS => '',
            GESHI_BEFORE => '\1\2',
            GESHI_AFTER => '\4'
            ),
        // command
        2 => array(
            GESHI_SEARCH => '(\\\\)(\[|\w*((?=\[)|(?=\{)|(?=\b))|\])',
            GESHI_REPLACE => '\0',
            GESHI_MODIFIERS => '',
            GESHI_BEFORE => '',
            GESHI_AFTER => ''
            ),
        ),
    'STRICT_MODE_APPLIES' => GESHI_NEVER,
    'SCRIPT_DELIMITERS' => array(
        ),
    'HIGHLIGHT_STRICT_BLOCK' => array(
        ),
    'PARSER_CONTROL' => array(
        'COMMENTS' => array(
            'DISALLOWED_BEFORE' => '\\'
        ),
        'KEYWORDS' => array(
            1 => array(
                'DISALLOWED_BEFORE' => '(?:\\\\)(?:usepackage|documentclass)(?:.*\{)\K',
                'DISALLOWED_AFTER' => '(?=\})'
            ),
        ),
        'ENABLE_FLAGS' => array(
            'NUMBERS' => GESHI_NEVER,
            'BRACKETS' => GESHI_NEVER
        )
    )
);
