<?php
/*************************************************************************************
 * mathematica.php
 * --------
 * Author: Connor Glosser (glosser1@gmail.com)
 * Copyright: (c) 2014 Connor Glosser (http://www.msu.edu/~glosser1)
 * Release Version: 1.0.8.11
 * Date Started: 2014/08/11
 *
 * Mathematica language file for GeSHi.
 *
 * COMMENTS
 * --------
 * Mathematica itself uses a lot of hyper-contextual syntax highlighting
 * that doesn't work well outside of their proprietary Notebook interface.
 * Consequently, external syntax highlighting tends to get noisy quickly.
 * Here, I've tried to create a triadic color scheme to distinguish keywords,
 * infix functions, and $-designated variables.
 *
 * CHANGES
 * -------
 * 2014/10/13 (1.0.8.11)
 *  - Removed style variables for compatability
 * 2014/08/11 (1.0.8.11)
 *  - First Release
 *  - Symbols taken from http://reference.wolfram.com/language/guide/AlphabeticalListing.html
 *    (Mathematica Version 10)
 *
 * TODO (updated 2014/08/12)
 * -------------------------
 * - evaluate colored array syntax
 *************************************************************************************
 *
 *     This file is part of GeSHi.
 *
 *   GeSHi is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   GeSHi is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with GeSHi; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ************************************************************************************/
//"Base" styles
//string     = 'color: #666666; font-style: italic;';
//comment    = 'color: #999999; font-style: italic;';

//Purple-green colors
//primary    = 'color: #500D75; font-weight: bold;'; //keywords
//secondary  = 'color: #70A30A; font-weight: bold;'; //infix functions
//tertiary   = 'color: #8C0953; font-weight: bold;'; //$variables
//quaternary = 'color: #AFAF0B; font-weight: bold;'; //potentially array syntax in the future

//Orange-blue colors (similar to python coloring)
//primary    = 'color: #FF7700; font-weight: bold;'; //keywords
//secondary  = 'color: #133CAC; font-weight: bold;'; //infix functions
//tertiary   = 'color: #028E9B; font-weight: bold;'; //$variables
//quaternary = 'color: #FFAD00; font-weight: bold;'; //potentially array syntax in the future

$language_data = array(
    'LANG_NAME' => 'Mathematica',
    'COMMENT_SINGLE' => array(),
    'COMMENT_MULTI' => array(
        '(*' => '*)',
        ),
    'COMMENT_REGEXP' => array(),
    'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
    'QUOTEMARKS' => array(
        1 => '"',
        ),
    'ESCAPE_CHAR' => '',
    'ESCAPE_REGEXP' => array(),
    'HARDQUOTE' => array(),
    'HARDESCAPE' => array(),
    'HARDCHAR' => '',
    'NUMBERS' =>
        GESHI_NUMBER_INT_BASIC | GESHI_NUMBER_OCT_PREFIX | GESHI_NUMBER_HEX_PREFIX |
        GESHI_NUMBER_FLT_SCI_ZERO,
    'KEYWORDS' => array(
        1 => array(
            'AASTriangle','AllowedDimensions','ArcTan','AbelianGroup','AllowGroupClose',
            'ARIMAProcess','AbsoluteCorrelation','AlternatingFactorial','ArithmeticGeometricMean','AbsoluteCorrelationFunction',
            'Above','AlphaChannel','ArgMin','Abs','AlternateImage',
            'AbsoluteDashing','Alternatives','Array','AbsoluteFileName','AmbiguityFunction',
            'AbsoluteTime','AndersonDarlingTest','ArrayPlot','AbsoluteTiming','AngerJ',
            'AccuracyGoal','AnimationDirection','Arrays','ActionMenu','AnimationRate',
            'AcyclicGraphQ','AnimatorBoxOptions','Assert','AddTo','Annotation',
            'AdjustmentBox','AntihermitianMatrixQ','AssociationThread','AdjustmentBoxOptions','Antisymmetric',
            'AffineTransform','ApartSquareFree','AsynchronousTaskObject','After','APIFunction',
            'AirTemperatureData','AppellF1','AutoAction','AiryAi','Append',
            'AiryBiPrime','ArcCosh','Automatic','AiryBiZero','ArcCot',
            'AlgebraicNumberNorm','ArcCurvature','Axes','AlgebraicNumberPolynomial','ARCHProcess',
            'Alignment','ArcSin','Axis','AlignmentPoint','ArcSinDistribution',
            'All','ArcSinh',
            'AllowReverseGroupClose','Arg','AbortProtect','AllTrue','ArgMax',
            'AlternatingGroup','ARMAProcess','AbsoluteCurrentValue','AlternativeHypothesis','ARProcess',
            'AnchoredSearch','ArrayFlatten','AbsoluteThickness','And','ArrayPad',
            'AngularGauge','ArrayReshape','Accuracy','Animate','ArrayRules',
            'AnimationRunning','ASATriangle','ActiveStyle','Animator','AspectRatio',
            'AnnuityDue','AssociationFormat','AdjacencyMatrix','Antialiasing','AssociationMap',
            'AnyTrue','AsymptoticOutputTracker','AffineStateSpaceModel','Apart','Asynchronous',
            'AppearanceElements','Attributes','AirPressureData','AppearanceRules','AugmentedSymmetricPolynomial',
            'Apply','AutoIndent','AiryBi','ArcCos','AutoItalicWords',
            'ArcCsc','AutoScroll','AlgebraicNumberDenominator','ArcCsch','AutoSpacing',
            'ArcSec','AxesOrigin','AlgebraicUnitQ','ArcSech','AxesStyle',
            'ArcTanh','Abort','AllowInlineCells','Area','AbortKernels',
            'ArrayComponents','AbsoluteOptions','AmbiguityList','ArrayDepth','AbsolutePointSize',
            'ArrayQ','AccountingForm','AngleBracket','ArrayResample','Accumulate',
            'Arrow','ActionMenuBoxOptions','AnimationRepetitions','Arrowheads','Activate',
            'AssociateTo','AdjacencyGraph','Annuity','Association','AdjacencyList',
            'Assuming','AdjustTimeSeriesForecast','AntisymmetricMatrixQ','Assumptions','AdministrativeDivisionData',
            'AsynchronousTasks','AircraftData','Appearance','AtomQ','AirportData',
            'AutoMultiplicationSymbol','AlgebraicIntegerQ','ArcCoth','AutorunSequencing','AlgebraicNumber',
            'AutocorrelationTest','AiryAiPrime','AppendTo','AutoDelete','AiryAiZero',
            'AxesEdge','AlgebraicNumberTrace','ArcLength','AxesLabel','Algebraics',
            'BSplineFunction','Below','BlankNullSequence','BSplineSurface','BenfordDistribution',
            'BabyMonsterGroupB','BezierCurve',
            'Backward','BilateralFilter','BorderDimensions','Ball','Binarize',
            'BarLegend','BinomialDistribution','BoundedRegionQ','BarlowProschanImportance','BinomialProcess',
            'BarabasiAlbertGraphDistribution','BinaryReadList','BoundaryDiscretizeRegion','BarChart','BinaryWrite',
            'BartlettHannWindow','BirnbaumImportance','BoxRatios','BartlettWindow','BirnbaumSaundersDistribution',
            'BaseStyle','BitLength','BreadthFirstScan','BatesDistribution','BitNot',
            'Beep','BitShiftRight','BrownForsytheTest','Before','BitXor',
            'BellB','BlackmanWindow','BSplineCurveBoxOptions','BellY','Blank',
            'BenktanderGibratDistribution','Block','BubbleChart3D','BenktanderWeibullDistribution','BlockRandom',
            'BernoulliProcess','Blur','BusinessDayQ','BernsteinBasis','BodePlot',
            'BesselJZero','Boole','ButtonBox','BesselK','BooleanConsecutiveFunction',
            'BetaBinomialDistribution','BooleanGraph','ButtonNotebook','BetaDistribution','BooleanMaxterms',
            'BetweennessCentrality','BooleanRegion',
            'BezierCurveBoxOptions','BooleanTable','Backslash','BezierFunction','BooleanVariables',
            'BinLists','BoundaryMeshRegionQ','BarcodeRecognize','Binomial','BoundaryStyle',
            'BinaryImageQ','BottomHatTransform','BandstopFilter','BinaryRead','BoundaryDiscretizeGraphics',
            'BiorthogonalSplineWavelet','BoxMatrix','BarSpacing','BipartiteGraphQ','BoxObject',
            'BitClear','BracketingBar','BaselinePosition','BitGet','BrayCurtisDistance',
            'BitSet','BroadcastStationData','BeckmannDistribution','BitShiftLeft','Brown',
            'BlackmanHarrisWindow','BSplineCurve','BeginPackage','BlackmanNuttallWindow','BSplineCurve3DBoxOptions',
            'BlankSequence','BSplineSurface3DBoxOptions','BeniniDistribution','Blend','BubbleChart',
            'BlomqvistBetaTest','BuildingData','BernoulliGraphDistribution','Blue','BulletGauge',
            'Bold','Button','BesselJ','Bookmarks','ButtonBar',
            'BooleanCountingFunction','ButtonFunction','Beta','BooleanFunction','ButtonMinHeight',
            'BooleanMinterms','ByteCount','BetaRegularized','BooleanQ','ByteOrdering',
            'Booleans','Back','BezierCurve3DBoxOptions','BooleanStrings','Background',
            'BorelTannerDistribution','Band','BinaryFormat','Bottom','BandpassFilter',
            'BoundaryMesh','BarChart3D','BinCounts','BoundaryMeshRegion','BarcodeImage',
            'BoxData','BarnesG','BinormalDistribution','Boxed','BarOrigin',
            'BoxStyle','BaseForm','BitAnd','BoxWhiskerChart','Baseline',
            'Break','BattleLemarieWavelet','BitOr','BridgeData','Because',
            'BrownianBridgeProcess','Begin','Black','BSplineBasis','BeginDialogPacket',
            'BubbleScale','BernoulliB','BlomqvistBeta','BubbleSizes','BernoulliDistribution',
            'ButterflyGraph','BesselFilterModel','BohmanWindow','ButterworthFilterModel','BesselI',
            'ButtonBoxOptions','BesselY','BooleanConvert','ButtonData','BesselYZero',
            'ButtonSource','BetaNegativeBinomialDistribution','BooleanMinimize','Byte','BetaPrimeDistribution',
            'CalendarConvert','ClipPlanes','ContextToFileName','CalendarData','ClipPlanesStyle',
            'Cancel','Close','ContinuousMarkovProcess','CancelButton','CloseKernels',
            'CantorStaircase','CloudConnect','ContourLabels','Cap','CloudDeploy',
            'CarmichaelLambda','CloudExport','ContourStyle','Cases','CloudFunction',
            'CatalanNumber','CloudObjects','ControllabilityMatrix','Catch','CloudPut',
            'CayleyGraph','CMYKColor','ControllerManipulate','CDF','CodeAssistOptions',
            'Ceiling','CoefficientRules','ControlsRendering','CelestialSystem','CoifletWavelet',
            'CellBracketOptions','ColorConvert','Convolve','CellChangeTimes','ColorCoverage',
            'CellEditDuplicate','ColorFunction','CoordinatesToolOptions','CellEpilog','ColorFunctionScaling',
            'CellFrame','ColorQ','CopulaDistribution','CellFrameMargins','ColorQuantize',
            'CellID','ColorSetter','CornerFilter','CellLabel','ColorSetterBoxOptions',
            'CellOpen','ColumnAlignments','CorrelationTest','CellPrint','ColumnLines',
            'CellTags','CombinerFunction','CosineWindow','CellularAutomaton','CometData',
            'CenterDot','CommonUnits','CountDistinct','CentralMoment','CommunityBoundaryStyle',
            'ChanVeseBinarize','CompanyData','Counts','Character','CompatibleUnitQ',
            'CharacterRange','Compiled','CoxianDistribution','Characters','CompiledFunction',
            'ChartLabels','CompleteKaryTree','CreateArchive','ChartLayout','Complex',
            'Chebyshev2FilterModel','ComplexityFunction','CreateDocument','ChebyshevT','ComponentMeasurements',
            'Checkbox','Composition','CreateScheduledTask','CheckboxBar','CompoundExpression',
            'ChiDistribution','Compress','CriticalitySuccessImportance','ChineseRemainder','Condition',
            'CholeskyDecomposition','ConfidenceLevel','Csc','Chop','ConfidenceRange',
            'Circle','ConicHullRegion','Cumulant','CircleDot','Conjugate',
            'CirculantGraph','ConnectedGraphQ','CurrencyConvert','Circumsphere','ConnectedMeshComponents',
            'ClassifierMeasurements','Constant','Cyan','Classify','ConstantArray',
            'ClearAttributes','ConstellationData','Cyclotomic','ClearSystemCache','ContentPadding',
            'ClippingStyle','Contexts',
            'Clock','ContinuedFractionK','CanberraDistance','ClockGauge','ContinuousAction',
            'Closing','ContinuousWaveletTransform','CanonicalName','CloudAccountData','ContourDetect',
            'CloudDisconnect','Contours','CarlemanLinearize','CloudEvaluate','ContourShading',
            'CloudImport','ControlActive','Catalan','CloudObject','ControllabilityGramian',
            'CloudSymbol','ControllerInformation','CauchyWindow','ClusteringComponents','ControllerLinking',
            'CoefficientArrays','ControllerState','CDFWavelet','CoefficientList','ControlPlacement',
            'Colon','ConversionRules','CellBaseline','ColorCombine','ConvexHullMesh',
            'ColorDataFunction','ConwayGroupCo3','CellDynamicExpression','ColorDistance','CoordinateChartData',
            'ColorNegate','CoprimeQ','CellEventActions','ColorProfileData','Coproduct',
            'ColorRules','CopyFile','CellGrouping','ColorSeparate','CopyToClipboard',
            'ColorSpace','CorrelationDistance','CellObject','Column','CorrelationFunction',
            'ColumnSpacings','CoshIntegral','CellStyle','ColumnWidths','CosineDistance',
            'CommonestFilter','Coth','Center','CommonName','Count',
            'CommunityLabels','CountRoots','ChampernowneNumber','CommunityRegionStyle','CountryData',
            'CompilationTarget','CovarianceEstimatorFunction','CharacteristicPolynomial','Compile','CovarianceFunction',
            'CompleteGraph','CoxModelFit','ChartElements','CompleteGraphQ','CramerVonMisesTest',
            'ComplexExpand','CreateDialog','Chebyshev1FilterModel','ComplexInfinity','CreateDirectory',
            'ComposeSeries','CreateNotebook','CheckAbort','CompositeQ','CreatePalette',
            'CompoundPoissonProcess','CreateWindow','ChessboardDistance','CompoundRenewalProcess','CriticalityFailureImportance',
            'Conditioned','CrossingDetect','ChoiceDialog','Cone','CrossMatrix',
            'ConformImages','Cubics','ChromaticPolynomial','Congruent','Cuboid',
            'Conjunction','CupCap','CircleTimes','ConnectedComponents','Curl',
            'ConnesWindow','CurvatureFlowFilter','ClassifierInformation','ConoverTest','CurveClosed',
            'ConstantRegionQ','Cycles','ClearAll','Constants','CyclicGroup',
            'ContentSize','Clip','Context',
            'Continue','CalendarType','ClipRange','ContinuedFraction','CallPacket',
            'ContinuousTimeModelQ','CandlestickChart','ClosenessCentrality','ContinuousWaveletData','CanonicalGraph',
            'ContourPlot','CapForm','CloudDirectory','ContourPlot3D','CapitalDifferentialD',
            'ContraharmonicMean','Cashflow','CloudGet','Control','Casoratian',
            'ControlType','Cell','Collect','Convergents','CellAutoOverwrite',
            'ControllableDecomposition','Catenate','CloudSave','ControllableModelQ','CauchyDistribution',
            'ControllerMethod','CDFDeploy','Coefficient','ControllerPath','CDFInformation',
            'ConwayGroupCo1','CellContext','ColorData','ConwayGroupCo2','CellDingbat',
            'CoordinateTransform','CellEvaluationDuplicate','Colorize','CoordinateTransformData','CellEvaluationFunction',
            'Copyable','CellGroup','ColorReplace','CopyDirectory','CellGroupData',
            'CornerNeighbors','CellLabelAutoDelete','ColorSlider','Correlation','CellMargins',
            'Cos','CellProlog','ColumnsEqual','Cosh','Cells',
            'CosIntegral','CensoredDistribution','Commonest','Cot','Censoring',
            'CountDistinctBy','CentralMomentGeneratingFunction','CommunityGraphPlot','CounterBoxOptions','CForm',
            'CountsBy','CharacterEncoding','CompilationOptions','Covariance','CharacteristicFunction',
            'CoxIngersollRossProcess','ChartBaseStyle','Complement','CoxModel','ChartElementFunction',
            'CreateCellID','ChartLegends','Complexes','CreateDatabin','ChartStyle',
            'CreateIntermediateDirectories','ChebyshevU','ComposeList','CreateManagedLibraryExpression','Check',
            'CreateTemporary','CheckboxBoxOptions','CompoundPoissonDistribution','CreateUUID','ChemicalData',
            'CriticalSection','ChiSquareDistribution','ConditionalExpression','Cross','ChoiceButtons',
            'Csch','ChromaticityPlot','ConfidenceTransform','CubeRoot','ChromaticityPlot3D',
            'CumulantGeneratingFunction','CircleMinus','ConjugateTranspose','Cup','CirclePlus',
            'CurrentImage','CityData','ConnectLibraryCallbackFunction','CurrentValue','ClassifierFunction',
            'CycleGraph','ClassPriors','ConstantImage','CycleIndexPolynomial','Clear',
            'Cylinder','ClebschGordan','ContentSelectable','CylindricalDecomposition','ClickPane',
            'DGaussianWavelet','DistributionChart','DateValue','Diagonal','DistributionFitTest',
            'DMSList','DayRound','DifferenceDelta','DMSString','DeBruijnGraph',
            'DSolveValue','DeleteCases','DiscreteChirpZTransform','Dt','DeleteContents',
            'Darker','Deployed','DiscreteWaveletData','Dashed','Depth',
            'Databins','DescriptorStateSpace','Discriminant','DataDistribution','DesignMatrix',
            'DateDifference','DeviceExecute','Dispatch','DatedUnit','DeviceExecuteAsynchronous',
            'DateListLogPlot','DeviceReadBuffer','DisplayFunction','DateListPlot','DeviceReadLatest',
            'DatePlus','DeviceStreams','Distributed','DateRange','DeviceWrite',
            'DaubechiesWavelet','DiagonalizableMatrixQ','DistributionParameterAssumptions','DavisDistribution','DiagonalMatrix',
            'DayHemisphere','DialogProlog','DivideBy','DaylightQ','DialogReturn',
            'DayPlus','DiceDissimilarity','DivisorSum','DayRange','DictionaryLookup',
            'Decompose','Differences','DocumentNotebook','Decrement','DifferentialD',
            'DefaultAxesStyle','DigitBlock','Dotted','DefaultBaseStyle','DigitCharacter',
            'DefaultDuration','Dilation','DoubleLeftTee','DefaultElement','DimensionalCombinations',
            'DefaultFrameTicksStyle','DiracDelta','DoubleRightTee','DefaultGridLinesStyle','DirectedEdge',
            'DefaultOptions','DirectedInfinity','DownArrowBar','DefaultTicksStyle','Direction',
            'DefineOutputStreamMethod','DirectoryQ','DownLeftVectorBar','Definition','DirectoryStack',
            'Deinitialization','DirichletConvolve','DownTee','Del','DirichletDistribution',
            'Delete','DirichletTransform','DSolve','DeleteBorderComponents','DirichletWindow',
            'DeleteDuplicates','DiscreteHadamardTransform','DuplicateFreeQ','DeleteDuplicatesBy','DiscreteIndicator',
            'DelimitedSequence','DiscreteMarkovProcess','DynamicModuleBoxOptions','Delimiter','DiscretePlot',
            'DensityHistogram',
            'DependentVariables','DiscreteUniformDistribution','DamerauLevenshteinDistance','Deploy','DiscreteVariables',
            'Derivative','DiscretizeGraphics','DatabinAdd','DerivativeFilter','DiscretizeRegion',
            'DeviceClose','Disk','Dataset','DeviceConfigure','DiskMatrix',
            'DeviceOpen','DisplayEndPacket','DateList','DeviceRead','DisplayForm',
            'DeviceReadTimeSeries','DistanceTransform','DatePattern','Devices','Distribute',
            'DialogInput','Div','DayCountConvention','DialogNotebook','Divide',
            'Diamond','Divisors','DayNightTerminator','DiamondMatrix','DivisorSigma',
            'DifferenceRoot','Do','DeclarePackage','DifferenceRootReduce','DockedCells',
            'DifferentialRootReduce','DotDashed','Default','DifferentiatorFilter','DotEqual',
            'DigitQ','DoubleLeftArrow','DefaultDuplicateCellStyle','DihedralGroup','DoubleLeftRightArrow',
            'Dimensions','DoubleLongRightArrow','DefaultFrameStyle','DiracComb','DoubleRightArrow',
            'DirectedGraph','DoubleVerticalBar','DefaultNewCellStyle','DirectedGraphQ','DownArrow',
            'Directory','DownLeftTeeVector','DefineInputStreamMethod','DirectoryName','DownLeftVector',
            'DirichletCharacter','DownRightVectorBar','DegreeGraphDistribution','DirichletCondition','Downsample',
            'DirichletL','DragAndDrop','Deletable','DirichletLambda','Drop',
            'DiscreteConvolve','DualSystemsModel','DeleteDirectory','DiscreteDelta','DumpSave',
            'DiscreteLQRegulatorGains','DynamicEvaluationTimeout','DeleteSmallComponents','DiscreteLyapunovSolve','DynamicModule',
            'DiscreteRatio','DynamicWrapper','Denominator','DiscreteRiccatiSolve','DynamicWrapperBoxOptions',
            'DiscreteShift','DagumDistribution','DensityPlot','DiscreteTimeModelQ','DamData',
            'DiscreteWaveletPacketTransform','Dashing','DepthFirstScan','DiscreteWaveletTransform','Databin',
            'DisjointQ','DataRange','Det','Disjunction','DataReversed',
            'DispersionEstimatorFunction','DateFormat','DeviceObject','DisplayAllSteps','DateFunction',
            'DisplayPacket','DateObject','DeviceReadList','DistanceFunction','DateObjectQ',
            'DistributedContexts','DateString','DeviceWriteBuffer','DistributeDefinitions','DateTicksFormat',
            'DistributionParameterQ','DawsonF','Dialog','Dithering','DayCount',
            'Dividers','DayMatchQ','DialogSymbols','Divisible','DayName',
            'DominantColors','DedekindEta','DifferentialRoot','Dot','DeepSpaceProbeData',
            'DoubleBracketingBar','DefaultBoxStyle','DigitCount','DoubleDownArrow','DefaultButton',
            'DoubleLongLeftArrow','DefaultFaceGridsStyle','DimensionalMeshComponents','DoubleLongLeftRightArrow','DefaultFieldHintStyle',
            'DoubleUpArrow','DefaultLabelStyle','DirectedEdges','DoubleUpDownArrow','DefaultMenuStyle',
            'DownArrowUpArrow','DefaultTooltipStyle','Directive','DownLeftRightVector','Defer',
            'DownRightTeeVector','Degree','DirichletBeta','DownRightVector','DegreeCentrality',
            'DownTeeArrow','DelaunayMesh','DirichletEta','DownValues','Delayed',
            'Dynamic','DeleteFile','DiscreteLQEstimatorGains','DynamicBoxOptions','DeleteMissing',
            'DynamicModuleValues','DelimiterFlashTime','DiscretePlot3D','DynamicSetting','Delimiters',
            'EdgeAdd','EndOfFile','EventHandler','EdgeBetweennessCentrality','EndOfLine',
            'EdgeCost','EnterExpressionPacket','ExampleData','EdgeCount','EnterTextPacket',
            'EdgeDetect','EntityList','ExcludePods','EdgeForm','EntityProperties',
            'EdgeLabelStyle','EntityValue','ExoplanetData','EdgeList','Entropy',
            'EdgeShapeFunction','Equal','ExpandFileName','EdgeStyle','EqualTilde',
            'EffectiveInterest','Erf','ExpIntegralEi','Eigensystem','Erfc',
            'Element','ErlangDistribution','ExponentialGeneratingFunction','ElementData','Erosion',
            'EllipticE','EstimatedDistribution','ExportForm','EllipticExp','EstimatedProcess',
            'EllipticK','EulerE','ExtendedGCD','EllipticLog','EulerGamma',
            'EllipticThetaPrime','Evaluate','ExternalBundle','EmbedCode','EvaluatePacket',
            'EmptyGraphQ','EvaluationElements','ExtremeValueDistribution','EmptyRegion','EvaluationMonitor',
            'Enabled','EvaluationNotebook','EarthImpactData','Encode',
            'EndDialogPacket','EvenQ','EclipseType','EndOfBuffer','EventData',
            'EndPackage','ExactBlackmanWindow','EdgeContract','EngineeringForm','ExactNumberQ',
            'EntityClass','ExcludedLines','EdgeDelete','EntityClassList','ExcludedPhysicalQuantities',
            'EntityPropertyClass','Exists','EdgeLabels','EntityTypeName','Exit',
            'Environment','ExpandAll','EdgeRules','Epilog','ExpandDenominator',
            'EquirippleFilterKernel','ExpGammaDistribution','EditDistance','Equivalent','ExpIntegralE',
            'ErlangB','ExponentialDistribution','Eigenvectors','ErlangC','ExponentialFamily',
            'EscapeRadius','ExponentStep','Ellipsoid','EstimatedBackground','Export',
            'EstimatorRegulator','ExpressionCell','EllipticFilterModel','EuclideanDistance','ExpToTrig',
            'EulerPhi','ExtentMarkers','EllipticTheta','Evaluatable','ExtentSize',
            'EvaluationCell','Extract','EmpiricalDistribution','EvaluationData','ExtractArchive',
            'EvaluationObject','EarthquakeData','End','Evaluator','EccentricityCentrality',
            'EventLabels','EdgeCapacity','EndOfString','EventSeries','EdgeConnectivity',
            'Except','EdgeCoverQ','Entity','ExcludedForms','EdgeCycleMatrix',
            'Exclusions','EdgeIndex','EntityProperty','ExclusionsStyle','EdgeLabeling',
            'Exp','EdgeQ','EntropyFilter','Expand','EdgeRenderingFunction',
            'ExpandNumerator','EdgeWeight','Equilibrium','Expectation','Editable',
            'Exponent','Eigenvalues','Erfi','ExponentFunction','EigenvectorCentrality',
            'ExponentialMovingAverage','ElidedForms','ErrorBox','ExponentialPowerDistribution','Eliminate',
            'ExportString','EllipticExpPrime','EstimatorGains','Expression','EllipticF',
            'Extension','EllipticNomeQ','EulerianGraphQ','ExtentElementFunction','EllipticPi',
            'ExternalOptions','EmbeddedHTML','EvaluationBox','ExternalTypeSignature','EmitSound',
            'FaceForm','FindGraphCommunities','FormLayoutFunction','FaceGrids',
            'Factor','FindHamiltonianCycle','FormulaData','Factorial','FindHiddenMarkovStates',
            'FactorTerms','FindLibrary','FourierDCT','FactorTermsList','FindLinearRecurrence',
            'FactorialPower','FindIntegerNullVector','Fourier','FactorInteger','FindKClan',
            'False','FindMaxValue','FourierMatrix','FareySequence','FindMinimum',
            'FeedbackSectorStyle','FindPath','FourierSinSeries','FeedbackType','FindPeaks',
            'FieldHintStyle','FindRoot','FractionalGaussianNoiseProcess','FieldMasked','FindSequenceFunction',
            'FileDate','FindSpanningTree','FrameBox','FileExistsQ','FindThreshold',
            'FileNameDepth','FinishDynamic','FrameStyle','FileNameDrop','FiniteAbelianGroupCount',
            'FileNameSplit','FirstCase','FreeQ','FileNameTake','FirstPassageTimeDistribution',
            'FileType','FischerGroupFi24Prime','FresnelG','FilledCurve','FisherHypergeometricDistribution',
            'FillingTransform','FittedModel','FromCharacterCode','FilterRules','FixedPoint',
            'FinancialIndicator','FlattenAt','FromEntity','Find','FlatTopWindow',
            'FindClusters','Fold','FrontEndToken','FindCurvePath','FoldList',
            'FindDivisions','FontSlant','FullGraphics','FindEdgeCover','FontSubstitutions',
            'FindFaces','For','FunctionDomain','FindFile','ForAll',
            'FindGeoLocation','FormBoxOptions','FunctionSpace','FindGeometricTransform','FormFunction',
            'FindGraphIsomorphism','FormObject','FaceGridsStyle','FindGraphPartition','FormTheme',
            'FindIndependentVertexSet','Forward','FactorialMomentGeneratingFunction','FindInstance','ForwardBackward',
            'FindKClub','FourierCosSeries','FactorSquareFreeList','FindKPlex','FourierCosTransform',
            'FindMaximum','FourierDST','FailureDistribution','FindMaximumFlow','FourierDSTMatrix',
            'FindMinimumCut','FourierSeries','FeedbackSector','FindMinValue','FourierSinCoefficient',
            'FindPostmanTour','FourierTrigSeries','FieldHint','FindProcessParameters','FractionalBrownianMotionProcess',
            'FindShortestPath','FractionBoxOptions','FileByteCount','FindShortestTour','Frame',
            'FindVertexCut','FrameLabel','FileHash','FindVertexIndependentPaths','FrameMargins',
            'FiniteGroupData','FRatioDistribution','FileNameSetter','First','FrechetDistribution',
            'FischerGroupFi22','FresnelC','FileTemplateApply','FischerGroupFi23','FresnelF',
            'FisherZDistribution','FrobeniusNumber','FillingStyle','Fit','FrobeniusSolve',
            'Flat','FromDigits','FinancialDerivative','Flatten','FromDMS',
            'Floor','FrontEndEventActions','FindClique','FlowPolynomial','FrontEndExecute',
            'FontFamily','FullDefinition','FindDistributionParameters','FontSize','FullForm',
            'FontVariations','FullSimplify','FindEulerianCycle','FontWeight','Function',
            'FormatType','FunctionPeriod','FindGeneratingFunction','FormBox','FunctionRange',
            'FormulaLookup','Factorial2','FindIndependentEdgeSet','FortranForm','FactorialMoment',
            'FourierCoefficient','FactorList','FindKClique','FourierCosCoefficient','FactorSquareFree',
            'FourierDCTFilter','Failure','FindList','FourierDCTMatrix','FailureAction',
            'FourierParameters','FARIMAProcess','FindMinimumCostFlow','FourierSequenceTransform','FeedbackLinearize',
            'FourierSinTransform','Fibonacci','FindPermutation','FourierTransform','Fibonorial',
            'FractionalPart','FieldSize','FindSettings','FractionBox','FileBaseName',
            'FrameBoxOptions','FileExtension','FindVertexCover','Framed','FileFormat',
            'FrameTicks','FileNameJoin','FiniteGroupCount','FrameTicksStyle','FileNames',
            'FrenetSerretSystem','FilePrint','FirstPosition','FrequencySamplingFilterKernel','FileTemplate',
            'FresnelS','FilledCurveBoxOptions','FisherRatioTest','Friday','Filling',
            'FromCoefficientRules','FinancialBond','FixedPointList','FromContinuedFraction','FinancialData',
            'Front','FindArgMax','FlipView','FrontEndDynamicExpression','FindArgMin',
            'FrontEndTokenExecute','FindCycle','FontColor','Full','FindDevices',
            'FullInformationOutputRegulator','FindEdgeCut','FontTracking','FullRegion','FindEdgeIndependentPaths',
            'FunctionExpand','FindFit','Format','FunctionInterpolation','FindFundamentalCycles',
            'FussellVeselyImportance',
            'GaborFilter','GeoLocation','Graphics3D',
            'GaborMatrix','GeologicalPeriodData','Graphics3DBoxOptions','GaborWavelet','GeoMarker',
            'Gamma','GeometricMeanFilter','GraphicsComplexBoxOptions','GammaDistribution','GeometricTransformation',
            'Gather','GeoNearest','GraphicsRow','GatherBy','GeoPath',
            'GaugeFrameSize','GeoProjection','GraphPlot','GaugeFrameStyle','GeoProjectionData',
            'GaussianFilter','GeoScaleBar','GraphRadius','GaussianIntegers','GeoStyling',
            'GegenbauerC','GeoVisibleRegionBoundary','GrayLevel','General','GeoWithinQ',
            'GenerateDocument','GetEnvironment','GreaterGreater','GeneratedParameters','Glaisher',
            'GenomeLookup','GompertzMakehamDistribution','Grid','GeoBackground','GoodmanKruskalGamma',
            'GeoCircle','Gradient','GridLinesStyle','GeodesicClosing','GradientFilter',
            'GeoDestination','GraphAssortativity','GroupElementFromWord','GeodesyData','GraphAutomorphismGroup',
            'GeoDistance','GraphDensity','GroupGenerators','GeoElevationData','GraphDiameter',
            'GeoGridLinesStyle','GraphDistanceMatrix','GroupSetwiseStabilizer','GeoGridPosition','GraphEmbedding',
            'GeoListPlot','Graphics','GumbelDistribution',
            'GeoPositionENU','GraphLinkEfficiency','GaugeFrameElementFunction','GeoPositionXYZ','GraphPeriphery',
            'GeoRangePadding','GraphPropertyDistribution','GaugeStyle','GeoRegionValuePlot','GraphQ',
            'GeoVariant','GraphUnion','GCD','GeoVisibleRegion','Gray',
            'GeometricDistribution','GraphicsComplex','GalaxyData','GeometricMean','GraphicsComplex3DBoxOptions',
            'GeometricTransformationBoxOptions','GraphicsGroup3DBoxOptions','GARCHProcess','GeoModel','GraphicsGroupBoxOptions',
            'GestureHandler','GreaterEqualLess','GeneratedCell','Get','GreaterFullEqual',
            'Glow','GreaterTilde','GenomeData','GoldenRatio','Green',
            'Goto','GridGraph','GeoCenter','Grad','GridLines',
            'Graph','GroupBy','GeodesicOpening','Graph3D','GroupCentralizer',
            'GraphComplement','GroupElements','GeoDisplacement','GraphData','GroupElementToWord',
            'GraphDisjointUnion','GroupOrder','GeoGridLines','GraphDistance','GroupPageBreakWithin',
            'GraphHighlightStyle','GrowCutComponents','GeoLabels','GraphHub','Gudermannian',
            'GraphIntersection','GaugeFaceElementFunction','GeoPosition','GraphLayout','GaugeFaceStyle',
            'GraphPlot3D','GaugeLabels','GeoRange','GraphPower','GaugeMarkers',
            'GraphReciprocity','GaussianMatrix','GeoStylingImageFunction','GraphStyle','GaussianWindow',
            'GraphicsBoxOptions','GainMargins','GeometricBrownianMotionProcess','GraphicsColumn','GainPhaseMargins',
            'GraphicsGrid','GammaRegularized','GeometricTransformation3DBoxOptions','GraphicsGroup','GapPenalty',
            'Greater','GeneralizedLinearModelFit','GeoZoomLevel','GreaterEqual','GenerateConditions',
            'GreaterLess','GeneratingFunction','GlobalClusteringCoefficient','GreaterSlantEqual','GenericCylindricalDecomposition',
            'GridBox','GeoBoundingBox','GoodmanKruskalGammaTest','GridDefaultElement','GeoBounds',
            'GroebnerBasis','GeodesicDilation','GradientOrientationFilter','GroupActionBase','GeodesicErosion',
            'GroupElementPosition','GeoDirection','GraphCenter','GroupElementQ','GeoDisk',
            'GroupMultiplicationTable','GeoEntities','GraphDifference','GroupOrbits','GeoGraphics',
            'GroupStabilizer','GeoGroup','GraphHighlight','GroupStabilizerChain','GeoIdentify',
            'HaarWavelet',
            'HalfLine','Hexahedron','HotellingTSquareDistribution','HalfNormalDistribution','HiddenMarkovProcess',
            'HammingWindow','HighpassFilter','Hue','HankelH1','HigmanSimsGroupHS',
            'HannWindow','Histogram3D','HyperbolicDistribution','HaradaNortonGroupHN','HistogramDistribution',
            'HarmonicNumber','HistoricalPeriodData','Hypergeometric0F1Regularized','Hash','HitMissTransform',
            'HeaderLines','HoeffdingDTest','HypergeometricDistribution','Heads','Hold',
            'HeldGroupHe','HoldFirst','Hyphenation','Here','HoldForm',
            'HessenbergDecomposition','HorizontalGauge','HadamardMatrix','HexadecimalCharacter','HornerForm',
            'HighlightImage','HTTPRequestData','HammingDistance','HighlightMesh','HTTPResponse',
            'HilbertMatrix','HurwitzLerchPhi','HannPoissonWindow','Histogram','HurwitzZeta',
            'HistogramTransform','Hyperfactorial','HarmonicMeanFilter','HistogramTransformInterpolation','Hypergeometric0F1',
            'HodgeDual','Hypergeometric2F1','Head','HoeffdingD','Hypergeometric2F1Regularized',
            'HoldAllComplete','HypergeometricU','HeavisideTheta','HoldComplete','Hyperlink',
            'HoldRest','HermitianMatrixQ','HolidayCalendar',
            'HoytDistribution','HalfPlane','HighlightGraph','HTTPRedirect','HamiltonianGraphQ',
            'HumpDownHump','HankelH2','HilbertFilter','HumpEqual','HankelMatrix',
            'HypercubeGraph','HararyGraph','HistogramList','HyperexponentialDistribution','HarmonicMean',
            'Hypergeometric1F1','Haversine','HITSCentrality','Hypergeometric1F1Regularized','HazardFunction',
            'HypergeometricPFQ','HeavisideLambda','HoldAll','HypergeometricPFQRegularized','HeavisidePi',
            'HypoexponentialDistribution','HermiteDecomposition','HoldPattern','HypothesisTestData','HermiteH',
            'I','ImageValuePositions','Interleaving','IconData','ImagingDevice',
            'If','ImportString','InterpolationOrder','IgnoreCase','ImprovementImportance',
            'Image3D','IncidenceGraph','Interpreter','Image3DSlices','IncidenceList',
            'ImageAlign','IncludeQuantities','Interval','ImageApply','IncludeWindowTimes',
            'ImageCapture','IndependentEdgeSetQ','Inverse','ImageChannels','IndependentUnit',
            'ImageCompose','Indexed','InverseDistanceTransform','ImageConvolve','IndexGraph',
            'ImageCorrespondingPoints','Infinity','InverseFourierCosTransform','ImageCrop','Infix',
            'ImageDifference','Inherited','InverseFunctions','ImageDimensions','InheritScope',
            'ImageFileApply','Inpaint','InverseHaversine','ImageFileFilter','Input',
            'ImageFormattingWidth','InputField','InverseJacobiDN','ImageForwardTransformation','InputFieldBoxOptions',
            'ImageLines','InputPacket','InverseJacobiSC','ImageMargins','InputStream',
            'ImagePadding','InsertionFunction','InverseRadon','ImagePartition','InsertResults',
            'ImageReflect','Install','InverseWeierstrassP','ImageResize','InstallService',
            'ImageScaled','IntegerExponent','IsolatingInterval','ImageScan','IntegerLength',
            'ImageSubtract','IntegerQ','ItemAspectRatio','ImageTake','Integers',
            'ImageValue','InteractiveTradingChart',
            'Implies','InterpolatingPolynomial','IdentityMatrix','Import','Interpolation',
            'Inactivate','InterpretationBox','Image','Inactive','InterpretationBoxOptions',
            'IncludeConstantBasis','IntersectingQ','ImageAdjust','IncludePods','Intersection',
            'IndefiniteMatrixQ','IntervalSlider','ImageAssemble','IndependenceTest','IntervalUnion',
            'Indeterminate','InverseChiSquareDistribution','ImageColorSpace','IndeterminateThreshold','InverseContinuousWaveletTransform',
            'InfiniteLine','InverseErfc','ImageCorrelate','InfinitePlane','InverseFourier',
            'InflationMethod','InverseFourierTransform','ImageDemosaic','Information','InverseFunction',
            'InitializationCell','InverseGaussianDistribution','ImageFeatureTrack','Inner','InverseGudermannian',
            'InputAssumptions','InverseJacobiCS','ImageForestingComponents','InputAutoReplacements','InverseJacobiDC',
            'InputNamePacket','InverseJacobiND','ImageLevels','InputNotebook','InverseJacobiNS',
            'InputStringPacket','InverseLaplaceTransform','ImagePad','Insert','InversePermutation',
            'Inset3DBoxOptions','InverseTransformedRegion','ImageQ','InsetBoxOptions','InverseWaveletTransform',
            'Integer','IrreduciblePolynomialQ','ImageSaliencyFilter','IntegerDigits','IslandData',
            'IntegerPart','Italic','ImageSizeMultipliers','IntegerPartitions','Item',
            'Integrate','ItemStyle','ImageType','Interactive','ItoProcess',
            'InternallyBalancedDecomposition','IconRules','ImplicitRegion','InterpolatingFunction','Identity',
            'InterpolationPoints','IgnoringInactive','In','Interpretation','Im',
            'InterquartileRange','ImageAccumulate','IncidenceMatrix','Interrupt','ImageAdd',
            'IntervalIntersection','ImageApplyIndexed','Increment','IntervalMemberQ','ImageAspectRatio',
            'InverseBetaRegularized','ImageClip','IndependentVertexSetQ','InverseCDF','ImageCollage',
            'InverseEllipticNomeQ','ImageCooccurrence','InexactNumberQ','InverseErf','ImageCorners',
            'InverseFourierSequenceTransform','ImageData','InflationAdjust','InverseFourierSinTransform','ImageDeconvolve',
            'InverseGammaDistribution','ImageDistance','Initialization','InverseGammaRegularized','ImageEffect',
            'InverseJacobiCD','ImageFileScan','InputAliases','InverseJacobiCN','ImageFilter',
            'InverseJacobiDS','ImageHistogram','InputForm','InverseJacobiNC','ImageKeypoints',
            'InverseJacobiSD','ImageMeasurements','InputString','InverseJacobiSN','ImageMultiply',
            'InverseSeries','ImagePeriodogram','Inset','InverseSurvivalFunction','ImagePerspectiveTransformation',
            'InverseZTransform','ImageResolution','InString','Invisible','ImageRotate',
            'IsomorphicGraphQ','ImageSize','IntegerName','IsotopeData','ImageSizeAction',
            'ItemBoxOptions','ImageTransformation','IntegerString','ItemSize','ImageTrim',
            'JaccardDissimilarity','JacobiSC',
            'JacobiCS','JacobiZeta','JoinForm','JacobiDC','JankoGroupJ1',
            'JacobiND','JarqueBeraALMTest','JuliaSetPlot','JacobiNS','JohnsonDistribution',
            'JacobiSN','JoinedCurve','JacobiCN','JacobiSymbol','JoinedCurveBoxOptions',
            'JankoGroupJ3','JuliaSetBoettcher','JacobiNC','JankoGroupJ4','JuliaSetIterationCount',
            'JoinAcross','JacobiAmplitude','JacobiSD','Joined','JacobiCD',
            'JordanDecomposition','JacobiDN','JankoGroupJ2','JordanModelDecomposition','JacobiDS',
            'JuliaSetPoints','JacobiP','Join', 'KagiChart',
            'KaiserWindow','Kernels','KleinInvariantJ','KalmanEstimator','Key',
            'KatzCentrality','KeyIntersection','KroneckerDelta','KCoreComponents','KeyMap',
            'KelvinBei','KeySort','KumaraswamyDistribution','KelvinBer','KeySortBy',
            'KendallTauTest','KillProcess',
            'KernelMixtureDistribution','KirchhoffGraph','KaiserBesselWindow','KernelObject','KirchhoffMatrix',
            'KeyDropFrom','KnownUnitQ','KaryTree','KeyExistsQ','KolmogorovSmirnovTest',
            'KeyUnion','KVertexConnectedComponents','KendallTau','Khinchin','KVertexConnectedGraphQ',
            'Keys','KroneckerSymbol','KEdgeConnectedGraphQ','KeySelect','KuiperTest',
            'KnightTourGraph','KalmanFilter','KeyDrop','KnotData','KarhunenLoeveDecomposition',
            'KroneckerModelDecomposition','KDistribution','KeypointStrength','KroneckerProduct','KEdgeConnectedComponents',
            'Kurtosis','KelvinKei','KeyTake','KuwaharaFilter','KelvinKer',
            'LABColor','LeveneTest',
            'LCM','LimitsPositioning','LocatorBoxOptions','LeafCount','LindleyDistribution',
            'LQOutputRegulatorGains','LessFullEqual','ListConvolve','LQRegulatorGains','LessGreater',
            'LabelStyle','LibraryFunction','ListLogPlot','LaguerreL','LibraryFunctionError',
            'LanczosWindow','LibraryLoad','ListPlot','LandauDistribution','LibraryUnload',
            'LaplaceTransform','LightBrown','ListStreamPlot','Laplacian','LightCyan',
            'Larger','Lighting','ListZTransform','Last','LightingAngle',
            'LatticeReduce','LightPurple','LocalTimeZone','LaunchKernels','LightRed',
            'Left','LinearGradientImage','Log','LeftArrow','LinearizingTransformationData',
            'LeftDownVector','LinearRecurrence','LogGammaDistribution','LeftDownVectorBar','LinearSolve',
            'LeftTeeArrow','LineGraph','LogitModelFit','LeftTeeVector','LineIndent',
            'LeftUpDownVector','LineLegend','LogMultinormalDistribution','LeftUpTeeVector','LineSpacing',
            'LeftVectorBar','LinkFunction','Longest','LegendAppearance','LinkInterrupt',
            'LegendLayout','LinkProtocol','LongLeftRightArrow','LegendMargins','LinkRankCentrality',
            'LegendreQ','LinkWrite','LowerLeftArrow','Length','LiouvilleLambda',
            'LessEqual','ListContourPlot','LQGRegulator','LessEqualGreater','ListContourPlot3D',
            'LessSlantEqual','ListDeconvolve','LUDecomposition','LessTilde','ListDensityPlot',
            'LevyDistribution','ListLogLinearPlot','LabelingFunction','LibraryDataType','ListLogLogPlot',
            'LibraryFunctionLoad','ListPickerBoxOptions','LaminaData','LibraryFunctionUnload','ListPlay',
            'LiftingWaveletTransform','ListPolarPlot','LaplaceDistribution','LightBlue','ListStreamDensityPlot',
            'LightGray','ListVectorPlot','Large','LightGreen','ListVectorPlot3D',
            'LightOrange','LocalizeVariables','LatticeData','LightPink','LocalTime',
            'Likelihood','Locator','LCHColor','Limit','LocatorAutoCreate',
            'Line3DBoxOptions','LocatorRegion','LeastSquaresFilterKernel','LinearFractionalTransform','Locked',
            'LineBoxOptions','LogisticDistribution','LeftTee','LineBreakChart','LogisticSigmoid',
            'LineIntegralConvolutionPlot','LogLogisticDistribution','LeftTriangleEqual','LineIntegralConvolutionScale','LogLogPlot',
            'LinearOffsetFunction','LogBarnesG','LeftDownTeeVector','LinearProgramming','LogGamma',
            'LinkConnect','LogRankTest','LeftVector','LinkCreate','LogSeriesDistribution',
            'LinkObject','Longitude','LegendLabel','LinkPatterns','LongLeftArrow',
            'LinkReadyQ','LoopFreeGraphQ','LegendreP','Links','LowerCaseQ',
            'ListCorrelate','LucasL','LessLess','ListCurvePathPlot','LuccioSamiComponents',
            'ListFourierSequenceTransform','LyapunovSolve','Level','ListInterpolation','LyonsGroupLy',
            'ListLineIntegralConvolutionPlot','Label','LeviCivitaTensor','ListLinePlot','Labeled',
            'ListPicker','LakeData','LibraryFunctionInformation','ListPickerBox','LambdaComponents',
            'ListPlot3D','LanguageCategory','LiftingFilterData','ListPointPlot3D','LanguageData',
            'ListSurfacePlot3D','LaplacianFilter','Lighter','ListVectorDensityPlot','LaplacianGaussianFilter',
            'Listable','LowpassFilter','Less','ListAnimate','LQEstimatorGains',
            'LocalAdaptiveBinarize','Latitude','LightMagenta','LocalClusteringCoefficient','LatitudeLongitude',
            'LocationEquivalenceTest','LayeredGraphPlot','LightYellow','LocationTest','LayerSizeFunction',
            'LocatorPane','LeapYearQ','Line','LocatorPaneBoxOptions','LeastSquares',
            'Log10','LeftArrowBar','LinearModelFit','Log2','LeftArrowRightArrow',
            'LogLikelihood','LeftTriangle','LineIndentMaxFraction','LogLinearPlot','LeftTriangleBar',
            'LogNormalDistribution','LeftUpVector','LinkClose','LogPlot','LeftUpVectorBar',
            'LogicalExpand','LeftRightArrow','LinearSolveFunction','LogIntegral','LeftRightVector',
            'LongRightArrow','LegendMarkers','LinkRead','Lookup','LegendMarkerSize',
            'LongestCommonSequence','Legended','LinkLaunch','LongestCommonSubsequence','LegendFunction',
            'LowerRightArrow','LengthWhile','List','LowerTriangularize','LerchPhi',
            'LunarEclipse','LetterCharacter','ListFormat','LUVColor','LetterQ',
            'MachineNumberQ','MaxMemoryUsed','MineralData','MachinePrecision',
            'Magnification','MaxRecursion','MinimalPolynomial','Magnify','MaxStableDistribution',
            'ManagedLibraryExpressionID','MaxValue','MinkowskiQuestionMark','ManagedLibraryExpressionQ','MaxwellDistribution',
            'MandelbrotSetMemberQ','MeanDegreeConnectivity','MinusPlus','MandelbrotSetPlot','MeanDeviation',
            'Manipulator','MeanShift','MissingDataRules','MannedSpaceMissionData','MeanShiftFilter',
            'Map','MedicalTestData','MixedRadixQuantity','MapAll','Medium',
            'MapThread','MemoryConstrained','Module','MarcumQ','MemoryConstraint',
            'MarginalDistribution','MenuSortingValue','MomentEvaluate','MarkovProcessProperties','MenuStyle',
            'MatchQ','MeshCellCentroid','MonsterGroupM','MathieuC','MeshCellCount',
            'MathieuCPrime','MeshCellMeasure','MorphologicalBranchPoints','MathieuGroupM11','MeshCellQuality',
            'MathieuGroupM24','MeshFunctions','MorphologicalTransform','MathieuS','MeshPrimitives',
            'MatrixExp','MeshRegionQ','Mouseover','MatrixForm','MeshShading',
            'MatrixPower','MessageDialog','MovingMedian','MatrixQ','MessageList',
            'MaxDetect','MetaInformation','Multinomial','MaxExtraBandwidths','MeteorShowerData',
            'MaxMixtureKernels','MinFilter','Magenta','MaxPlotPoints','MinimalBy',
            'MaxSteps','MinimumTimeIncrement','MakeExpression','MaxStepSize','MinIntervalSize',
            'MaximalBy','Min','MultivariateHypergeometricDistribution','Maximize','MinColorDistance',
            'Mean','MinStableDistribution','MandelbrotSetIterationCount','MeanClusteringCoefficient','Minus',
            'MeanGraphDistance','MissingBehavior','Manipulate','MeanNeighborDegree','MissingDataMethod',
            'MedianDeviation','MittagLefflerE','Manual','MedianFilter','MixedGraphQ',
            'MeixnerDistribution','Modal','MAProcess','MemberQ','ModularLambda',
            'MenuCommandKey','Moment','MardiaSkewnessTest','MenuPacket','MomentConvert',
            'Merge','Monitor','MatchLocalNames','Mesh','MonomialList',
            'MeshCellLabel','MorletWavelet','MathieuCharacteristicExponent','MeshCellMarker','MorphologicalBinarize',
            'MeshCellStyle','MorphologicalGraph','MathieuGroupM23','MeshCoordinates','MorphologicalPerimeter',
            'MeshRefinementFunction','MouseAnnotation','Matrices','MeshRegion','MouseAppearance',
            'Message','MovingAverage','MatrixPlot','MessageAction','MovingMap',
            'MessagePacket','MultiedgeStyle','MaxCellMeasure','Messages','MultigraphQ',
            'MexicanHatWavelet','MultiplicativeOrder','MaxFilter','MeyerWavelet','Multiselection',
            'MinValue','MangoldtLambda','MeanFilter','Missing','ManhattanDistance',
            'MinimalStateSpaceModel','Majority','MaxStepFraction','Minimize','MakeBoxes',
            'MinorPlanetData','MandelbrotSetBoettcher','McLaughlinGroupMcL','Minors','MandelbrotSetDistance',
            'MissingString','MannWhitneyTest','Median','MissingStyle','MantissaExponent',
            'MixtureDistribution','MapAt','MeijerG','Mod','MapIndexed',
            'Modulus','MardiaCombinedTest','MemoryInUse','MoebiusMu','MardiaKurtosisTest',
            'MomentGeneratingFunction','Masking','MenuView','Monday','MatchingDissimilarity',
            'MoonPhase','MathieuCharacteristicA','MeshCellIndex','MoonPosition','MathieuCharacteristicB',
            'MorphologicalComponents','MathieuGroupM12','MeshCells','MorphologicalEulerNumber','MathieuGroupM22',
            'Most','MathieuSPrime','MeshQualityGoal','MountainData','MathMLForm',
            'MousePosition','MatrixFunction','MeshStyle','MovieData','MatrixLog',
            'MoyalDistribution','MatrixRank','MessageName','Multicolumn','Max',
            'MultinomialDistribution','MaxExtraConditions','Method','MultinormalDistribution','MaxFeatures',
            'MultivariatePoissonDistribution','MaxIterations','MinDetect','MultivariateTDistribution',
            'NCache','NormalsFunction','NotSquareSubsetEqual','NDSolve','NormFunction',
            'NHoldFirst','NotElement','NumberFieldDiscriminant','NHoldRest','NotEqualTilde',
            'NIntegrate','NotGreaterFullEqual','NumberFieldRootsOfUnity','NMaximize','NotGreaterGreater',
            'NSum','NevilleThetaC','NotebookPrint','NuclearExplosionData','NevilleThetaD',
            'NameQ','NormalDistribution','NotReverseElement','Names','Normalize',
            'NebulaData','NotDoubleVerticalBar','NotSucceeds','NeedlemanWunschSimilarity','Notebook',
            'NegativeDefiniteMatrixQ','NotebookDelete','NotSupersetEqual','NegativeMultinomialDistribution','NotebookDirectory',
            'Nest','NotebookFileName','NotVerticalBar','NestedGreaterGreater','NotebookFind',
            'NestWhileList','NotebookObject','NSolve','NeumannValue','NotebookOpen',
            'NevilleThetaS','Notebooks','NullRecords','NExpectation','NotebookSave',
            'NominalVariables','NotHumpDownHump','NumberMarks','NoncentralBetaDistribution','NotHumpEqual',
            'NonCommutativeMultiply','NotLess','NumberSeparator','NonConstants','NotLessEqual',
            'NonlinearStateSpaceModel','NotLessSlantEqual','NumericQ','NonlocalMeansFilter','NotLessTilde',
            'NorlundB','NotPrecedesEqual',
            'Norm','NotPrecedesSlantEqual','NakagamiDistribution','Normal','NotPrecedesTilde',
            'NormalizedSquaredEuclideanDistance','NotRightTriangleEqual','NArgMin','NormalMatrixQ','NotSquareSubset',
            'NotCongruent','NotSubset','NearestFunction','NotCupCap','NotSubsetEqual',
            'NotGreater','NumberFieldNormRepresentatives','NightHemisphere','NotGreaterEqual','NumberFieldRegulator',
            'NotGreaterSlantEqual','NumberFormat','NMinValue','NotGreaterTilde','NumberLinePlot',
            'NotLeftTriangleBar','NumberPoint','NoncentralStudentTDistribution','NotLeftTriangleEqual','NumberQ',
            'NotLessGreater','Numerator','NonlinearModelFit','NotLessLess','NumericFunction',
            'NotNestedLessLess','NyquistPlot','Nor','NotPrecedes',
            'NotRightTriangle','Nand','Normalized','NotRightTriangleBar','NArgMax',
            'NotSquareSuperset','NDSolveValue','Not','NotSquareSupersetEqual','Nearest',
            'NotSucceedsEqual','Needs','NotebookApply','NotSucceedsSlantEqual','Negative',
            'NotTilde','NegativeSemidefiniteMatrixQ','NotebookDynamicExpression','NotTildeEqual','NeighborhoodData',
            'NotebookAutoSave','NotSucceedsTilde','NegativeBinomialDistribution','NotebookClose','NotSuperset',
            'NotebookEvaluate','NotTildeFullEqual','NeighborhoodGraph','NotebookEventActions','NotTildeTilde',
            'NotebookInformation','NProduct','NestWhile','NotebookLocate','NRoots',
            'NotebookPut','NuclearReactorData','NevilleThetaN','NotebookRead','Null',
            'NotebookTemplate','Number','NHoldAll','NotebookWrite','NumberFieldClassNumber',
            'Now','NestedLessLess','NotebookGet','NProbability','NestList',
            'NullSpace','NextCell','NotebookSelection','NullWords','NextPrime',
            'NumberFieldFundamentalUnits','NicholsGridLines','NotExists','NumberFieldIntegralBasis','NicholsPlot',
            'NumberFieldSignature','NMaxValue','NotGreaterLess','NumberForm','NMinimize',
            'NumberMultiplier','NoncentralChiSquareDistribution','NotLeftTriangle','NumberPadding','NoncentralFRatioDistribution',
            'NumberSigns','None','NotLessFullEqual','NumberString','NoneTrue',
            'NuttallWindow','NonNegative','NotNestedGreaterGreater','NyquistGridLines','NonPositive',
            'O','ObservabilityGramian','OptimumFlowData','OutputNamePacket','ObservabilityMatrix','Optional',
            'OddQ','OptionValueBoxOptions','OverDot','Off','Or',
            'OneIdentity','OrderedQ','OverlayBoxOptions','Opacity','Ordering',
            'OpenerView','OrthogonalMatrixQ','OverVector','Opening','Out',
            'OperatingSystem','OutputForm',
            'OptionsPattern','OutputStream','OceanData','OptionValue','OverBar',
            'Order','Overlaps','ONanGroupON','OrderDistribution','Overlay',
            'OrnsteinUhlenbeckProcess','OverscriptBoxOptions','OpenerBoxOptions','Orthogonalize','OverTilde',
            'OutputControllabilityMatrix','Operate','OutputControllableModelQ',
            'OutputResponse','ObservableDecomposition','Options','OutputSizeLimit','ObservableModelQ',
            'Overflow','Offset','Orange','OverHat','On',
            'Overscript','OpenAppend','Orderless','OverscriptBox','Opener',
            'OwenT','OpenRead','Outer','OwnValues','OpenWrite',
            'PIDFeedforward','Precedes','Panel','PIDTune','PrecedesEqual',
            'PackingMethod',
            'Padding','PermutationOrder','PopupWindow','PadeApproximant','PermutationPower',
            'PageBreakBelow','PermutationSupport','PositiveSemidefiniteMatrixQ','PageBreakWithin','Permute',
            'PageWidth','PetersenGraph','PowerExpand','PairedBarChart','PhaseMargins',
            'PairedZTest','Pick','PowersRepresentations','PaletteNotebook','PIDData',
            'PanelBoxOptions','Piecewise','PrecedesSlantEqual','Paneled','PiecewiseExpand',
            'ParagraphIndent','PillaiTraceTest','Predict','ParagraphSpacing','Pink',
            'ParallelNeeds','PlanckRadiationLaw','PreviousCell','Parallelogram','PlaneCurveData',
            'ParallelTable','Play','PrimePi','ParallelTry','PlayRange',
            'Parallelepiped','Placed','Prefix','ParallelEvaluate','Placeholder',
            'ParametricNDSolve','PlotLayout','PrimitiveRoot','ParametricNDSolveValue','PlotLegends',
            'ParentBox','PlotRangeClipping','PrintingStyleEnvironment','ParentCell','PlotRangePadding',
            'ParkData','Pluralize','Probability','Part','Plus',
            'ParticleData','PodWidth','ProcessConnection','Partition','Point',
            'PascalDistribution','PointLegend','ProcessInformation','PassEventsDown','PointSize',
            'Path','PoissonWindow','Product','PathGraph','PolarAxes',
            'PatternTest','PolarTicks','Projection','PauliMatrix','PoleZeroMarkers',
            'PeakDetect','Polygon3DBoxOptions','PropertyValue','PearsonChiSquareTest','PolygonBoxOptions',
            'Periodogram','PolynomialGCD','ProteinData','PeriodogramArray','PolynomialLCM',
            'PermutationGroup','PolynomialQuotientRemainder','Put','PermutationLength','PolynomialReduce',
            'PermutationMax','PopupMenuBoxOptions','PaddedForm','PermutationMin','PopupView',
            'PermutationReplace','Positive','PageBreakAbove','Permutations','PositiveDefiniteMatrixQ',
            'PersonData','Power','PageRankCentrality','PERTDistribution','PowerDistribution',
            'PhysicalSystemData','PowerRange','PairedTTest','Pi','PowerSpectralDensity',
            'PieChart3D','PrecisionGoal','ParabolicCylinderD','PillaiTrace','PreDecrement',
            'PixelValue','PredictorMeasurements','ParallelDo','PixelValuePositions','PreemptProtect',
            'Plain','PrependTo','ParallelMap','PlanarGraphQ','PreserveImageOptions',
            'PlanetData','PrimeNu','ParallelSum','PlantData','PrimeOmega',
            'Plot3D','Primes','ParametricFunction','PlotLabel','PrimeZetaP',
            'PlotPoints','PrincipalValue','ParametricRegion','PlotRange','Print',
            'PlotStyle','PrivateCellOptions','ParetoDistribution','PlotTheme','PrivateNotebookOptions',
            'Pochhammer','ProbabilityScalePlot','ParticleAcceleratorData','PodStates','ProbitModelFit',
            'PointBoxOptions','Processes','ParzenWindow','PointFigureChart','ProcessEstimator',
            'PoissonDistribution','ProcessParameterQ','PasteButton','PoissonProcess','ProcessStatus',
            'PolarGridLines','ProgressIndicator','PatternSequence','PolarPlot','ProgressIndicatorBoxOptions',
            'PolyGamma','Property','PDF','Polygon','PropertyList',
            'PolyLog','Protect','PerformanceGoal','PolynomialExtendedGCD','Protected',
            'PolynomialQ','PulsarData','PermutationCyclesQ','PolynomialQuotient','Purple',
            'PopupMenu',
            'Position','PadLeft','PermutationProduct','PositionIndex','PadRight',
            'PossibleZeroQ','PageFooters','PeronaMalikFilter','Postfix','PageHeaders',
            'PowerMod','PairedHistogram','PhaseRange','PowerModList','PairedSmoothHistogram',
            'PowerSymmetricPolynomial','Pane','PIDDerivativeFilter','PrecedenceForm','PaneBoxOptions',
            'PreIncrement','Parallelization','PlaceholderReplace','Prepend','Parallelize',
            'PrecedesTilde','PaneSelector','PieChart','Precision','PaneSelectorBoxOptions',
            'PredictorFunction','ParallelArray','PixelConstrained','PredictorInformation','ParallelCombine',
            'PriceGraphDistribution','ParallelProduct','PlanetaryMoonData','Prime','ParallelSubmit',
            'PrimePowerQ','ParameterEstimator','Plot','PrimeQ','ParameterMixtureDistribution',
            'PrimitiveRootList','ParametricPlot','PlotMarkers','PrincipalComponents','ParametricPlot3D',
            'PrintTemporary','ParentDirectory','PlotRegion','Prism','ParentNotebook',
            'ProbabilityDistribution','PartBehavior','PlusMinus','ProbabilityPlot','PartialCorrelationFunction',
            'ProcessDirectory','PartitionsP','Point3DBoxOptions','ProcessEnvironment','PartitionsQ',
            'ProcessObject','PassEventsUp','PoissonConsulDistribution','ProcessParameterAssumptions','Paste',
            'ProductDistribution','PathGraphQ','PolarAxesOrigin','ProductLog','Pattern',
            'Prolog','PaulWavelet','PolyaAeppliDistribution','Properties','Pause',
            'Proportion','PearsonCorrelationTest','PolyhedronData','Proportional','PearsonDistribution',
            'Pruning','Permissions','PolynomialMod','PseudoInverse','PermutationCycles',
            'PutAppend','PermutationList','PolynomialRemainder','Pyramid','PermutationListQ',
            'QBinomial','QuantityForm','QuartileDeviation',
            'QFactorial','QuantityMagnitude','Quartiles','QGamma','QuantityQ',
            'QRDecomposition','QuantityVariableCanonicalUnit','QueueProperties','QuadraticIrrationalQ','QuantityVariableDimensions',
            'QuantityUnit','QueueingNetworkProcess','QPolyGamma','QuantityVariable','QueueingProcess',
            'QuantityVariablePhysicalQuantity','Quotient','Quantity','Quartics','QuotientRemainder',
            'QuartileSkewness','QHypergeometricPFQ','QuantityThread','Query','QPochhammer',
            'Quiet','Quantile','QuantityVariableIdentifier','Quit','QuantilePlot',
            'RadialGradientImage','RegionBounds','RevolutionPlot3D','RadialityCentrality',
            'RadicalBoxOptions','RegionDimension','RiceDistribution','RadioButton','RegionDistance',
            'RamanujanTau','RegionIntersection','RiemannXi','RamanujanTauL','RegionMeasure',
            'RandomColor','RegionNearestFunction','RightArrowLeftArrow','RandomComplex','RegionPlot',
            'RandomInteger','RegionSymmetricDifference','RightDownVectorBar','RandomPermutation','RegionUnion',
            'RandomVariate','ReleaseHold','RightTriangleBar','RandomWalkProcess','ReliabilityDistribution',
            'RankedMin','RemoveAlphaChannel','RightUpVectorBar','Raster','RemoveAsynchronousTask',
            'Rasterize','RemoveProperty','RogersTanimotoDissimilarity','RasterSize','RemoveScheduledTask',
            'Ratios','RenkoChart','RootMeanSquare','RawBoxes','Repeated',
            'Read','ReplaceImageValue','Rotate','ReadLine','ReplaceList',
            'Real','RequiredPhysicalQuantities','RotationBoxOptions','RealBlockDiagonalForm','Resampling',
            'Reap','ResetDirectory','Row','Record','ResetScheduledTask',
            'RectangleBoxOptions','Rest','RowReduce','RectangleChart','Restricted',
            'Red','ReturnExpressionPacket','RudvalisGroupRu','Reduce','ReturnPacket',
            'ReflectionTransform','ReverseElement','RunScheduledTask','Refresh','ReverseEquilibrium',
            'RegionCentroid','RGBColor','RadicalBox','RegionDifference','RiccatiSolve',
            'RegionEmbeddingDimension','RiemannSiegelTheta','Radon','RegionFunction','RiemannSiegelZ',
            'RegionMemberFunction','RightArrow','RandomChoice','RegionNearest','RightArrowBar',
            'RegionProduct','RightDownTeeVector','RandomImage','RegionQ','RightDownVector',
            'Regularization','RightTeeVector','RandomSample','RegularlySampledQ','RightTriangle',
            'ReliefPlot','RightUpTeeVector','RankedMax','Remove','RightUpVector',
            'RemoveInputStreamMethod','RiskAchievementImportance','RasterBoxOptions','RemoveOutputStreamMethod','RiskReductionImportance',
            'RenameFile','RootIntervals','Rationals','RenewalProcess','RootLocusPlot',
            'Replace','Roots','Re','ReplaceAll','RootSum',
            'ReplacePixelValue','RotateRight','ReadString','ReplaceRepeated','RotationAction',
            'Rescale','Round','Reals','RescalingTransform','RoundingRadius',
            'Resolve','RowLines','Rectangle','ResponseForm','RowMinHeight',
            'ResumePacket','RSolve','RecurrenceTable','Return','RSolveValue',
            'Reverse','Run','ReflectionMatrix','ReverseBiorthogonalSplineWavelet','RunProcess',
            'ReverseUpEquilibrium','RuntimeOptions','RegionBoundary','RevolutionAxis','RussellRaoDissimilarity',
            'RidgeFilter','RadioButtonBar','RegionDistanceFunction','RiemannR','RadioButtonBoxOptions',
            'Riffle','RamanujanTauTheta','RegionMember','Right','RamanujanTauZ',
            'RightComposition','RandomFunction','RegionPlot3D','RightCosetRepresentative','RandomGraph',
            'RightTee','RandomPrime','RegularExpression','RightTeeArrow','RandomReal',
            'RightTriangleEqual','Range','ReliefImage','RightUpDownVector','RangeFilter',
            'RightVector','Raster3D','RemoveBackground','RightVectorBar','Raster3DBoxOptions',
            'Root','Rational','RenameDirectory','RootApproximant','Rationalize',
            'RootOfUnityQ','RawData','RepeatedNull','RootReduce','RayleighDistribution',
            'RotateLabel','ReadList','ReplacePart','RotateLeft','ReadProtected',
            'RotationMatrix','RealDigits','ResamplingMethod','RotationTransform','RealExponent',
            'RowAlignments','RecordLists','Residue','RowBox','RecordSeparators',
            'RowsEqual','RectangleChart3D','Resultant','RowSpacings','RecurrenceFilter',
            'Rule','ReferenceLineStyle','ReturnTextPacket','RuleDelayed','Refine',
            'RunThrough','RefreshRate','ReverseGraph','RuntimeAttributes','RegionBinarize',
            'SARMAProcess','SinhIntegral','StreamDensityPlot','SASTriangle','SinIntegral',
            'SameQ','Sin','StirlingS1','SameTest',
            'SampledSoundFunction','SingleLetterItalics','StopScheduledTask','SampledSoundList','SingularValueDecomposition',
            'SatisfiableQ','SkellamDistribution','StreamScale','Saturday','Skewness',
            'SawtoothWave','Slider','StringDrop','Scale','Slider2D',
            'ScalePadding','Slot','StringInsert','ScaleRanges','SlotSequence',
            'ScalingTransform','SmithDelayCompensator','StringQ','Scan','SmithWatermanSimilarity',
            'SchurDecomposition','SmoothKernelDistribution','StringRotateLeft','ScientificForm','SocialMediaData',
            'ScorerHiPrime','SolidData','StringTemplate','ScreenStyleEnvironment','Solve',
            'Scrollbars','Sound','StructuralImportance','ScrollingOptions','SoundNote',
            'SechDistribution','Spacer','Stub','SectorChart','Spacings',
            'SeedRandom','SpanFromLeft','StyleDefinitions','Select','SparseArray',
            'SelectedNotebook','SpearmanRho','SubresultantPolynomialRemainders','SelectFirst','SpeciesData',
            'SelectionMove','SpellingCorrection','SubscriptBoxOptions','SelfLoopStyle','Sphere',
            'SemialgebraicComponentInstances','SphericalHankelH2','SubStar','SendMail','SphericalHarmonicY',
            'SequenceHold','SpheroidalJoiningFactor','SubtractFrom','Series','SpheroidalPS',
            'ServiceDisconnect','SpheroidalRadialFactor','SuchThat','ServiceExecute','SpheroidalS1',
            'SetAccuracy','Splice','Sunrise','SetAlphaChannel','SplicedDistribution',
            'SetDirectory','SplineWeights','SuperPlus','SetEnvironment','Split',
            'SetProperty','SqrtBox','SupersetEqual','SetSelectedNotebook','SqrtBoxOptions',
            'SetSystemOptions','SquareIntersection','SurvivalFunction','Setter','SquareMatrixQ',
            'Shallow','SquareSuperset','SuzukiGroupSuz','ShannonWavelet','SquareSupersetEqual',
            'ShearingMatrix','StabilityMargins','SymletWavelet','ShearingTransform','StabilityMarginsStyle',
            'Shortest','StackComplete','SymmetricReduction','ShortestPathFunction','StackInhibit',
            'Show','StandardForm','SymmetrizedIndependentComponents','ShowAutoStyles','Standardize',
            'ShowCursorTracker','StarData','SyntaxInformation','ShowGroupOpener','StarGraph',
            'ShowStringCharacters','StartOfString','SystemInformation','ShrinkingDelay','StartProcess',
            'Sign','StateResponse','SystemsModelDelete','Signature','StateSpaceModel',
            'SignPadding','StationaryDistribution','SystemsModelLinearity','SignTest','StationaryWaveletPacketTransform',
            'Simplex','StepMonitor','SystemsModelStateFeedbackConnect','Simplify','StieltjesGamma',
            'Sinc','StirlingS2','SampleDepth','SinghMaddalaDistribution','StopAsynchronousTask',
            'SingularValuePlot','StreamColorFunction','SARIMAProcess','Sinh','StreamColorFunctionScaling',
            'Skeleton','StreamPosition','SatisfiabilityInstances','SkeletonTransform','Streams',
            'Skip','StringCases','SavitzkyGolayMatrix','SliceDistribution','StringCount',
            'SliderBoxOptions','StringFormat','ScaleOrigin','SlideView','StringFreeQ',
            'SmallCircle','StringMatchQ','ScalingMatrix','Smaller','StringPosition',
            'SmoothHistogram','StringReplacePart','ScheduledTasks','SmoothHistogram3D','StringReverse',
            'SolarEclipse','StringSplit','ScorerHi','SolarSystemFeatureData','StringTake',
            'Sort','StripOnInput','ScriptSizeMultipliers','SortBy','StripWrapperBoxes',
            'Sow','StruveH','Sech','SpaceCurveData','StruveL',
            'SpanFromAbove','StyleBox','SectorSpacing','SpanFromBoth','StyleData',
            'Speak','SubMinus','SelectedCells','SpearmanRankTest','SubPlus',
            'SpectrogramArray','Subscript','SelectionEvaluateCreateCell','Specularity','SubscriptBox',
            'SphericalBesselY','SubsetQ','SemanticInterpretation','SphericalHankelH1','Subsets',
            'SphericalRegion','SubsuperscriptBoxOptions','SequenceAlignment','SpheroidalEigenvalue','Subtract',
            'SpheroidalQS','SucceedsSlantEqual','ServiceConnect','SpheroidalQSPrime','SucceedsTilde',
            'SpheroidalS2','Sunday','Set','SpheroidalS2Prime','SunPosition',
            'SplineDegree','SuperMinus','SetDelayed','SplineKnots','SupernovaData',
            'SpokenString','SuperscriptBoxOptions','SetPrecision','Sqrt','Superset',
            'SquareSubset','SuspendPacket','Setting','SquareSubsetEqual','SuzukiDistribution',
            'SquareWave','Symbol','Sharpen','SSSTriangle','SymbolName',
            'SquaredEuclideanDistance','SurfaceData','SetStreamPosition','SquareFreeQ','SurvivalDistribution',
            'Stack','SymmetricMatrixQ','ShortDownArrow','StackBegin','SymmetricPolynomial',
            'StandardDeviation','SymmetrizedArrayRules','ShortUpArrow','StandardDeviationFilter','SymmetrizedDependentComponents',
            'Star','SynchronousUpdating','ShowCellTags','StarClusterData','SyntaxForm',
            'StartingStepSize','SyntaxQ','ShowSpecialCharacters','StartOfLine','SystemDialogInput',
            'StateFeedbackGains','SystemsModelDelay','SiegelTukeyTest','StateOutputEstimator','SystemsModelDelayApproximate',
            'StateSpaceTransform','SystemsModelFeedbackConnect','SignificanceLevel','StateTransformationLinearize','SystemsModelLabels',
            'StatusArea','SystemsModelParallelConnect','SimpleGraphQ','StatusCentrality','SystemsModelSeriesConnect',
            'StrataVariables','SampleRate','SingularValueList','StratonovichProcess','SamplingPeriod',
            'StreamPlot','SatelliteData','SixJSymbol','StreamPoints','SatisfiabilityCount',
            'StreamStyle','Save','SkewNormalDistribution','String','SaveDefinitions',
            'StringExpression','Scaled','Slider2DBoxOptions','StringForm','ScaleDivisions',
            'StringJoin','ScaleRangeStyle','Small','StringLength','ScalingFunctions',
            'StringReplace','ScheduledTask','SmoothDensityHistogram','StringReplaceList','ScheduledTaskObject',
            'StringRotateRight','ScorerGi','SokalSneathDissimilarity','StringSkeleton','ScorerGiPrime',
            'StringToStream','ScriptBaselineShifts','SolveAlways','StringTrim','ScriptMinSize',
            'StructuredArray','ScrollPosition','SoundVolume','StructuredSelection','Sec',
            'StudentTDistribution','SectorChart3D','Span','Style','SectorOrigin',
            'Subfactorial','Selectable','SpatialGraphDistribution','Subgraph','SelectComponents',
            'SubresultantPolynomials','SelectionCreateCell','Spectrogram','Subresultants','SelectionEvaluate',
            'Subset','SemanticImport','SphericalBesselJ','SubsetEqual','SemanticImportString',
            'Subsuperscript','SendMessage','SphericalPlot3D','SubsuperscriptBox','Sequence',
            'Succeeds','SeriesCoefficient','SpheroidalPSPrime','SucceedsEqual','SeriesData',
            'Sum','ServiceObject','SpheroidalS1Prime','SumConvergence','SessionTime',
            'Sunset','SetAttributes','SplineClosed','SuperDagger','SetCloudDirectory',
            'SuperStar','SetSharedFunction','Square','Surd','SetSharedVariable',
            'Superscript','SetFileDate','SplitBy','SuperscriptBox','SetOptions',
            'SurvivalModel','SetterBar','SquaresR','SurvivalModelFit','SetterBoxOptions',
            'SwatchLegend','ShapiroWilkTest','SquareUnion','Switch','Share',
            'Symmetric','ShenCastanMatrix','StableDistribution','SymmetricGroup','Short',
            'Symmetrize','ShortLeftArrow','StandardAtmosphereData','SymmetrizedArray','ShortRightArrow',
            'SymmetrizedReplacePart','ShowCellBracket','StandbyDistribution','SynchronousInitialization','ShowCellLabel',
            'SyntaxLength','ShowPageBreaks','StartAsynchronousTask','SyntaxPacket','ShowSelection',
            'SystemOpen','SiderealTime','StartScheduledTask','SystemOptions','SiegelTheta',
            'SystemsModelDimensions','SignedRankTest','StateSpaceRealization','SystemsModelExtract','SignedRegionDistance',
            'SystemsModelMerge','SimilarityRules','StationaryWaveletTransform','SystemsModelOrder','SimpleGraph',
            'SystemsModelVectorRelativeOrders',
            'Table','Threshold','TraceAbove',
            'TableAlignments','Through','TraceBackward','TableDepth','Throw',
            'TableSpacing','TicksStyle','TraceOn','TabView','Tilde',
            'TaggingRules','TimeConstrained','TrackingFunction','TagSet','TimeConstraint',
            'TakeWhile','Times','TransferFunctionFactor','Tally','TimesBy',
            'TargetFunctions','TimeSeriesInsert','TransformationClass','TargetUnits','TimeSeriesInvertibility',
            'TeXForm','ToInvertibleTimeSeries','Trigger','Text','TokenWords',
            'TemplateBox','TimeSeriesModelFit','TransformedField','TemplateBoxOptions','TimeSeriesResample',
            'TemplateSequence','TimeSeriesWindow','TransitionEffect','TemplateSlot','TimeUsed',
            'Temporary','Timing','Transparent','TensorContract','Tiny',
            'TensorRank','ToContinuousTimeModel','TreePlot','TensorReduce','Today',
            'TestID','ToExpression','TriangulateMesh','TestReport','Together',
            'TextClipboardType','ToNumberField','True','TextData','Tooltip',
            'TextString','Top','TTest','Texture','TopHatTransform',
            'ThermodynamicData','ToString','Tuesday','ThermometerGauge','Total',
            'Thinning','TouchscreenAutoZoom','TuranGraph','ThompsonGroupTh','TouchscreenControlPlacement',
            'Thursday','TraceForward','TableHeadings','Ticks','TraceOff',
            'TildeFullEqual','TraceScan','TagBoxOptions','TildeTilde','TrackedSymbols',
            'TimeFormat','TransferFunctionCancel','Take','TimeObject','TransferFunctionExpand',
            'TimeSeriesAggregate','TransferFunctionTransform','Target','TimeSeriesForecast','TransferFunctionZeros',
            'TimeSeriesMapThread','TransformationMatrix','TemplateApply','TimeSeriesModel','TransformedDistribution',
            'TimeSeriesShift','TransitionDirection','TemplateObject','TimeSeriesThread','TransitionDuration',
            'TimeZone','Translate','TemporalRegularity','TimeZoneConvert','TranslationTransform',
            'ToBoxes','TreeGraph','TensorProduct','ToCharacterCode','TreeGraphQ',
            'ToEntity','TriangleWave','TensorWedge','ToeplitzMatrix','TriangularDistribution',
            'ToLowerCase','TrimmedMean','TextCell','Tomorrow','TropicalStormData',
            'ToRadicals','TubeBoxOptions','Therefore','ToRules','TubeBSplineCurveBoxOptions',
            'TogglerBar','TrigFactor','Tetrahedron','TogglerBoxOptions','TrigFactorList',
            'TooltipDelay','TsallisQExponentialDistribution','TextRecognize','TooltipStyle','TsallisQGaussianDistribution',
            'TotalWidth','TunnelData','Thin','TouchPosition','Tuples',
            'Tr','ThreeJSymbol','Trace',
            'TraceDepth','TableDirections','Thumbnail','TraceDialog','TableForm',
            'TraceOriginal','TabViewBoxOptions','TildeEqual','TracePrint','TagBox',
            'TradingChart','TagSetDelayed','TimeDirection','TraditionalForm','TagUnset',
            'TransferFunctionModel','Tan','TimeSeries','TransferFunctionPoles','Tanh',
            'TransformationFunction','TautologyQ','TimeSeriesMap','TransformationFunctions','TelegraphProcess',
            'TransformedProcess','TemplateExpression','TimeSeriesRescale','TransformedRegion','TemplateIf',
            'TransitiveClosureGraph','TemplateWith','TimeValue','TransitiveReductionGraph','TemporalData',
            'Transpose','TensorDimensions','TitsGroupT','TreeForm','TensorExpand',
            'TrendStyle','TensorSymmetry','ToDiscreteTimeModel','Triangle','TensorTranspose',
            'Trig','TestReportObject','Toggler','TrigExpand','TestResultObject',
            'TrigReduce','Text3DBoxOptions','Tolerance','TrigToExp','TextAlignment',
            'TrueQ','TextJustification','TooltipBoxOptions','TruncatedDistribution','TextPacket',
            'Tube','TextureCoordinateFunction','TopologicalSort','TubeBezierCurveBoxOptions','TextureCoordinateScaling',
            'TukeyLambdaDistribution','Thick','TotalVariationFilter','TukeyWindow','Thickness',
            'TuringMachine','Thread','ToUpperCase','TuttePolynomial','ThreadDepth',
            'URLExecute','UndirectedGraph','Unprotect','URLExpand','UndirectedGraphQ',
            'URLQueryDecode','Unevaluated','UpArrow','URLQueryEncode','UniformDistribution',
            'UnateQ',
            'Undefined','UnitBox','UpperRightArrow','UnderBar','UnitConvert',
            'UnderoverscriptBox','UnitSimplify','UpTee','UnderoverscriptBoxOptions','UnitStep',
            'UnderseaFeatureData','UnityDimensions','URLEncode','UndirectedEdge','UniversityData',
            'UndoTrackedVariables','Unset','URLParse','Unequal','UnsetShared',
            'UniformSumDistribution','Update','URLShorten','Uninstall','UpdateInterval',
            'Unique','UpperCaseQ','Uncompress','UnitaryMatrixQ','UpperLeftArrow',
            'UnitTriangle','URLBuild','UnderscriptBoxOptions','UnitVector','URLDecode',
            'Unitize','UpSet','Underoverscript','UnitRootTest','UpSetDelayed',
            'UnsameQ','URLFetch','UndoOptions','UnsavedVariables','URLFetchAsynchronous',
            'UpArrowBar','URLSave','UniformGraphDistribution','UpArrowDownArrow','URLSaveAsynchronous',
            'UpEquilibrium',
            'UpTeeArrow','Underscript','UnitSystem','UpValues','UnderscriptBox',
            'UpperTriangularize','Underflow','UnitDimensions','Upsample','Underlined',
            'UsingFrontEnd','Union','UpDownArrow','UtilityFunction','UnionPlus',
            'ValidationLength','VerifyTestAssumptions','VertexOutDegree',
            'ValidationSet','VertexAdd','VertexQ','ValueBoxOptions','VertexCapacity',
            'Variables','VertexContract','VertexSize','Variance','VertexCoordinateRules',
            'VarianceTest','VertexCount','VerticalGauge','VectorAngle','VertexCoverQ',
            'VectorPlot','VertexDiceSimilarity','ViewCenter','VectorPlot3D','VertexEccentricity',
            'VectorScale','VertexJaccardSimilarity','ViewVertical','VectorStyle','VertexLabeling',
            'VerifyConvergence','VertexNormals','VonMisesDistribution','VerifySolutions','VertexOutComponent',
            'VertexComponent','VertexShape','Values','VertexConnectivity','VertexShapeFunction',
            'VertexCorrelationSimilarity','VertexWeight','VarianceGammaDistribution','VertexCosineSimilarity','VerticalBar',
            'VertexDegree','VerticalTilde','VectorDensityPlot','VertexDelete','ViewAngle',
            'VertexInDegree','ViewRange','Vectors','VertexIndex','ViewVector',
            'VertexLabelStyle','VolcanoData','VerificationTest','VertexList','Volume',
            'VertexRenderingFunction','ValueDimensions','VertexColors','VertexReplace','ValueQ',
            'VertexStyle','VarianceEquivalenceTest','VertexCoordinates','VertexTextureCoordinates','VarianceEstimatorFunction',
            'VerticalSeparator','VectorColorFunction','VertexDataCoordinates','VerticalSlider','VectorColorFunctionScaling',
            'ViewMatrix','VectorPoints','VertexInComponent','ViewPoint','VectorQ',
            'Visible','Vee','VertexLabels','VoigtDistribution','Verbatim',
            'VoronoiMesh',
            'WaitAll','WeierstrassInvariants','WindowClickSelect',
            'WaitAsynchronousTask','WeierstrassP','WindowElements','WaitNext','WeierstrassPPrime',
            'WatershedComponents','WeightedAdjacencyMatrix','WindowOpacity','WatsonUSquareTest','WeightedData',
            'WaveletImagePlot','WheelGraph','WindSpeedData','WaveletListPlot','WhenEvent',
            'WaveletPsi','WhiteNoiseProcess','WordBoundary','WaveletScale','WhitePoint',
            'WeaklyConnectedGraphQ','WhittakerW','WorkingPrecision','WeakStationarity','WienerFilter',
            'Wednesday','WilksW','Wronskian','WeibullDistribution','WilksWTest',
            'WeierstrassHalfPeriods','WindDirectionData',
            'WeierstrassZeta','WindowMargins','WaringYuleDistribution','WeightedAdjacencyGraph','WindowMovable',
            'Weights','WindowTitle','WaveletFilterCoefficients','WelchWindow','WindowToolbars',
            'While','WolframAlpha','WaveletPhi','White','Word',
            'WhitespaceCharacter','WordSearch','WeaklyConnectedComponents','WhittakerM','WordSeparators',
            'WignerD','WriteLine','Wedge','WignerSemicircleDistribution','WriteString',
            'WindVectorData','WaveletMapIndexed','Which','With','WaveletMatrixPlot',
            'WindowFloating','WakebyDistribution','WeierstrassSigma','WindowFrame','WalleniusHypergeometricDistribution',
            'WindowSize','WattsStrogatzGraphDistribution','WeightedGraphQ','WindowStatusArea','WaveletBestBasis',
            'WordCharacter','WaveletScalogram','Whitespace','WordData','WaveletThreshold',
            'WrapAround','WeatherData','WienerProcess','Write','WeberE',
            'XMLElement','XMLTemplate',
            'Xor','XMLObject','Xnor','XYZColor',
            'Yellow','Yesterday','YuleDissimilarity',
            'ZernikeR', 'Zeta','ZipfDistribution','ZeroSymmetric','ZetaZero','ZTest',
            'ZeroTest','ZIPCodeData','ZTransform','$Aborted',
            )
        ),
    'CASE_SENSITIVE' => array(
        1 => true
        ),
    'SYMBOLS' => array(
        1 => array(
            '@', '//', '/@', '@@', '@@@', '#', '&', //functions
            '=', ':=', '+=', '-=', '*=', '/=', //assignments
            '^', '+' ,'-', '/', '*', '>', '<', '%', //math
            '||', '&&', //logic
            '/.', '/;', '->', ':>' //rules
            ),
        2 => array( // Wolfram
            '$Assumptions','$ImportFormats','$ParentProcessID','$AsynchronousTask','$InitialDirectory',
            '$ByteOrdering','$Inspector','$PlotTheme','$Canceled','$InstallationDirectory',
            '$CloudConnected','$KernelID','$ProcessID','$CloudCreditsAvailable','$Language',
            '$CommandLine','$LicenseServer','$RequesterAddress','$CompilationTarget','$Line',
            '$ControlActiveSetting','$MachineEpsilon','$ScriptCommandLine','$CreationDate','$MachineID',
            '$Display','$MaxExtraPrecision','$SoundDisplayFunction','$DisplayFunction','$MaxMachineNumber',
            '$EmbedCodeEnvironments','$MaxRootDegree','$SystemShell','$Epilog','$MessageGroups',
            '$Failed','$MinMachineNumber','$TimeUnit','$FrontEnd','$MinNumber',
            '$GeoLocationCountry','$NewSymbol','$UserBaseDirectory','$GeoLocationSource','$Notebooks',
            '$IgnoreEOF','$OutputSizeLimit','$WolframID','$ImageFormattingWidth','$OutputStreamMethods',
            '$ImagingDevice','$Packages','$AssertFunction','$ImagingDevices','$ParentLink',
            '$InputFileName','$PerformanceGoal','$BatchOutput','$InputStreamMethods','$Permissions',
            '$IterationLimit','$PrePrint','$CloudBase','$KernelCount','$PreRead',
            '$LicenseExpirationDate','$RecursionLimit','$CloudSymbolBase','$LicenseID','$ReleaseNumber',
            '$MachineAddresses','$RootDirectory','$ContextPath','$MachineDomains','$ScheduledTask',
            '$MachinePrecision','$SharedFunctions','$DefaultImagingDevice','$MachineType','$SharedVariables',
            '$MaxPiecewiseCases','$SystemCharacterEncoding','$Echo','$MaxPrecision','$SystemID',
            '$MessagePrePrint','$TemporaryDirectory','$ExportFormats','$Messages','$TimedOut',
            '$ModuleNumber','$Urgent','$GeoLocationCity','$NewMessage','$UserAgentString',
            '$OperatingSystem','$Version','$HTTPCookies','$Output','$VersionNumber',
            '$Path','$BaseDirectory','$Input','$PathnameSeparator','$BatchInput',
            '$Post','$CharacterEncoding','$InterpreterTypes','$Pre','$CharacterEncodings',
            '$ProcessorCount','$CloudEvaluation','$LibraryPath','$ProcessorType','$CloudRootDirectory',
            '$RequesterWolframID','$ConfiguredKernels','$Linked','$RequesterWolframUUID','$Context',
            '$Services','$CurrentLink','$MachineName','$SessionID','$DateStringFormat',
            '$SyntaxHandler','$DistributedContexts','$MaxNumber','$System','$DynamicEvaluation',
            '$SystemWordLength','$EvaluationCloudObject','$MessageList','$TemplatePath','$EvaluationEnvironment',
            '$TimeZone','$FrontEndSession','$MinPrecision','$UnitSystem','$GeoLocation',
            '$UserDocumentsDirectory','$HistoryLength','$NumberMarks','$UserName','$HomeDirectory',
            '$WolframUUID',
            ),
        3 => array( // array stuff
            '{', '}', '[[', ']]'
            ),
        ),
    'STYLES' => array(
        'KEYWORDS' => array(
            1 => 'color: #FF7700; font-weight: bold;',
            ),
        'COMMENTS' => array(
            'MULTI' => 'color: #999999; font-style: italic;',
            ),
        'ESCAPE_CHAR' => array(
            1 => '',
            ),
        'BRACKETS' => array(),
        'STRINGS' => array(
            1 => 'color: #666666; font-style: italic;',
            ),
        'NUMBERS' => array(
            ),
        'METHODS' => array(),
        'SYMBOLS' => array(
            1 => 'color: #133CAC; font-weight: bold;',
            2 => 'color: #028E9B; font-weight: bold;',
            3 => 'color: #FFAD00; font-weight: bold;',
            ),
        //'BRACKETS' => array(
            //0 => 'color: #8C0953; font-weight: bold;', // array
            //),
        'REGEXPS' => array(
            0 => 'color: #133CAC; font-weight: bold;',
            ),
        'SCRIPT' => array()
        ),
    'URLS' => array(
        1 => 'http://reference.wolfram.com/language/ref/{FNAME}.html'
        ),
    'OOLANG' => false,
    'OBJECT_SPLITTERS' => array(),
    'REGEXPS' => array(
        0 => '#[1-9][0-9]*'
        ),
    'STRICT_MODE_APPLIES' => GESHI_MAYBE,
    'SCRIPT_DELIMITERS' => array(),
    'HIGHLIGHT_STRICT_BLOCK' => array(),
    'TAB_WIDTH' => 4
);
