<?php
/*************************************************************************************
 * mql5.php
 * -----
 * Author: tormec (dcstoyanov@gmail.com)
 * Copyright: (c) 2023 tormec (https://github.com/tormec)
 * Release Version: 1.0.9.1
 * Date Started: 2023/05/05
 *
 * mql5 language file for GeSHi.
 *
 * CHANGES
 * -------
 * 2023/05/05 (1.0.9.1)
 *  -  First Release
 *
 *************************************************************************************
 *
 *     This file is part of GeSHi.
 *
 *   GeSHi is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   GeSHi is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with GeSHi; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ************************************************************************************/

 $language_data = array (
    'LANG_NAME' => 'mql5',
    'COMMENT_SINGLE' => array(1 => '//'),
    'COMMENT_MULTI' => array('/*' => '*/'),
    'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
    'QUOTEMARKS' => array('"'),
    'ESCAPE_CHAR' => '',
    'NUMBERS' =>
        GESHI_NUMBER_INT_BASIC | GESHI_NUMBER_INT_CSTYLE | GESHI_NUMBER_BIN_PREFIX_0B |
        GESHI_NUMBER_OCT_PREFIX | GESHI_NUMBER_HEX_PREFIX | GESHI_NUMBER_FLT_NONSCI |
        GESHI_NUMBER_FLT_NONSCI_F | GESHI_NUMBER_FLT_SCI_SHORT | GESHI_NUMBER_FLT_SCI_ZERO,
    'KEYWORDS' => array(
        1 => array(
            'AccountInfoDouble', 'AccountInfoInteger', 'AccountInfoString', 'Alert', 'ArrayBsearch', 'ArrayCompare',
            'ArrayCopy', 'ArrayFill', 'ArrayFree', 'ArrayGetAsSeries', 'ArrayInitialize', 'ArrayInsert', 'ArrayIsDynamic',
            'ArrayIsSeries', 'ArrayMaximum', 'ArrayMinimum', 'ArrayPrint', 'ArrayRange', 'ArrayRemove', 'ArrayResize',
            'ArrayReverse', 'ArraySetAsSeries', 'ArraySize', 'ArraySort', 'ArraySwap', 'Bars', 'BarsCalculated',
            'CLBufferCreate', 'CLBufferFree', 'CLBufferRead', 'CLBufferWrite', 'CLContextCreate', 'CLContextFree',
            'CLExecute', 'CLGetDeviceInfo', 'CLGetInfoInteger', 'CLHandleType', 'CLKernelCreate', 'CLKernelFree',
            'CLProgramCreate', 'CLProgramFree', 'CLSetKernelArg', 'CLSetKernelArgMem', 'CalendarCountries', 'CalendarCountryById',
            'CalendarEventByCountry', 'CalendarEventByCurrency', 'CalendarEventById', 'CalendarValueById', 'CalendarValueHistory',
            'CalendarValueHistoryByEvent', 'CalendarValueLast', 'CalendarValueLastByEvent', 'CharArrayToString',
            'CharToString', 'ChartApplyTemplate', 'ChartClose', 'ChartFirst', 'ChartGetDouble', 'ChartGetInteger',
            'ChartGetString', 'ChartID', 'ChartIndicatorAdd', 'ChartIndicatorDelete', 'ChartIndicatorGet', 'ChartIndicatorName',
            'ChartIndicatorsTotal', 'ChartNavigate', 'ChartNext', 'ChartOpen', 'ChartPeriod', 'ChartPriceOnDropped',
            'ChartRedraw', 'ChartSaveTemplate', 'ChartScreenShot', 'ChartSetDouble', 'ChartSetInteger', 'ChartSetString',
            'ChartSetSymbolPeriod', 'ChartSymbol', 'ChartTimeOnDropped', 'ChartTimePriceToXY', 'ChartWindowFind',
            'ChartWindowOnDropped', 'ChartXOnDropped', 'ChartXYToTimePrice', 'ChartYOnDropped', 'CheckPointer',
            'ColorToARGB', 'ColorToString', 'Comment', 'CopyBuffer', 'CopyClose', 'CopyHigh', 'CopyLow', 'CopyOpen',
            'CopyRates', 'CopyRealVolume', 'CopySpread', 'CopyTickVolume', 'CopyTicks', 'CopyTime', 'CryptDecode',
            'CryptEncode', 'CustomBookAdd', 'CustomRatesDelete', 'CustomRatesReplace', 'CustomRatesUpdate', 'CustomSymbolCreate',
            'CustomSymbolDelete', 'CustomSymbolSetDouble', 'CustomSymbolSetInteger', 'CustomSymbolSetMarginRate',
            'CustomSymbolSetSessionQuote', 'CustomSymbolSetSessionTrade', 'CustomSymbolSetString', 'CustomTicksAdd',
            'CustomTicksDelete', 'CustomTicksReplace', 'DXBufferCreate', 'DXBufferSet', 'DXContextClearColors',
            'DXContextClearDepth', 'DXContextCreate', 'DXContextGetColors', 'DXContextGetDepth', 'DXContextSetSize',
            'DXContextSetSize', 'DXDraw', 'DXDrawIndexed', 'DXHandleType', 'DXInputCreate', 'DXInputSet', 'DXPrimiveTopologySet',
            'DXRelease', 'DXShaderCreate', 'DXShaderInputsSet', 'DXShaderSet', 'DXShaderSetLayout', 'DXShaderTexturesSet',
            'DXTextureCreate', 'DatabaseBind', 'DatabaseBindArray', 'DatabaseClose', 'DatabaseColumnBlob', 'DatabaseColumnDouble',
            'DatabaseColumnInteger', 'DatabaseColumnLong', 'DatabaseColumnName', 'DatabaseColumnSize', 'DatabaseColumnText',
            'DatabaseColumnType', 'DatabaseColumnsCount', 'DatabaseExecute', 'DatabaseExport', 'DatabaseFinalize',
            'DatabaseImport', 'DatabaseOpen', 'DatabasePrepare', 'DatabasePrint', 'DatabaseRead', 'DatabaseReadBind',
            'DatabaseReset', 'DatabaseTableExists', 'DatabaseTransactionBegin', 'DatabaseTransactionCommit', 'DatabaseTransactionRollback',
            'DebugBreak', 'Digits', 'DoubleToString', 'EnumToString', 'EventChartCustom', 'EventKillTimer', 'EventSetMillisecondTimer',
            'EventSetTimer', 'ExpertRemove', 'FileClose', 'FileCopy', 'FileDelete', 'FileFindClose', 'FileFindFirst',
            'FileFindNext', 'FileFlush', 'FileGetInteger', 'FileIsEnding', 'FileIsExist', 'FileIsLineEnding', 'FileMove',
            'FileOpen', 'FileReadArray', 'FileReadBool', 'FileReadDatetime', 'FileReadDouble', 'FileReadFloat',
            'FileReadInteger', 'FileReadLong', 'FileReadNumber', 'FileReadString', 'FileReadStruct', 'FileSeek',
            'FileSize', 'FileTell', 'FileWrite', 'FileWriteArray', 'FileWriteDouble', 'FileWriteFloat', 'FileWriteInteger',
            'FileWriteLong', 'FileWriteString', 'FileWriteStruct', 'FolderClean', 'FolderCreate', 'FolderDelete',
            'FrameAdd', 'FrameFilter', 'FrameFirst', 'FrameInputs', 'FrameNext', 'GetLastError', 'GetPointer', 'GetTickCount',
            'GlobalVariableCheck', 'GlobalVariableDel', 'GlobalVariableGet', 'GlobalVariableName', 'GlobalVariableSet',
            'GlobalVariableSetOnCondition', 'GlobalVariableTemp', 'GlobalVariableTime', 'GlobalVariablesDeleteAll',
            'GlobalVariablesFlush', 'GlobalVariablesTotal', 'HistoryDealGetDouble', 'HistoryDealGetInteger', 'HistoryDealGetString',
            'HistoryDealGetTicket', 'HistoryDealSelect', 'HistoryDealsTotal', 'HistoryOrderGetDouble', 'HistoryOrderGetInteger',
            'HistoryOrderGetString', 'HistoryOrderGetTicket', 'HistoryOrderSelect', 'HistoryOrdersTotal', 'HistorySelect',
            'HistorySelectByPosition', 'IndicatorCreate', 'IndicatorParameters', 'IndicatorRelease', 'IndicatorSetDouble',
            'IndicatorSetInteger', 'IndicatorSetString', 'IntegerToString', 'IsStopped', 'MQLInfoInteger', 'MQLInfoString',
            'MT5CopyRatesFrom', 'MT5CopyRatesFromPos', 'MT5CopyRatesRange', 'MT5CopyTicksFrom', 'MT5CopyTicksRange',
            'MT5Initialize', 'MT5Shutdown', 'MT5TerminalInfo', 'MT5Version', 'MarketBookAdd', 'MarketBookGet', 'MarketBookRelease',
            'MathAbs', 'MathArccos', 'MathArcsin', 'MathArctan', 'MathCeil', 'MathCos', 'MathExp', 'MathFloor',
            'MathIsValidNumber', 'MathLog', 'MathLog10', 'MathMax', 'MathMin', 'MathMod', 'MathPow', 'MathRand',
            'MathRound', 'MathSin', 'MathSqrt', 'MathSrand', 'MathTan', 'MessageBox', 'NormalizeDouble', 'ObjectCreate',
            'ObjectDelete', 'ObjectFind', 'ObjectGetDouble', 'ObjectGetInteger', 'ObjectGetString', 'ObjectGetTimeByValue',
            'ObjectGetValueByTime', 'ObjectMove', 'ObjectName', 'ObjectSetDouble', 'ObjectSetInteger', 'ObjectSetString',
            'ObjectsDeleteAll', 'ObjectsTotal', 'OnBookEvent', 'OnCalculate', 'OnChartEvent', 'OnDeinit', 'OnInit',
            'OnStart', 'OnTester', 'OnTesterDeinit', 'OnTesterInit', 'OnTesterPass', 'OnTick', 'OnTimer', 'OnTrade',
            'OnTradeTransaction', 'OrderCalcMargin', 'OrderCalcProfit', 'OrderCheck', 'OrderGetDouble', 'OrderGetInteger',
            'OrderGetString', 'OrderGetTicket', 'OrderSelect', 'OrderSend', 'OrderSendAsync', 'OrdersTotal', 'ParameterGetRange',
            'ParameterSetRange', 'Period', 'PeriodSeconds', 'PlaySound', 'PlotIndexGetInteger', 'PlotIndexSetDouble',
            'PlotIndexSetInteger', 'PlotIndexSetString', 'Point', 'PositionGetDouble', 'PositionGetInteger', 'PositionGetString',
            'PositionGetSymbol', 'PositionGetTicket', 'PositionSelect', 'PositionSelectByTicket', 'PositionsTotal',
            'Print', 'PrintFormat', 'ResetLastError', 'ResourceCreate', 'ResourceFree', 'ResourceReadImage', 'ResourceSave',
            'SendFTP', 'SendMail', 'SendNotification', 'SeriesInfoInteger', 'SetIndexBuffer', 'ShortArrayToString',
            'ShortToString', 'SignalBaseGetDouble', 'SignalBaseGetInteger', 'SignalBaseGetString', 'SignalBaseSelect',
            'SignalBaseTotal', 'SignalInfoGetDouble', 'SignalInfoGetInteger', 'SignalInfoGetString', 'SignalInfoSetDouble',
            'SignalInfoSetInteger', 'SignalSubscribe', 'SignalUnsubscribe', 'Sleep', 'SocketClose', 'SocketConnect',
            'SocketCreate', 'SocketIsConnected', 'SocketIsReadable', 'SocketIsWritable', 'SocketRead', 'SocketSend',
            'SocketTimeouts', 'SocketTlsCertificate', 'SocketTlsHandshake', 'SocketTlsRead', 'SocketTlsReadAvailable',
            'SocketTlsSend', 'StringAdd', 'StringBufferLen', 'StringCompare', 'StringConcatenate', 'StringFill',
            'StringFind', 'StringFormat', 'StringGetCharacter', 'StringInit', 'StringLen', 'StringReplace', 'StringSetCharacter',
            'StringSplit', 'StringSubstr', 'StringToCharArray', 'StringToColor', 'StringToDouble', 'StringToInteger',
            'StringToLower', 'StringToShortArray', 'StringToTime', 'StringToUpper', 'StringTrimLeft', 'StringTrimRight',
            'StructToTime', 'Symbol', 'SymbolInfoDouble', 'SymbolInfoInteger', 'SymbolInfoMarginRate', 'SymbolInfoSessionQuote',
            'SymbolInfoSessionTrade', 'SymbolInfoString', 'SymbolInfoTick', 'SymbolIsSynchronized', 'SymbolName',
            'SymbolSelect', 'SymbolsTotal', 'TerminalClose', 'TerminalInfoDouble', 'TerminalInfoInteger', 'TerminalInfoString',
            'TesterStatistics', 'TextGetSize', 'TextOut', 'TextSetFont', 'TimeCurrent', 'TimeDaylightSavings', 'TimeGMT',
            'TimeGMTOffset', 'TimeLocal', 'TimeToString', 'TimeToStruct', 'TimeTradeServer', 'UninitializeReason',
            'WebRequest', 'ZeroMemory', 'acos', 'asin', 'atan', 'ceil', 'cos', 'exp', 'fabs', 'floor', 'fmax', 'fmin',
            'fmod', 'iAD', 'iADX', 'iADXWilder', 'iAMA', 'iAO', 'iATR', 'iAlligator', 'iBWMFI', 'iBands', 'iBarShift',
            'iBars', 'iBearsPower', 'iBullsPower', 'iCCI', 'iChaikin', 'iClose', 'iCustom', 'iDEMA', 'iDeMarker',
            'iEnvelopes', 'iForce', 'iFrAMA', 'iFractals', 'iGator', 'iHigh', 'iHighest', 'iIchimoku', 'iLow', 'iLowest',
            'iMA', 'iMACD', 'iMFI', 'iMomentum', 'iOBV', 'iOpen', 'iOsMA', 'iRSI', 'iRVI', 'iRealVolume', 'iSAR',
            'iSpread', 'iStdDev', 'iStochastic', 'iTEMA', 'iTickVolume', 'iTime', 'iTriX', 'iVIDyA', 'iVolume',
            'iVolumes', 'iWPR', 'log', 'log10', 'pow', 'rand', 'round', 'sin', 'sqrt', 'srand', 'tan',
        ),
        2 => array(
            'ACCOUNT_ASSETS', 'ACCOUNT_BALANCE', 'ACCOUNT_COMMISSION_BLOCKED', 'ACCOUNT_COMPANY', 'ACCOUNT_CREDIT',
            'ACCOUNT_CURRENCY', 'ACCOUNT_EQUITY', 'ACCOUNT_LEVERAGE', 'ACCOUNT_LIABILITIES', 'ACCOUNT_LIMIT_ORDERS',
            'ACCOUNT_LOGIN', 'ACCOUNT_MARGIN', 'ACCOUNT_MARGIN_FREE', 'ACCOUNT_MARGIN_INITIAL', 'ACCOUNT_MARGIN_LEVEL',
            'ACCOUNT_MARGIN_MAINTENANCE', 'ACCOUNT_MARGIN_SO_CALL', 'ACCOUNT_MARGIN_SO_MODE', 'ACCOUNT_MARGIN_SO_SO',
            'ACCOUNT_NAME', 'ACCOUNT_PROFIT', 'ACCOUNT_SERVER', 'ACCOUNT_STOPOUT_MODE_MONEY', 'ACCOUNT_STOPOUT_MODE_PERCENT',
            'ACCOUNT_TRADE_ALLOWED', 'ACCOUNT_TRADE_EXPERT', 'ACCOUNT_TRADE_MODE', 'ACCOUNT_TRADE_MODE_CONTEST',
            'ACCOUNT_TRADE_MODE_DEMO', 'ACCOUNT_TRADE_MODE_REAL', 'ALIGN_CENTER', 'ALIGN_LEFT', 'ALIGN_RIGHT', 'ANCHOR_CENTER',
            'ANCHOR_LEFT', 'ANCHOR_LEFT_LOWER', 'ANCHOR_LEFT_UPPER', 'ANCHOR_LOWER', 'ANCHOR_RIGHT', 'ANCHOR_RIGHT_LOWER',
            'ANCHOR_RIGHT_UPPER', 'ANCHOR_UPPER', 'BASE_LINE', 'BOOK_TYPE_BUY', 'BOOK_TYPE_BUY_MARKET', 'BOOK_TYPE_SELL',
            'BOOK_TYPE_SELL_MARKET', 'BORDER_FLAT', 'BORDER_RAISED', 'BORDER_SUNKEN', 'CHARTEVENT_CHART_CHANGE',
            'CHARTEVENT_CLICK', 'CHARTEVENT_CUSTOM', 'CHARTEVENT_CUSTOM_LAST', 'CHARTEVENT_KEYDOWN', 'CHARTEVENT_MOUSE_MOVE',
            'CHARTEVENT_OBJECT_CHANGE', 'CHARTEVENT_OBJECT_CLICK', 'CHARTEVENT_OBJECT_CREATE', 'CHARTEVENT_OBJECT_DELETE',
            'CHARTEVENT_OBJECT_DRAG', 'CHARTEVENT_OBJECT_ENDEDIT', 'CHARTS_MAX', 'CHART_AUTOSCROLL', 'CHART_BARS',
            'CHART_BEGIN', 'CHART_BRING_TO_TOP', 'CHART_CANDLES', 'CHART_COLOR_ASK', 'CHART_COLOR_BACKGROUND', 'CHART_COLOR_BID',
            'CHART_COLOR_CANDLE_BEAR', 'CHART_COLOR_CANDLE_BULL', 'CHART_COLOR_CHART_DOWN', 'CHART_COLOR_CHART_LINE',
            'CHART_COLOR_CHART_UP', 'CHART_COLOR_FOREGROUND', 'CHART_COLOR_GRID', 'CHART_COLOR_LAST', 'CHART_COLOR_STOP_LEVEL',
            'CHART_COLOR_VOLUME', 'CHART_COMMENT', 'CHART_CURRENT_POS', 'CHART_DRAG_TRADE_LEVELS', 'CHART_EVENT_MOUSE_MOVE',
            'CHART_EVENT_OBJECT_CREATE', 'CHART_EVENT_OBJECT_DELETE', 'CHART_FIRST_VISIBLE_BAR', 'CHART_FIXED_MAX',
            'CHART_FIXED_MIN', 'CHART_FIXED_POSITION', 'CHART_FOREGROUND', 'CHART_HEIGHT_IN_PIXELS', 'CHART_IS_OBJECT',
            'CHART_LINE', 'CHART_MODE', 'CHART_MOUSE_SCROLL', 'CHART_POINTS_PER_BAR', 'CHART_PRICE_MAX', 'CHART_PRICE_MIN',
            'CHART_SCALE', 'CHART_SCALEFIX', 'CHART_SCALEFIX_11', 'CHART_SCALE_PT_PER_BAR', 'CHART_SHIFT', 'CHART_SHIFT_SIZE',
            'CHART_SHOW_ASK_LINE', 'CHART_SHOW_BID_LINE', 'CHART_SHOW_DATE_SCALE', 'CHART_SHOW_GRID', 'CHART_SHOW_LAST_LINE',
            'CHART_SHOW_OBJECT_DESCR', 'CHART_SHOW_OHLC', 'CHART_SHOW_ONE_CLICK', 'CHART_SHOW_PERIOD_SEP', 'CHART_SHOW_PRICE_SCALE',
            'CHART_SHOW_TRADE_LEVELS', 'CHART_SHOW_VOLUMES', 'CHART_VISIBLE_BARS', 'CHART_VOLUME_HIDE', 'CHART_VOLUME_REAL',
            'CHART_VOLUME_TICK', 'CHART_WIDTH_IN_BARS', 'CHART_WIDTH_IN_PIXELS', 'CHART_WINDOWS_TOTAL', 'CHART_WINDOW_HANDLE',
            'CHART_WINDOW_IS_VISIBLE', 'CHART_WINDOW_YDISTANCE', 'CHAR_MAX', 'CHAR_MIN', 'CHIKOUSPAN_LINE', 'CORNER_LEFT_LOWER',
            'CORNER_LEFT_UPPER', 'CORNER_RIGHT_LOWER', 'CORNER_RIGHT_UPPER', 'CP_ACP', 'CP_MACCP', 'CP_OEMCP', 'CP_SYMBOL',
            'CP_THREAD_ACP', 'CP_UTF7', 'CP_UTF8', 'CRYPT_AES128', 'CRYPT_AES256', 'CRYPT_ARCH_ZIP', 'CRYPT_BASE64',
            'CRYPT_DES', 'CRYPT_HASH_MD5', 'CRYPT_HASH_SHA1', 'CRYPT_HASH_SHA256', 'DBL_DIG', 'DBL_EPSILON', 'DBL_MANT_DIG',
            'DBL_MAX', 'DBL_MAX_10_EXP', 'DBL_MAX_EXP', 'DBL_MIN', 'DBL_MIN_10_EXP', 'DBL_MIN_EXP', 'DEAL_COMMENT',
            'DEAL_COMMISSION', 'DEAL_ENTRY', 'DEAL_ENTRY_IN', 'DEAL_ENTRY_INOUT', 'DEAL_ENTRY_OUT', 'DEAL_MAGIC',
            'DEAL_ORDER', 'DEAL_POSITION_ID', 'DEAL_PRICE', 'DEAL_PROFIT', 'DEAL_SWAP', 'DEAL_SYMBOL', 'DEAL_TIME',
            'DEAL_TIME_MSC', 'DEAL_TYPE', 'DEAL_TYPE_BALANCE', 'DEAL_TYPE_BONUS', 'DEAL_TYPE_BUY_CANCELED', 'DEAL_TYPE_CHARGE',
            'DEAL_TYPE_COMMISSION', 'DEAL_TYPE_COMMISSION_AGENT_DAILY', 'DEAL_TYPE_COMMISSION_AGENT_MONTHLY', 'DEAL_TYPE_COMMISSION_DAILY',
            'DEAL_TYPE_COMMISSION_MONTHLY', 'DEAL_TYPE_CORRECTION', 'DEAL_TYPE_CREDIT', 'DEAL_TYPE_INTEREST', 'DEAL_TYPE_SELL',
            'DEAL_TYPE_SELL_CANCELED', 'DEAL_VOLUME', 'DRAW_ARROW', 'DRAW_BARS', 'DRAW_CANDLES', 'DRAW_COLOR_ARROW',
            'DRAW_COLOR_BARS', 'DRAW_COLOR_CANDLES', 'DRAW_COLOR_HISTOGRAM', 'DRAW_COLOR_HISTOGRAM2', 'DRAW_COLOR_LINE',
            'DRAW_COLOR_SECTION', 'DRAW_COLOR_ZIGZAG', 'DRAW_FILLING', 'DRAW_HISTOGRAM', 'DRAW_HISTOGRAM2', 'DRAW_LINE',
            'DRAW_NONE', 'DRAW_SECTION', 'DRAW_ZIGZAG', 'ELLIOTT_CYCLE', 'ELLIOTT_GRAND_SUPERCYCLE', 'ELLIOTT_INTERMEDIATE',
            'ELLIOTT_MINOR', 'ELLIOTT_MINUTE', 'ELLIOTT_PRIMARY', 'ELLIOTT_SUBMINUETTE', 'ELLIOTT_SUPERCYCLE', 'EMPTY_VALUE',
            'ERR_ACCOUNT_WRONG_PROPERTY', 'ERR_ARRAY_BAD_SIZE', 'ERR_ARRAY_RESIZE_ERROR', 'ERR_BOOKS_CANNOT_ADD',
            'ERR_BOOKS_CANNOT_DELETE', 'ERR_BOOKS_CANNOT_GET', 'ERR_BOOKS_CANNOT_SUBSCRIBE', 'ERR_BUFFERS_NO_MEMORY',
            'ERR_BUFFERS_WRONG_INDEX', 'ERR_CANNOT_CLEAN_DIRECTORY', 'ERR_CANNOT_DELETE_DIRECTORY', 'ERR_CANNOT_DELETE_FILE',
            'ERR_CANNOT_OPEN_FILE', 'ERR_CHART_CANNOT_CHANGE', 'ERR_CHART_CANNOT_CREATE_TIMER', 'ERR_CHART_CANNOT_OPEN',
            'ERR_CHART_INDICATOR_CANNOT_ADD', 'ERR_CHART_INDICATOR_CANNOT_DEL', 'ERR_CHART_INDICATOR_NOT_FOUND',
            'ERR_CHART_NAVIGATE_FAILED', 'ERR_CHART_NOT_FOUND', 'ERR_CHART_NO_EXPERT', 'ERR_CHART_NO_REPLY', 'ERR_CHART_SCREENSHOT_FAILED',
            'ERR_CHART_TEMPLATE_FAILED', 'ERR_CHART_WINDOW_NOT_FOUND', 'ERR_CHART_WRONG_ID', 'ERR_CHART_WRONG_PARAMETER',
            'ERR_CHART_WRONG_PROPERTY', 'ERR_CHAR_ARRAY_ONLY', 'ERR_CUSTOM_WRONG_PROPERTY', 'ERR_DIRECTORY_NOT_EXIST',
            'ERR_DOUBLE_ARRAY_ONLY', 'ERR_FILE_BINSTRINGSIZE', 'ERR_FILE_CACHEBUFFER_ERROR', 'ERR_FILE_CANNOT_REWRITE',
            'ERR_FILE_ISNOT_DIRECTORY', 'ERR_FILE_IS_DIRECTORY', 'ERR_FILE_NOTBIN', 'ERR_FILE_NOTCSV', 'ERR_FILE_NOTTOREAD',
            'ERR_FILE_NOTTOWRITE', 'ERR_FILE_NOTTXT', 'ERR_FILE_NOTTXTORCSV', 'ERR_FILE_NOT_EXIST', 'ERR_FILE_READERROR',
            'ERR_FILE_WRITEERROR', 'ERR_FLOAT_ARRAY_ONLY', 'ERR_FTP_SEND_FAILED', 'ERR_FUNCTION_NOT_ALLOWED', 'ERR_GLOBALVARIABLE_EXISTS',
            'ERR_GLOBALVARIABLE_NOT_FOUND', 'ERR_HISTORY_NOT_FOUND', 'ERR_HISTORY_WRONG_PROPERTY', 'ERR_INCOMPATIBLE_ARRAYS',
            'ERR_INCOMPATIBLE_FILE', 'ERR_INDICATOR_CANNOT_ADD', 'ERR_INDICATOR_CANNOT_APPLY', 'ERR_INDICATOR_CANNOT_CREATE',
            'ERR_INDICATOR_CUSTOM_NAME', 'ERR_INDICATOR_DATA_NOT_FOUND', 'ERR_INDICATOR_NO_MEMORY', 'ERR_INDICATOR_PARAMETERS_MISSING',
            'ERR_INDICATOR_PARAMETER_TYPE', 'ERR_INDICATOR_UNKNOWN_SYMBOL', 'ERR_INDICATOR_WRONG_HANDLE', 'ERR_INDICATOR_WRONG_INDEX',
            'ERR_INDICATOR_WRONG_PARAMETERS', 'ERR_INTERNAL_ERROR', 'ERR_INT_ARRAY_ONLY', 'ERR_INVALID_ARRAY', 'ERR_INVALID_DATETIME',
            'ERR_INVALID_FILEHANDLE', 'ERR_INVALID_PARAMETER', 'ERR_INVALID_POINTER', 'ERR_INVALID_POINTER_TYPE',
            'ERR_LONG_ARRAY_ONLY', 'ERR_MAIL_SEND_FAILED', 'ERR_MARKET_LASTTIME_UNKNOWN', 'ERR_MARKET_NOT_SELECTED',
            'ERR_MARKET_SELECT_ERROR', 'ERR_MARKET_UNKNOWN_SYMBOL', 'ERR_MARKET_WRONG_PROPERTY', 'ERR_NOTIFICATION_SEND_FAILED',
            'ERR_NOTIFICATION_TOO_FREQUENT', 'ERR_NOTIFICATION_WRONG_PARAMETER', 'ERR_NOTIFICATION_WRONG_SETTINGS',
            'ERR_NOTINITIALIZED_STRING', 'ERR_NOT_ENOUGH_MEMORY', 'ERR_NO_STRING_DATE', 'ERR_NUMBER_ARRAYS_ONLY',
            'ERR_OBJECT_ERROR', 'ERR_OBJECT_GETDATE_FAILED', 'ERR_OBJECT_GETVALUE_FAILED', 'ERR_OBJECT_NOT_FOUND',
            'ERR_OBJECT_WRONG_PROPERTY', 'ERR_ONEDIM_ARRAYS_ONLY', 'ERR_OPENCL_BUFFER_CREATE', 'ERR_OPENCL_CONTEXT_CREATE',
            'ERR_OPENCL_EXECUTE', 'ERR_OPENCL_INTERNAL', 'ERR_OPENCL_INVALID_HANDLE', 'ERR_OPENCL_NOT_SUPPORTED',
            'ERR_OPENCL_QUEUE_CREATE', 'ERR_OPENCL_SET_KERNEL_PARAMETER', 'ERR_OPENCL_TOO_LONG_KERNEL_NAME', 'ERR_OPENCL_WRONG_BUFFER_OFFSET',
            'ERR_OPENCL_WRONG_BUFFER_SIZE', 'ERR_RESOURCE_NAME_DUPLICATED', 'ERR_RESOURCE_NAME_IS_TOO_LONG', 'ERR_RESOURCE_NOT_FOUND',
            'ERR_RESOURCE_UNSUPPORTED_TYPE', 'ERR_SERIES_ARRAY', 'ERR_SHORT_ARRAY_ONLY', 'ERR_SMALL_ARRAY', 'ERR_SMALL_ASSERIES_ARRAY',
            'ERR_STRINGPOS_OUTOFRANGE', 'ERR_STRING_OUT_OF_MEMORY', 'ERR_STRING_RESIZE_ERROR', 'ERR_STRING_SMALL_LEN',
            'ERR_STRING_TIME_ERROR', 'ERR_STRING_TOO_BIGNUMBER', 'ERR_STRING_UNKNOWNTYPE', 'ERR_STRING_ZEROADDED',
            'ERR_STRUCT_WITHOBJECTS_ORCLASS', 'ERR_SUCCESS', 'ERR_TERMINAL_WRONG_PROPERTY', 'ERR_TOO_LONG_FILENAME',
            'ERR_TOO_MANY_FILES', 'ERR_TOO_MANY_FORMATTERS', 'ERR_TOO_MANY_PARAMETERS', 'ERR_TRADE_DEAL_NOT_FOUND',
            'ERR_TRADE_DISABLED', 'ERR_TRADE_ORDER_NOT_FOUND', 'ERR_TRADE_POSITION_NOT_FOUND', 'ERR_TRADE_SEND_FAILED',
            'ERR_TRADE_WRONG_PROPERTY', 'ERR_USER_ERROR_FIRST', 'ERR_WEBREQUEST_CONNECT_FAILED', 'ERR_WEBREQUEST_INVALID_ADDRESS',
            'ERR_WEBREQUEST_REQUEST_FAILED', 'ERR_WEBREQUEST_TIMEOUT', 'ERR_WRONG_DIRECTORYNAME', 'ERR_WRONG_FILEHANDLE',
            'ERR_WRONG_FILENAME', 'ERR_WRONG_FORMATSTRING', 'ERR_WRONG_INTERNAL_PARAMETER', 'ERR_WRONG_STRING_DATE',
            'ERR_WRONG_STRING_OBJECT', 'ERR_WRONG_STRING_PARAMETER', 'ERR_WRONG_STRING_TIME', 'ERR_ZEROSIZE_ARRAY',
            'FILE_ACCESS_DATE', 'FILE_ANSI', 'FILE_BIN', 'FILE_COMMON', 'FILE_CREATE_DATE', 'FILE_CSV', 'FILE_END',
            'FILE_EXISTS', 'FILE_IS_BINARY', 'FILE_IS_COMMON', 'FILE_IS_CSV', 'FILE_IS_READABLE', 'FILE_IS_TEXT',
            'FILE_IS_WRITABLE', 'FILE_LINE_END', 'FILE_MODIFY_DATE', 'FILE_POSITION', 'FILE_READ', 'FILE_REWRITE',
            'FILE_SHARE_READ', 'FILE_SHARE_WRITE', 'FILE_SIZE', 'FILE_TXT', 'FILE_UNICODE', 'FILE_WRITE', 'FLT_DIG',
            'FLT_EPSILON', 'FLT_MANT_DIG', 'FLT_MAX', 'FLT_MAX_10_EXP', 'FLT_MAX_EXP', 'FLT_MIN', 'FLT_MIN_10_EXP',
            'FLT_MIN_EXP', 'FRIDAY', 'GANN_DOWN_TREND', 'GANN_UP_TREND', 'GATORJAW_LINE', 'GATORLIPS_LINE', 'GATORTEETH_LINE',
            'IDABORT', 'IDCANCEL', 'IDCONTINUE', 'IDIGNORE', 'IDNO', 'IDOK', 'IDRETRY', 'IDTRYAGAIN', 'IDYES', 'INDICATOR_CALCULATIONS',
            'INDICATOR_COLOR_INDEX', 'INDICATOR_DATA', 'INDICATOR_DIGITS', 'INDICATOR_HEIGHT', 'INDICATOR_LEVELCOLOR',
            'INDICATOR_LEVELS', 'INDICATOR_LEVELSTYLE', 'INDICATOR_LEVELTEXT', 'INDICATOR_LEVELVALUE', 'INDICATOR_LEVELWIDTH',
            'INDICATOR_MAXIMUM', 'INDICATOR_MINIMUM', 'INDICATOR_SHORTNAME', 'IND_AC', 'IND_AD', 'IND_ADX', 'IND_ADXW',
            'IND_ALLIGATOR', 'IND_AMA', 'IND_AO', 'IND_ATR', 'IND_BANDS', 'IND_BEARS', 'IND_BULLS', 'IND_BWMFI',
            'IND_CCI', 'IND_CHAIKIN', 'IND_CUSTOM', 'IND_DEMA', 'IND_DEMARKER', 'IND_ENVELOPES', 'IND_FORCE', 'IND_FRACTALS',
            'IND_FRAMA', 'IND_GATOR', 'IND_ICHIMOKU', 'IND_MA', 'IND_MACD', 'IND_MFI', 'IND_MOMENTUM', 'IND_OBV',
            'IND_OSMA', 'IND_RSI', 'IND_RVI', 'IND_SAR', 'IND_STDDEV', 'IND_STOCHASTIC', 'IND_TEMA', 'IND_TRIX',
            'IND_VIDYA', 'IND_VOLUMES', 'IND_WPR', 'INT_MAX', 'INT_MIN', 'INVALID_HANDLE', 'IS_DEBUG_MODE', 'IS_PROFILE_MODE',
            'KIJUNSEN_LINE', 'LICENSE_DEMO', 'LICENSE_FREE', 'LICENSE_FULL', 'LICENSE_TIME', 'LONG_MAX', 'LONG_MIN',
            'LOWER_BAND', 'LOWER_HISTOGRAM', 'LOWER_LINE', 'MAIN_LINE', 'MB_ABORTRETRYIGNORE', 'MB_CANCELTRYCONTINUE',
            'MB_DEFBUTTON1', 'MB_DEFBUTTON2', 'MB_DEFBUTTON3', 'MB_DEFBUTTON4', 'MB_ICONQUESTION', 'MB_OK', 'MB_OKCANCEL',
            'MB_RETRYCANCEL', 'MB_YESNO', 'MB_YESNOCANCEL', 'MINUSDI_LINE', 'MODE_EMA', 'MODE_LWMA', 'MODE_SMA',
            'MODE_SMMA', 'MONDAY', 'MQL_DEBUG', 'MQL_DLLS_ALLOWED', 'MQL_FRAME_MODE', 'MQL_LICENSE_TYPE', 'MQL_MEMORY_LIMIT',
            'MQL_MEMORY_USED', 'MQL_OPTIMIZATION', 'MQL_PROFILER', 'MQL_PROGRAM_NAME', 'MQL_PROGRAM_PATH', 'MQL_PROGRAM_TYPE',
            'MQL_SIGNALS_ALLOWED', 'MQL_TESTER', 'MQL_TRADE_ALLOWED', 'MQL_VISUAL_MODE', 'M_1_PI', 'M_2_PI', 'M_2_SQRTPI',
            'M_E', 'M_LN2', 'M_LN10', 'M_LOG2E', 'M_LOG10E', 'M_PI', 'M_PI_2', 'M_PI_4', 'M_SQRT1_2', 'M_SQRT2',
            'NULL', 'OBJPROP_ALIGN', 'OBJPROP_ANCHOR', 'OBJPROP_ANGLE', 'OBJPROP_ARROWCODE', 'OBJPROP_BACK', 'OBJPROP_BGCOLOR',
            'OBJPROP_BMPFILE', 'OBJPROP_BORDER_COLOR', 'OBJPROP_BORDER_TYPE', 'OBJPROP_CHART_ID', 'OBJPROP_CHART_SCALE',
            'OBJPROP_COLOR', 'OBJPROP_CORNER', 'OBJPROP_CREATETIME', 'OBJPROP_DATE_SCALE', 'OBJPROP_DEGREE', 'OBJPROP_DEVIATION',
            'OBJPROP_DIRECTION', 'OBJPROP_DRAWLINES', 'OBJPROP_ELLIPSE', 'OBJPROP_FILL', 'OBJPROP_FONT', 'OBJPROP_FONTSIZE',
            'OBJPROP_HIDDEN', 'OBJPROP_LEVELCOLOR', 'OBJPROP_LEVELS', 'OBJPROP_LEVELSTYLE', 'OBJPROP_LEVELTEXT',
            'OBJPROP_LEVELVALUE', 'OBJPROP_LEVELWIDTH', 'OBJPROP_NAME', 'OBJPROP_PERIOD', 'OBJPROP_PRICE', 'OBJPROP_PRICE_SCALE',
            'OBJPROP_RAY', 'OBJPROP_RAY_LEFT', 'OBJPROP_RAY_RIGHT', 'OBJPROP_READONLY', 'OBJPROP_SCALE', 'OBJPROP_SELECTABLE',
            'OBJPROP_SELECTED', 'OBJPROP_STATE', 'OBJPROP_STYLE', 'OBJPROP_SYMBOL', 'OBJPROP_TEXT', 'OBJPROP_TIME',
            'OBJPROP_TIMEFRAMES', 'OBJPROP_TOOLTIP', 'OBJPROP_TYPE', 'OBJPROP_WIDTH', 'OBJPROP_XDISTANCE', 'OBJPROP_XOFFSET',
            'OBJPROP_XSIZE', 'OBJPROP_YDISTANCE', 'OBJPROP_YOFFSET', 'OBJPROP_YSIZE', 'OBJPROP_ZORDER', 'OBJ_ALL_PERIODS',
            'OBJ_ARROW', 'OBJ_ARROWED_LINE', 'OBJ_ARROW_BUY', 'OBJ_ARROW_CHECK', 'OBJ_ARROW_DOWN', 'OBJ_ARROW_LEFT_PRICE',
            'OBJ_ARROW_RIGHT_PRICE', 'OBJ_ARROW_SELL', 'OBJ_ARROW_STOP', 'OBJ_ARROW_THUMB_DOWN', 'OBJ_ARROW_THUMB_UP',
            'OBJ_ARROW_UP', 'OBJ_BITMAP', 'OBJ_BITMAP_LABEL', 'OBJ_BUTTON', 'OBJ_CHANNEL', 'OBJ_CHART', 'OBJ_CYCLES',
            'OBJ_EDIT', 'OBJ_ELLIOTWAVE3', 'OBJ_ELLIOTWAVE5', 'OBJ_ELLIPSE', 'OBJ_EVENT', 'OBJ_EXPANSION', 'OBJ_FIBO',
            'OBJ_FIBOARC', 'OBJ_FIBOCHANNEL', 'OBJ_FIBOFAN', 'OBJ_FIBOTIMES', 'OBJ_GANNFAN', 'OBJ_GANNGRID', 'OBJ_GANNLINE',
            'OBJ_HLINE', 'OBJ_LABEL', 'OBJ_NO_PERIODS', 'OBJ_PERIOD_D1', 'OBJ_PERIOD_H1', 'OBJ_PERIOD_H2', 'OBJ_PERIOD_H3',
            'OBJ_PERIOD_H4', 'OBJ_PERIOD_H6', 'OBJ_PERIOD_H8', 'OBJ_PERIOD_H12', 'OBJ_PERIOD_M1', 'OBJ_PERIOD_M2',
            'OBJ_PERIOD_M3', 'OBJ_PERIOD_M4', 'OBJ_PERIOD_M5', 'OBJ_PERIOD_M6', 'OBJ_PERIOD_M10', 'OBJ_PERIOD_M12',
            'OBJ_PERIOD_M15', 'OBJ_PERIOD_M20', 'OBJ_PERIOD_M30', 'OBJ_PERIOD_MN1', 'OBJ_PERIOD_W1', 'OBJ_PITCHFORK',
            'OBJ_RECTANGLE', 'OBJ_RECTANGLE_LABEL', 'OBJ_REGRESSION', 'OBJ_STDDEVCHANNEL', 'OBJ_TEXT', 'OBJ_TREND',
            'OBJ_TRENDBYANGLE', 'OBJ_TRIANGLE', 'OBJ_VLINE', 'ORDER_COMMENT', 'ORDER_FILLING_FOK', 'ORDER_FILLING_IOC',
            'ORDER_FILLING_RETURN', 'ORDER_MAGIC', 'ORDER_POSITION_ID', 'ORDER_PRICE_CURRENT', 'ORDER_PRICE_OPEN',
            'ORDER_PRICE_STOPLIMIT', 'ORDER_SL', 'ORDER_STATE', 'ORDER_STATE_CANCELED', 'ORDER_STATE_FILLED', 'ORDER_STATE_PARTIAL',
            'ORDER_STATE_PLACED', 'ORDER_STATE_REJECTED', 'ORDER_STATE_STARTED', 'ORDER_SYMBOL', 'ORDER_TIME_DAY',
            'ORDER_TIME_DONE', 'ORDER_TIME_DONE_MSC', 'ORDER_TIME_EXPIRATION', 'ORDER_TIME_GTC', 'ORDER_TIME_SETUP',
            'ORDER_TIME_SETUP_MSC', 'ORDER_TIME_SPECIFIED', 'ORDER_TIME_SPECIFIED_DAY', 'ORDER_TP', 'ORDER_TYPE',
            'ORDER_TYPE_BUY', 'ORDER_TYPE_BUY_LIMIT', 'ORDER_TYPE_BUY_STOP', 'ORDER_TYPE_BUY_STOP_LIMIT', 'ORDER_TYPE_FILLING',
            'ORDER_TYPE_SELL', 'ORDER_TYPE_SELL_LIMIT', 'ORDER_TYPE_SELL_STOP', 'ORDER_TYPE_SELL_STOP_LIMIT', 'ORDER_TYPE_TIME',
            'ORDER_VOLUME_CURRENT', 'ORDER_VOLUME_INITIAL', 'PERIOD_CURRENT', 'PERIOD_D1', 'PERIOD_H2', 'PERIOD_H3',
            'PERIOD_H4', 'PERIOD_H6', 'PERIOD_H8', 'PERIOD_H12', 'PERIOD_M1', 'PERIOD_M2', 'PERIOD_M3', 'PERIOD_M4',
            'PERIOD_M5', 'PERIOD_M6', 'PERIOD_M10', 'PERIOD_M12', 'PERIOD_M15', 'PERIOD_M20', 'PERIOD_M30', 'PERIOD_MN1',
            'PERIOD_W1', 'PLOT_ARROW', 'PLOT_ARROW_SHIFT', 'PLOT_COLOR_INDEXES', 'PLOT_DRAW_BEGIN', 'PLOT_DRAW_TYPE',
            'PLOT_EMPTY_VALUE', 'PLOT_LABEL', 'PLOT_LINE_COLOR', 'PLOT_LINE_STYLE', 'PLOT_LINE_WIDTH', 'PLOT_SHIFT',
            'PLOT_SHOW_DATA', 'PLUSDI_LINE', 'POINTER_AUTOMATIC', 'POINTER_DYNAMIC', 'POINTER_INVALID', 'POSITION_COMMENT',
            'POSITION_COMMISSION', 'POSITION_IDENTIFIER', 'POSITION_MAGIC', 'POSITION_PRICE_CURRENT', 'POSITION_PRICE_OPEN',
            'POSITION_PROFIT', 'POSITION_SL', 'POSITION_SWAP', 'POSITION_SYMBOL', 'POSITION_TIME', 'POSITION_TIME_MSC',
            'POSITION_TIME_UPDATE', 'POSITION_TIME_UPDATE_MSC', 'POSITION_TP', 'POSITION_TYPE', 'POSITION_TYPE_BUY',
            'POSITION_TYPE_SELL', 'POSITION_VOLUME', 'PRICE_CLOSE', 'PRICE_HIGH', 'PRICE_LOW', 'PRICE_MEDIAN', 'PRICE_OPEN',
            'PRICE_TYPICAL', 'PRICE_WEIGHTED', 'PROGRAM_EXPERT', 'PROGRAM_INDICATOR', 'PROGRAM_SCRIPT', 'REASON_ACCOUNT',
            'REASON_CHARTCHANGE', 'REASON_CHARTCLOSE', 'REASON_CLOSE', 'REASON_INITFAILED', 'REASON_PARAMETERS',
            'REASON_PROGRAM', 'REASON_RECOMPILE', 'REASON_REMOVE', 'REASON_TEMPLATE', 'SATURDAY', 'SEEK_CUR', 'SEEK_END',
            'SEEK_SET', 'SENKOUSPANA_LINE', 'SENKOUSPANB_LINE', 'SERIES_BARS_COUNT', 'SERIES_FIRSTDATE', 'SERIES_LASTBAR_DATE',
            'SERIES_SERVER_FIRSTDATE', 'SERIES_SYNCHRONIZED', 'SERIES_TERMINAL_FIRSTDATE', 'SHORT_MAX', 'SHORT_MIN',
            'SIGNAL_BASE_AUTHOR_LOGIN', 'SIGNAL_BASE_BALANCE', 'SIGNAL_BASE_BROKER', 'SIGNAL_BASE_BROKER_SERVER',
            'SIGNAL_BASE_CURRENCY', 'SIGNAL_BASE_DATE_PUBLISHED', 'SIGNAL_BASE_DATE_STARTED', 'SIGNAL_BASE_EQUITY',
            'SIGNAL_BASE_GAIN', 'SIGNAL_BASE_ID', 'SIGNAL_BASE_LEVERAGE', 'SIGNAL_BASE_MAX_DRAWDOWN', 'SIGNAL_BASE_NAME',
            'SIGNAL_BASE_PIPS', 'SIGNAL_BASE_PRICE', 'SIGNAL_BASE_RATING', 'SIGNAL_BASE_ROI', 'SIGNAL_BASE_SUBSCRIBERS',
            'SIGNAL_BASE_TRADES', 'SIGNAL_BASE_TRADE_MODE', 'SIGNAL_INFO_CONFIRMATIONS_DISABLED', 'SIGNAL_INFO_COPY_SLTP',
            'SIGNAL_INFO_DEPOSIT_PERCENT', 'SIGNAL_INFO_EQUITY_LIMIT', 'SIGNAL_INFO_ID', 'SIGNAL_INFO_NAME', 'SIGNAL_INFO_SLIPPAGE',
            'SIGNAL_INFO_SUBSCRIPTION_ENABLED', 'SIGNAL_INFO_TERMS_AGREE', 'SIGNAL_INFO_VOLUME_PERCENT', 'SIGNAL_LINE',
            'STAT_BALANCEDD_PERCENT', 'STAT_BALANCEMIN', 'STAT_BALANCE_DD', 'STAT_BALANCE_DDREL_PERCENT', 'STAT_BALANCE_DD_RELATIVE',
            'STAT_CONLOSSMAX', 'STAT_CONLOSSMAX_TRADES', 'STAT_CONPROFITMAX', 'STAT_CONPROFITMAX_TRADES', 'STAT_CUSTOM_ONTESTER',
            'STAT_DEALS', 'STAT_EQUITYDD_PERCENT', 'STAT_EQUITYMIN', 'STAT_EQUITY_DD', 'STAT_EQUITY_DDREL_PERCENT',
            'STAT_EQUITY_DD_RELATIVE', 'STAT_EXPECTED_PAYOFF', 'STAT_GROSS_LOSS', 'STAT_GROSS_PROFIT', 'STAT_INITIAL_DEPOSIT',
            'STAT_LONG_TRADES', 'STAT_LOSSTRADES_AVGCON', 'STAT_LOSS_TRADES', 'STAT_MAX_CONLOSSES', 'STAT_MAX_CONLOSS_TRADES',
            'STAT_MAX_CONPROFIT_TRADES', 'STAT_MAX_CONWINS', 'STAT_MAX_LOSSTRADE', 'STAT_MAX_PROFITTRADE', 'STAT_MIN_MARGINLEVEL',
            'STAT_PROFIT', 'STAT_PROFITTRADES_AVGCON', 'STAT_PROFIT_FACTOR', 'STAT_PROFIT_LONGTRADES', 'STAT_PROFIT_SHORTTRADES',
            'STAT_PROFIT_TRADES', 'STAT_RECOVERY_FACTOR', 'STAT_SHARPE_RATIO', 'STAT_SHORT_TRADES', 'STAT_TRADES',
            'STAT_WITHDRAWAL', 'STO_CLOSECLOSE', 'STO_LOWHIGH', 'STYLE_DASH', 'STYLE_DASHDOT', 'STYLE_DASHDOTDOT',
            'STYLE_DOT', 'STYLE_SOLID', 'SUNDAY', 'SYMBOL_ASK', 'SYMBOL_ASKHIGH', 'SYMBOL_ASKLOW', 'SYMBOL_BANK',
            'SYMBOL_BASIS', 'SYMBOL_BID', 'SYMBOL_BIDHIGH', 'SYMBOL_BIDLOW', 'SYMBOL_CALC_MODE_CFD', 'SYMBOL_CALC_MODE_CFDINDEX',
            'SYMBOL_CALC_MODE_CFDLEVERAGE', 'SYMBOL_CALC_MODE_EXCH_FUTURES', 'SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS',
            'SYMBOL_CALC_MODE_EXCH_STOCKS', 'SYMBOL_CALC_MODE_FOREX', 'SYMBOL_CALC_MODE_FUTURES', 'SYMBOL_CALC_MODE_SERV_COLLATERAL',
            'SYMBOL_CURRENCY_BASE', 'SYMBOL_CURRENCY_MARGIN', 'SYMBOL_CURRENCY_PROFIT', 'SYMBOL_DESCRIPTION', 'SYMBOL_DIGITS',
            'SYMBOL_EXPIRATION_DAY', 'SYMBOL_EXPIRATION_GTC', 'SYMBOL_EXPIRATION_SPECIFIED', 'SYMBOL_EXPIRATION_SPECIFIED_DAY',
            'SYMBOL_EXPIRATION_TIME', 'SYMBOL_FILLING_FOK', 'SYMBOL_FILLING_IOC', 'SYMBOL_FILLING_MODE', 'SYMBOL_ISIN',
            'SYMBOL_LAST', 'SYMBOL_LASTHIGH', 'SYMBOL_LASTLOW', 'SYMBOL_MARGIN_INITIAL', 'SYMBOL_MARGIN_MAINTENANCE',
            'SYMBOL_OPTION_MODE', 'SYMBOL_OPTION_MODE_EUROPEAN', 'SYMBOL_OPTION_RIGHT', 'SYMBOL_OPTION_RIGHT_CALL',
            'SYMBOL_OPTION_RIGHT_PUT', 'SYMBOL_OPTION_STRIKE', 'SYMBOL_ORDER_LIMIT', 'SYMBOL_ORDER_MARKET', 'SYMBOL_ORDER_MODE',
            'SYMBOL_ORDER_SL', 'SYMBOL_ORDER_STOP', 'SYMBOL_ORDER_TP', 'SYMBOL_PATH', 'SYMBOL_POINT', 'SYMBOL_SELECT',
            'SYMBOL_SESSION_AW', 'SYMBOL_SESSION_BUY_ORDERS', 'SYMBOL_SESSION_BUY_ORDERS_VOLUME', 'SYMBOL_SESSION_CLOSE',
            'SYMBOL_SESSION_DEALS', 'SYMBOL_SESSION_INTEREST', 'SYMBOL_SESSION_OPEN', 'SYMBOL_SESSION_PRICE_LIMIT_MAX',
            'SYMBOL_SESSION_PRICE_LIMIT_MIN', 'SYMBOL_SESSION_PRICE_SETTLEMENT', 'SYMBOL_SESSION_SELL_ORDERS', 'SYMBOL_SESSION_SELL_ORDERS_VOLUME',
            'SYMBOL_SESSION_TURNOVER', 'SYMBOL_SESSION_VOLUME', 'SYMBOL_SPREAD', 'SYMBOL_SPREAD_FLOAT', 'SYMBOL_START_TIME',
            'SYMBOL_SWAP_LONG', 'SYMBOL_SWAP_MODE', 'SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT', 'SYMBOL_SWAP_MODE_CURRENCY_MARGIN',
            'SYMBOL_SWAP_MODE_CURRENCY_SYMBOL', 'SYMBOL_SWAP_MODE_DISABLED', 'SYMBOL_SWAP_MODE_INTEREST_CURRENT',
            'SYMBOL_SWAP_MODE_INTEREST_OPEN', 'SYMBOL_SWAP_MODE_POINTS', 'SYMBOL_SWAP_MODE_REOPEN_BID', 'SYMBOL_SWAP_MODE_REOPEN_CURRENT',
            'SYMBOL_SWAP_ROLLOVER3DAYS', 'SYMBOL_SWAP_SHORT', 'SYMBOL_TICKS_BOOKDEPTH', 'SYMBOL_TIME', 'SYMBOL_TRADE_CALC_MODE',
            'SYMBOL_TRADE_CONTRACT_SIZE', 'SYMBOL_TRADE_EXECUTION_EXCHANGE', 'SYMBOL_TRADE_EXECUTION_INSTANT', 'SYMBOL_TRADE_EXECUTION_MARKET',
            'SYMBOL_TRADE_EXECUTION_REQUEST', 'SYMBOL_TRADE_EXEMODE', 'SYMBOL_TRADE_FREEZE_LEVEL', 'SYMBOL_TRADE_MODE',
            'SYMBOL_TRADE_MODE_CLOSEONLY', 'SYMBOL_TRADE_MODE_DISABLED', 'SYMBOL_TRADE_MODE_FULL', 'SYMBOL_TRADE_MODE_LONGONLY',
            'SYMBOL_TRADE_MODE_SHORTONLY', 'SYMBOL_TRADE_STOPS_LEVEL', 'SYMBOL_TRADE_TICK_SIZE', 'SYMBOL_TRADE_TICK_VALUE',
            'SYMBOL_TRADE_TICK_VALUE_LOSS', 'SYMBOL_TRADE_TICK_VALUE_PROFIT', 'SYMBOL_VOLUME', 'SYMBOL_VOLUMEHIGH',
            'SYMBOL_VOLUMELOW', 'SYMBOL_VOLUME_LIMIT', 'SYMBOL_VOLUME_MAX', 'SYMBOL_VOLUME_MIN', 'SYMBOL_VOLUME_STEP',
            'TENKANSEN_LINE', 'TERMINAL_BUILD', 'TERMINAL_CODEPAGE', 'TERMINAL_COMMONDATA_PATH', 'TERMINAL_COMMUNITY_ACCOUNT',
            'TERMINAL_COMMUNITY_BALANCE', 'TERMINAL_COMMUNITY_CONNECTION', 'TERMINAL_COMPANY', 'TERMINAL_CONNECTED',
            'TERMINAL_CPU_CORES', 'TERMINAL_DATA_PATH', 'TERMINAL_DISK_SPACE', 'TERMINAL_DLLS_ALLOWED', 'TERMINAL_EMAIL_ENABLED',
            'TERMINAL_FTP_ENABLED', 'TERMINAL_LANGUAGE', 'TERMINAL_MAXBARS', 'TERMINAL_MEMORY_AVAILABLE', 'TERMINAL_MEMORY_PHYSICAL',
            'TERMINAL_MEMORY_TOTAL', 'TERMINAL_MEMORY_USED', 'TERMINAL_MQID', 'TERMINAL_NAME', 'TERMINAL_NOTIFICATIONS_ENABLED',
            'TERMINAL_OPENCL_SUPPORT', 'TERMINAL_PATH', 'TERMINAL_SCREEN_DPI', 'TERMINAL_TRADE_ALLOWED', 'TERMINAL_X64',
            'THURSDAY', 'TRADE_ACTION_DEAL', 'TRADE_ACTION_MODIFY', 'TRADE_ACTION_PENDING', 'TRADE_ACTION_REMOVE',
            'TRADE_ACTION_SLTP', 'TRADE_RETCODE_CANCEL', 'TRADE_RETCODE_CLIENT_DISABLES_AT', 'TRADE_RETCODE_CONNECTION',
            'TRADE_RETCODE_DONE', 'TRADE_RETCODE_DONE_PARTIAL', 'TRADE_RETCODE_ERROR', 'TRADE_RETCODE_FROZEN', 'TRADE_RETCODE_INVALID',
            'TRADE_RETCODE_INVALID_EXPIRATION', 'TRADE_RETCODE_INVALID_FILL', 'TRADE_RETCODE_INVALID_ORDER', 'TRADE_RETCODE_INVALID_PRICE',
            'TRADE_RETCODE_INVALID_STOPS', 'TRADE_RETCODE_INVALID_VOLUME', 'TRADE_RETCODE_LIMIT_ORDERS', 'TRADE_RETCODE_LIMIT_VOLUME',
            'TRADE_RETCODE_LOCKED', 'TRADE_RETCODE_MARKET_CLOSED', 'TRADE_RETCODE_NO_CHANGES', 'TRADE_RETCODE_NO_MONEY',
            'TRADE_RETCODE_ONLY_REAL', 'TRADE_RETCODE_ORDER_CHANGED', 'TRADE_RETCODE_PLACED', 'TRADE_RETCODE_POSITION_CLOSED',
            'TRADE_RETCODE_PRICE_CHANGED', 'TRADE_RETCODE_PRICE_OFF', 'TRADE_RETCODE_REJECT', 'TRADE_RETCODE_REQUOTE',
            'TRADE_RETCODE_SERVER_DISABLES_AT', 'TRADE_RETCODE_TIMEOUT', 'TRADE_RETCODE_TOO_MANY_REQUESTS', 'TRADE_RETCODE_TRADE_DISABLED',
            'TRADE_TRANSACTION_DEAL_ADD', 'TRADE_TRANSACTION_DEAL_DELETE', 'TRADE_TRANSACTION_DEAL_UPDATE', 'TRADE_TRANSACTION_HISTORY_ADD',
            'TRADE_TRANSACTION_HISTORY_DELETE', 'TRADE_TRANSACTION_HISTORY_UPDATE', 'TRADE_TRANSACTION_ORDER_ADD',
            'TRADE_TRANSACTION_ORDER_DELETE', 'TRADE_TRANSACTION_ORDER_UPDATE', 'TRADE_TRANSACTION_POSITION', 'TRADE_TRANSACTION_REQUEST',
            'TUESDAY', 'TYPE_BOOL', 'TYPE_CHAR', 'TYPE_COLOR', 'TYPE_DATETIME', 'TYPE_DOUBLE', 'TYPE_FLOAT', 'TYPE_INT',
            'TYPE_LONG', 'TYPE_SHORT', 'TYPE_STRING', 'TYPE_UCHAR', 'TYPE_UINT', 'TYPE_ULONG', 'TYPE_USHORT', 'UCHAR_MAX',
            'UINT_MAX', 'ULONG_MAX', 'UPPER_HISTOGRAM', 'UPPER_LINE', 'USHORT_MAX', 'VOLUME_REAL', 'VOLUME_TICK',
            'WEDNESDAY', 'WHOLE_ARRAY', 'WRONG_VALUE', '__DATETIME__', '__DATE__', '__FILE__', '__FUNCSIG__', '__FUNCTION__',
            '__LINE__', '__PATH__', 'clrAliceBlue', 'clrAntiqueWhite', 'clrAqua', 'clrAquamarine', 'clrBeige', 'clrBisque',
            'clrBlack', 'clrBlanchedAlmond', 'clrBlue', 'clrBlueViolet', 'clrBrown', 'clrBurlyWood', 'clrCadetBlue',
            'clrChartreuse', 'clrChocolate', 'clrCoral', 'clrCornflowerBlue', 'clrCornsilk', 'clrCrimson', 'clrDarkBlue',
            'clrDarkGoldenrod', 'clrDarkGray', 'clrDarkGreen', 'clrDarkKhaki', 'clrDarkOliveGreen', 'clrDarkOrange',
            'clrDarkOrchid', 'clrDarkSalmon', 'clrDarkSeaGreen', 'clrDarkSlateBlue', 'clrDarkSlateGray', 'clrDarkTurquoise',
            'clrDarkViolet', 'clrDeepPink', 'clrDeepSkyBlue', 'clrDimGray', 'clrDodgerBlue', 'clrFireBrick', 'clrForestGreen',
            'clrGainsboro', 'clrGold', 'clrGoldenrod', 'clrGray', 'clrGreen', 'clrGreenYellow', 'clrHoneydew', 'clrHotPink',
            'clrIndianRed', 'clrIndigo', 'clrIvory', 'clrKhaki', 'clrLavender', 'clrLavenderBlush', 'clrLawnGreen',
            'clrLemonChiffon', 'clrLightBlue', 'clrLightCoral', 'clrLightCyan', 'clrLightGoldenrod', 'clrLightGray',
            'clrLightGreen', 'clrLightPink', 'clrLightSalmon', 'clrLightSeaGreen', 'clrLightSkyBlue', 'clrLightSlateGray',
            'clrLightSteelBlue', 'clrLightYellow', 'clrLime', 'clrLimeGreen', 'clrLinen', 'clrMagenta', 'clrMaroon',
            'clrMediumAquamarine', 'clrMediumBlue', 'clrMediumOrchid', 'clrMediumPurple', 'clrMediumSeaGreen', 'clrMediumSlateBlue',
            'clrMediumSpringGreen', 'clrMediumTurquoise', 'clrMediumVioletRed', 'clrMidnightBlue', 'clrMintCream',
            'clrMistyRose', 'clrMoccasin', 'clrNONE', 'clrNavajoWhite', 'clrNavy', 'clrOldLace', 'clrOlive', 'clrOliveDrab',
            'clrOrange', 'clrOrangeRed', 'clrOrchid', 'clrPaleGoldenrod', 'clrPaleGreen', 'clrPaleTurquoise', 'clrPaleVioletRed',
            'clrPapayaWhip', 'clrPeachPuff', 'clrPeru', 'clrPink', 'clrPlum', 'clrPowderBlue', 'clrPurple', 'clrRed',
            'clrRosyBrown', 'clrRoyalBlue', 'clrSaddleBrown', 'clrSalmon', 'clrSandyBrown', 'clrSeaGreen', 'clrSeashell',
            'clrSienna', 'clrSilver', 'clrSkyBlue', 'clrSlateBlue', 'clrSlateGray', 'clrSnow', 'clrSpringGreen',
            'clrSteelBlue', 'clrTan', 'clrTeal', 'clrThistle', 'clrTomato', 'clrTurquoise', 'clrViolet', 'clrWheat',
            'clrWhite', 'clrWhiteSmoke', 'clrYellow', 'clrYellowGreen',
        ),
        3 => array(
            '#define', '#else', '#endif', '#ifdef', '#ifndef', '#import', '#include', '#property', 'bool', 'break',
            'case', 'char', 'class', 'color', 'const', 'continue', 'datetime', 'default', 'delete', 'do', 'double',
            'dynamic_cast', 'else', 'enum', 'extern', 'false', 'float', 'for', 'group', 'if', 'input', 'int', 'long',
            'namespace', 'offsetof', 'operator', 'override', 'pack', 'private', 'protected', 'public', 'return',
            'short', 'sizeof', 'static', 'string', 'struct', 'template', 'this', 'true', 'typename', 'uchar', 'uint',
            'ulong', 'union', 'ushort', 'virtual', 'void', 'while',
        ),
        4 => array(
            '_AppliedTo', '_Digits', '_IsX64', '_LastError', '_Period', '_Point', '_RandomSeed', '_StopFlag', '_Symbol',
            '_UninitReason',
        ),
        5 => array(
            'copyright', 'description', 'icon', 'indicator_applied_price', 'indicator_buffers', 'indicator_chart_window',
            'indicator_color', 'indicator_label', 'indicator_level', 'indicator_levelcolor', 'indicator_levelstyle',
            'indicator_levelwidth', 'indicator_maximum', 'indicator_minimum', 'indicator_plots', 'indicator_separate_window',
            'indicator_style', 'indicator_type', 'indicator_width', 'library', 'link', 'optimization_chart_mode',
            'script_show_confirm', 'script_show_inputs', 'stacksize', 'tester_everytick_calculate', 'tester_file',
            'tester_indicator', 'tester_library', 'tester_no_cache', 'tester_set', 'version',
        ),
    ),
    'SYMBOLS' => array(
        0 => array('!', '@', '|', '&', '~', ':', '+', '-', '*', '/', '%', '=', '<', '>'),
    ),
    'CASE_SENSITIVE' => array(
        GESHI_COMMENTS => true,
        1 => true,
        2 => true,
        3 => true,
        4 => true,
        5 => true,
    ),
    'STYLES' => array(
        'KEYWORDS' => array(
            1 => 'color: #8A2BE2;',
            2 => 'color: #FF0000;',
            3 => 'color: #0000FF;',
            4 => 'color: #FF00FF;',
            5 => 'color: #FF0000;',
        ),
        'COMMENTS' => array(
            1 => 'color: #808080;',
            'MULTI' => 'color: #808080;',
        ),
        'ESCAPE_CHAR' => array(),
        'BRACKETS' => array(
            0 => 'color: #000080;',
        ),
        'STRINGS' => array(
            0 => 'color: #008080;'
        ),
        'NUMBERS' => array(
            0 => 'color: #008000;'
        ),
        'METHODS' => array(
            1 => 'color: #000000;',
            2 => 'color: #000000;',
        ),
        'SYMBOLS' => array(
            0 => 'color: #000080;',
        ),
        'REGEXPS' => array(
            1 => 'color: #008080;',
            2 => 'color: #FF0000;',
        ),
        'SCRIPT' => array(),
    ),
    'URLS' => array(
        1 => 'https://www.mql5.com/en/docs/function_indices',
        2 => '',
        3 => '',
        4 => '',
        5 => '',
    ),
    'OOLANG' => true,
    'OBJECT_SPLITTERS' => array(
        1 => '.',
        2 => '::',
    ),
    'REGEXPS' => array(
        1 => array(
            GESHI_SEARCH => '((?>B|D)\'.*?\')',
            GESHI_REPLACE => '\0',
            GESHI_MODIFIERS => '',
            GESHI_BEFORE => '',
            GESHI_AFTER => '',
        ),
        2 => array(
            GESHI_SEARCH => '(indicator_(?>label|color|width|style|type|level)[0-9]+)',
            GESHI_REPLACE => '\0',
            GESHI_MODIFIERS => '',
            GESHI_BEFORE => '',
            GESHI_AFTER => '',
        ),
    ),
    'STRICT_MODE_APPLIES' => GESHI_NEVER,
    'SCRIPT_DELIMITERS' => array(),
    'HIGHLIGHT_STRICT_BLOCK' => array(),
    'TAB_WIDTH' => 3,
);
