<?php
/*************************************************************************************
 * php.php
 * --------
 * Author: Nigel McNie (nigel@geshi.org)
 * Copyright: (c) 2004 Nigel McNie (http://qbnz.com/highlighter/)
 * Release Version: 1.0.8.2
 * Date Started: 2004/06/20
 *
 * PHP language file for GeSHi.
 *
 * CHANGES
 * -------
 * 2008/05/23 (1.0.7.22)
 *  -  Added description of extra language features (SF#1970248)
 * 2004/11/25 (1.0.3)
 *  -  Added support for multiple object splitters
 *  -  Fixed &new problem
 * 2004/10/27 (1.0.2)
 *  -  Added URL support
 *  -  Added extra constants
 * 2004/08/05 (1.0.1)
 *  -  Added support for symbols
 * 2004/07/14 (1.0.0)
 *  -  First Release
 *
 * TODO (updated 2004/07/14)
 * -------------------------
 * * Make sure the last few function I may have missed
 *   (like eval()) are included for highlighting
 * * Split to several files - php4, php5 etc
 *
 *************************************************************************************
 *
 *     This file is part of GeSHi.
 *
 *   GeSHi is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   GeSHi is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with GeSHi; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ************************************************************************************/

$language_data = array(
    'LANG_NAME' => 'PHP',
    'COMMENT_SINGLE' => array(1 => '//', 2 => '#'),
    'COMMENT_MULTI' => array('/*' => '*/'),
    'HARDQUOTE' => array("'", "'"),
    'HARDESCAPE' => array("\'"),
    'COMMENT_REGEXP' => array(
        //Heredoc and Nowdoc syntax
        3 => '/<<<\s*?(\'?)([a-zA-Z0-9]+?)\1[^\n]*?\\n.*\\n\\2(?![a-zA-Z0-9])/siU',
        // phpdoc comments
        4 => '#/\*\*(?![\*\/]).*\*/#sU'
        ),
    'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
    'QUOTEMARKS' => array('"'),
    'ESCAPE_CHAR' => '',
    'ESCAPE_REGEXP' => array(
        //Simple Single Char Escapes
        1 => "#\\\\[nfrtv\$\"\n\\\\]#i",
        //Hexadecimal Char Specs
        2 => "#\\\\x[\da-fA-F]{1,2}#i",
        //Octal Char Specs
        3 => "#\\\\[0-7]{1,3}#",
        //String Parsing of Variable Names
        4 => "#\\$[a-z0-9_]+(?:\\[[a-z0-9_]+\\]|->[a-z0-9_]+)?|(?:\\{\\$|\\$\\{)[a-z0-9_]+(?:\\[('?)[a-z0-9_]*\\1\\]|->[a-z0-9_]+)*\\}#i",
        //Experimental extension supporting cascaded {${$var}} syntax
        5 => "#\$[a-z0-9_]+(?:\[[a-z0-9_]+\]|->[a-z0-9_]+)?|(?:\{\$|\$\{)[a-z0-9_]+(?:\[('?)[a-z0-9_]*\\1\]|->[a-z0-9_]+)*\}|\{\$(?R)\}#i",
        //Format String support in ""-Strings
        6 => "#%(?:%|(?:\d+\\\\\\\$)?\\+?(?:\x20|0|'.)?-?(?:\d+|\\*)?(?:\.\d+)?[bcdefFosuxX])#"
        ),
    'NUMBERS' =>
        GESHI_NUMBER_INT_BASIC |  GESHI_NUMBER_OCT_PREFIX | GESHI_NUMBER_HEX_PREFIX |
        GESHI_NUMBER_FLT_SCI_ZERO,
    'KEYWORDS' => array(
        1 => array(
            'as','break','case','continue','default','do','else','elseif',
            'endfor','endforeach','endif','endswitch','endwhile','for',
            'foreach','if','include','include_once','require','require_once',
            'return','switch','while',

            'echo','print'
            ),
        2 => array(
            '&amp;new','&lt;/script&gt;','&lt;?php','&lt;script language',
            'class','const','declare','extends','function','global','interface',
            'namespace','new','private','public','self','var'
            ),
        3 => array(
            'abs','acos','acosh','addcslashes','addslashes','aggregate',
            'aggregate_methods','aggregate_methods_by_list',
            'aggregate_methods_by_regexp','aggregate_properties',
            'aggregate_properties_by_list','aggregate_properties_by_regexp',
            'aggregation_info','apache_child_terminate','apache_get_version',
            'apache_lookup_uri','apache_note','apache_request_headers',
            'apache_response_headers','apache_setenv','array',
            'array_change_key_case','array_chunk','array_combine',
            'array_count_values','array_diff','array_diff_assoc',
            'array_diff_key','array_diff_uassoc','array_diff_ukey','array_fill',
            'array_filter','array_flip','array_intersect',
            'array_intersect_assoc','array_intersect_key',
            'array_intersect_uassoc','array_intersect_ukey','array_key_exists',
            'array_keys','array_map','array_merge','array_merge_recursive',
            'array_multisort','array_pad','array_pop','array_product',
            'array_push','array_rand','array_reduce','array_reverse',
            'array_search','array_shift','array_slice','array_splice',
            'array_sum','array_udiff','array_udiff_assoc','array_udiff_uassoc',
            'array_uintersect','array_uintersect_assoc',
            'array_uintersect_uassoc','array_unique','array_unshift',
            'array_values','array_walk','array_walk_recursive','arsort','asin',
            'asinh','asort','assert','assert_options','atan','atan2','atanh',
            'base_convert','base64_decode','base64_encode','basename','bcadd',
            'bccomp','bcdiv','bcmod','bcmul','bcpow','bcpowmod','bcscale',
            'bcsqrt','bcsub','bin2hex','bind_textdomain_codeset','bindec',
            'bindtextdomain','bzclose','bzcompress','bzdecompress','bzerrno',
            'bzerror','bzerrstr','bzflush','bzopen','bzread','bzwrite',
            'cal_days_in_month','cal_from_jd','cal_info','cal_to_jd',
            'call_user_func','call_user_func_array','call_user_method',
            'call_user_method_array','ceil','chdir','checkdate','checkdnsrr',
            'chgrp','chmod','chop','chown','chr','chunk_split','class_exists',
            'class_implements','class_parents','clearstatcache','closedir',
            'closelog','com_create_guid','com_event_sink',
            'com_get_active_object','com_load_typelib','com_message_pump',
            'com_print_typeinfo','compact','connection_aborted',
            'connection_status','constant','convert_cyr_string',
            'convert_uudecode','convert_uuencode','copy','cos','cosh','count',
            'count_chars','crc32','create_function','crypt','ctype_alnum',
            'ctype_alpha','ctype_cntrl','ctype_digit','ctype_graph',
            'ctype_lower','ctype_print','ctype_punct','ctype_space',
            'ctype_upper','ctype_xdigit','curl_close','curl_copy_handle',
            'curl_errno','curl_error','curl_exec','curl_getinfo','curl_init',
            'curl_multi_add_handle','curl_multi_close','curl_multi_exec',
            'curl_multi_getcontent','curl_multi_info_read','curl_multi_init',
            'curl_multi_remove_handle','curl_multi_select','curl_setopt',
            'curl_version','current','date','date_default_timezone_get',
            'date_default_timezone_set','date_sunrise','date_sunset',
            'dba_close','dba_delete','dba_exists','dba_fetch','dba_firstkey',
            'dba_handlers','dba_insert','dba_key_split','dba_list',
            'dba_nextkey','dba_open','dba_optimize','dba_popen','dba_replace',
            'dba_sync','dbg_get_all_contexts','dbg_get_all_module_names',
            'dbg_get_all_source_lines','dbg_get_context_name',
            'dbg_get_module_name','dbg_get_profiler_results',
            'dbg_get_source_context','dcgettext','dcngettext','deaggregate',
            'debug_backtrace','debug_zval_dump','debugbreak','decbin','dechex',
            'decoct','define','define_syslog_variables','defined','deg2rad',
            'dgettext','die','dir','dirname','disk_free_space',
            'disk_total_space','diskfreespace','dl','dngettext',
            'dom_import_simplexml','doubleval','each','easter_date',
            'easter_days','empty','end','ereg','ereg_replace','eregi',
            'eregi_replace','error_log','error_reporting','escapeshellarg',
            'escapeshellcmd','eval','exec','exif_imagetype','exif_read_data',
            'exif_tagname','exif_thumbnail','exit','exp','explode','expm1',
            'extension_loaded','extract','ezmlm_hash','fclose',
            'fdf_add_doc_javascript','fdf_add_template','fdf_close',
            'fdf_create','fdf_enum_values','fdf_errno','fdf_error','fdf_get_ap',
            'fdf_get_attachment','fdf_get_encoding','fdf_get_file',
            'fdf_get_flags','fdf_get_opt','fdf_get_status','fdf_get_value',
            'fdf_get_version','fdf_header','fdf_next_field_name','fdf_open',
            'fdf_open_string','fdf_remove_item','fdf_save','fdf_save_string',
            'fdf_set_ap','fdf_set_encoding','fdf_set_file','fdf_set_flags',
            'fdf_set_javascript_action','fdf_set_on_import_javascript',
            'fdf_set_opt','fdf_set_status','fdf_set_submit_form_action',
            'fdf_set_target_frame','fdf_set_value','fdf_set_version','feof',
            'fflush','fgetc','fgetcsv','fgets','fgetss','file','file_exists',
            'file_get_contents','file_put_contents','fileatime','filectime',
            'filegroup','fileinode','filemtime','fileowner','fileperms',
            'filepro','filepro_fieldcount','filepro_fieldname',
            'filepro_fieldtype','filepro_fieldwidth','filepro_retrieve',
            'filepro_rowcount','filesize','filetype','floatval','flock','floor',
            'flush','fmod','fnmatch','fopen','fpassthru','fprintf','fputcsv',
            'fputs','fread','frenchtojd','fscanf','fseek','fsockopen','fstat',
            'ftell','ftok','ftp_alloc','ftp_cdup','ftp_chdir','ftp_chmod',
            'ftp_close','ftp_connect','ftp_delete','ftp_exec','ftp_fget',
            'ftp_fput','ftp_get','ftp_get_option','ftp_login','ftp_mdtm',
            'ftp_mkdir','ftp_nb_continue','ftp_nb_fget','ftp_nb_fput',
            'ftp_nb_get','ftp_nb_put','ftp_nlist','ftp_pasv','ftp_put',
            'ftp_pwd','ftp_quit','ftp_raw','ftp_rawlist','ftp_rename',
            'ftp_rmdir','ftp_set_option','ftp_site','ftp_size',
            'ftp_ssl_connect','ftp_systype','ftruncate','func_get_arg',
            'func_get_args','func_num_args','function_exists','fwrite',
            'gd_info','get_browser','get_cfg_var','get_class',
            'get_class_methods','get_class_vars','get_current_user',
            'get_declared_classes','get_defined_constants',
            'get_defined_functions','get_defined_vars','get_extension_funcs',
            'get_headers','get_html_translation_table','get_include_path',
            'get_included_files','get_loaded_extensions','get_magic_quotes_gpc',
            'get_magic_quotes_runtime','get_meta_tags','get_object_vars',
            'get_parent_class','get_required_files','get_resource_type',
            'getallheaders','getcwd','getdate','getenv','gethostbyaddr',
            'gethostbyname','gethostbynamel','getimagesize','getlastmod',
            'getmxrr','getmygid','getmyinode','getmypid','getmyuid','getopt',
            'getprotobyname','getprotobynumber','getrandmax','getrusage',
            'getservbyname','getservbyport','gettext','gettimeofday','gettype',
            'glob','gmdate','gmmktime','gmp_abs','gmp_add','gmp_and',
            'gmp_clrbit','gmp_cmp','gmp_com','gmp_div','gmp_div_q','gmp_div_qr',
            'gmp_div_r','gmp_divexact','gmp_fact','gmp_gcd','gmp_gcdext',
            'gmp_hamdist','gmp_init','gmp_intval','gmp_invert','gmp_jacobi',
            'gmp_legendre','gmp_mod','gmp_mul','gmp_neg','gmp_nextprime',
            'gmp_or','gmp_perfect_square','gmp_popcount','gmp_pow','gmp_powm',
            'gmp_prob_prime','gmp_random','gmp_scan0','gmp_scan1','gmp_setbit',
            'gmp_sign','gmp_sqrt','gmp_sqrtrem','gmp_strval','gmp_sub',
            'gmp_testbit','gmp_xor','gmstrftime','gregoriantojd','gzclose',
            'gzcompress','gzdeflate','gzencode','gzeof','gzfile','gzgetc',
            'gzgets','gzgetss','gzinflate','gzopen','gzpassthru','gzputs',
            'gzread','gzrewind','gzseek','gztell','gzuncompress','gzwrite',
            'hash','hash_algos','hash_file','hash_final','hash_hmac',
            'hash_hmac_file','hash_init','hash_update','hash_update_file',
            'hash_update_stream','header','headers_list','headers_sent',
            'hebrev','hebrevc','hexdec','highlight_file','highlight_string',
            'html_entity_decode','htmlentities','htmlspecialchars',
            'htmlspecialchars_decode','http_build_query','hypot','i18n_convert',
            'i18n_discover_encoding','i18n_http_input','i18n_http_output',
            'i18n_internal_encoding','i18n_ja_jp_hantozen',
            'i18n_mime_header_decode','i18n_mime_header_encode','iconv',
            'iconv_get_encoding','iconv_mime_decode',
            'iconv_mime_decode_headers','iconv_mime_encode',
            'iconv_set_encoding','iconv_strlen','iconv_strpos','iconv_strrpos',
            'iconv_substr','idate','ignore_user_abort',
            'image_type_to_mime_type','image2wbmp','imagealphablending',
            'imageantialias','imagearc','imagechar','imagecharup',
            'imagecolorallocate','imagecolorallocatealpha','imagecolorat',
            'imagecolorclosest','imagecolorclosestalpha','imagecolordeallocate',
            'imagecolorexact','imagecolorexactalpha','imagecolormatch',
            'imagecolorresolve','imagecolorresolvealpha','imagecolorset',
            'imagecolorsforindex','imagecolorstotal','imagecolortransparent',
            'imageconvolution','imagecopy','imagecopymerge',
            'imagecopymergegray','imagecopyresampled','imagecopyresized',
            'imagecreate','imagecreatefromgd','imagecreatefromgd2',
            'imagecreatefromgd2part','imagecreatefromgif','imagecreatefromjpeg',
            'imagecreatefrompng','imagecreatefromstring','imagecreatefromwbmp',
            'imagecreatefromxbm','imagecreatetruecolor','imagedashedline',
            'imagedestroy','imageellipse','imagefill','imagefilledarc',
            'imagefilledellipse','imagefilledpolygon','imagefilledrectangle',
            'imagefilltoborder','imagefilter','imagefontheight',
            'imagefontwidth','imageftbbox','imagefttext','imagegammacorrect',
            'imagegd','imagegd2','imagegif','imageinterlace','imageistruecolor',
            'imagejpeg','imagelayereffect','imageline','imageloadfont',
            'imagepalettecopy','imagepng','imagepolygon','imagepsbbox',
            'imagepsencodefont','imagepsextendfont','imagepsfreefont',
            'imagepsloadfont','imagepsslantfont','imagepstext','imagerectangle',
            'imagerotate','imagesavealpha','imagesetbrush','imagesetpixel',
            'imagesetstyle','imagesetthickness','imagesettile','imagestring',
            'imagestringup','imagesx','imagesy','imagetruecolortopalette',
            'imagettfbbox','imagettftext','imagetypes','imagewbmp','imagexbm',
            'implode','import_request_variables','in_array','ini_alter',
            'ini_get','ini_get_all','ini_restore','ini_set','intval','ip2long',
            'iptcembed','iptcparse','is_a','is_array','is_bool','is_callable',
            'is_dir','is_double','is_executable','is_file','is_finite',
            'is_float','is_infinite','is_int','is_integer','is_link','is_long',
            'is_nan','is_null','is_numeric','is_object','is_readable','is_real',
            'is_resource','is_scalar','is_string','is_subclass_of',
            'is_uploaded_file','is_writable','is_writeable','isset',
            'iterator_count','iterator_to_array','jddayofweek','jdmonthname',
            'jdtofrench','jdtogregorian','jdtojewish','jdtojulian','jdtounix',
            'jewishtojd','join','jpeg2wbmp','juliantojd','key','key_exists',
            'krsort','ksort','lcg_value','levenshtein','libxml_clear_errors',
            'libxml_get_errors','libxml_get_last_error',
            'libxml_set_streams_context','libxml_use_internal_errors','link',
            'linkinfo','list','localeconv','localtime','log','log10','log1p',
            'long2ip','lstat','ltrim','magic_quotes_runtime','mail','max',
            'mb_convert_case','mb_convert_encoding','mb_convert_kana',
            'mb_convert_variables','mb_decode_mimeheader',
            'mb_decode_numericentity','mb_detect_encoding','mb_detect_order',
            'mb_encode_mimeheader','mb_encode_numericentity','mb_ereg',
            'mb_ereg_match','mb_ereg_replace','mb_ereg_search',
            'mb_ereg_search_getpos','mb_ereg_search_getregs',
            'mb_ereg_search_init','mb_ereg_search_pos','mb_ereg_search_regs',
            'mb_ereg_search_setpos','mb_eregi','mb_eregi_replace','mb_get_info',
            'mb_http_input','mb_http_output','mb_internal_encoding',
            'mb_language','mb_output_handler','mb_parse_str',
            'mb_preferred_mime_name','mb_regex_encoding','mb_regex_set_options',
            'mb_send_mail','mb_split','mb_strcut','mb_strimwidth','mb_strlen',
            'mb_strpos','mb_strrpos','mb_strtolower','mb_strtoupper',
            'mb_strwidth','mb_substitute_character','mb_substr',
            'mb_substr_count','mbereg','mbereg_match','mbereg_replace',
            'mbereg_search','mbereg_search_getpos','mbereg_search_getregs',
            'mbereg_search_init','mbereg_search_pos','mbereg_search_regs',
            'mbereg_search_setpos','mberegi','mberegi_replace',
            'mbregex_encoding','mbsplit','mbstrcut','mbstrlen','mbstrpos',
            'mbstrrpos','mbsubstr','md5','md5_file','memory_get_usage',
            'metaphone','method_exists','mhash','mhash_count',
            'mhash_get_block_size','mhash_get_hash_name','mhash_keygen_s2k',
            'microtime','mime_content_type','min','ming_keypress',
            'ming_setcubicthreshold','ming_setscale','ming_useconstants',
            'ming_useswfversion','mkdir','mktime','money_format',
            'move_uploaded_file','msql','msql_affected_rows','msql_close',
            'msql_connect','msql_create_db','msql_createdb','msql_data_seek',
            'msql_db_query','msql_dbname','msql_drop_db','msql_dropdb',
            'msql_error','msql_fetch_array','msql_fetch_field',
            'msql_fetch_object','msql_fetch_row','msql_field_flags',
            'msql_field_len','msql_field_name','msql_field_seek',
            'msql_field_table','msql_field_type','msql_fieldflags',
            'msql_fieldlen','msql_fieldname','msql_fieldtable','msql_fieldtype',
            'msql_free_result','msql_freeresult','msql_list_dbs',
            'msql_list_fields','msql_list_tables','msql_listdbs',
            'msql_listfields','msql_listtables','msql_num_fields',
            'msql_num_rows','msql_numfields','msql_numrows','msql_pconnect',
            'msql_query','msql_regcase','msql_result','msql_select_db',
            'msql_selectdb','msql_tablename','mssql_bind','mssql_close',
            'mssql_connect','mssql_data_seek','mssql_execute',
            'mssql_fetch_array','mssql_fetch_assoc','mssql_fetch_batch',
            'mssql_fetch_field','mssql_fetch_object','mssql_fetch_row',
            'mssql_field_length','mssql_field_name','mssql_field_seek',
            'mssql_field_type','mssql_free_result','mssql_free_statement',
            'mssql_get_last_message','mssql_guid_string','mssql_init',
            'mssql_min_error_severity','mssql_min_message_severity',
            'mssql_next_result','mssql_num_fields','mssql_num_rows',
            'mssql_pconnect','mssql_query','mssql_result','mssql_rows_affected',
            'mssql_select_db','mt_getrandmax','mt_rand','mt_srand','mysql',
            'mysql_affected_rows','mysql_client_encoding','mysql_close',
            'mysql_connect','mysql_create_db','mysql_createdb',
            'mysql_data_seek','mysql_db_name','mysql_db_query','mysql_dbname',
            'mysql_drop_db','mysql_dropdb','mysql_errno','mysql_error',
            'mysql_escape_string','mysql_fetch_array','mysql_fetch_assoc',
            'mysql_fetch_field','mysql_fetch_lengths','mysql_fetch_object',
            'mysql_fetch_row','mysql_field_flags','mysql_field_len',
            'mysql_field_name','mysql_field_seek','mysql_field_table',
            'mysql_field_type','mysql_fieldflags','mysql_fieldlen',
            'mysql_fieldname','mysql_fieldtable','mysql_fieldtype',
            'mysql_free_result','mysql_freeresult','mysql_get_client_info',
            'mysql_get_host_info','mysql_get_proto_info',
            'mysql_get_server_info','mysql_info','mysql_insert_id',
            'mysql_list_dbs','mysql_list_fields','mysql_list_processes',
            'mysql_list_tables','mysql_listdbs','mysql_listfields',
            'mysql_listtables','mysql_num_fields','mysql_num_rows',
            'mysql_numfields','mysql_numrows','mysql_pconnect','mysql_ping',
            'mysql_query','mysql_real_escape_string','mysql_result',
            'mysql_select_db','mysql_selectdb','mysql_stat','mysql_table_name',
            'mysql_tablename','mysql_thread_id','mysql_unbuffered_query',
            'natcasesort','natsort','next','ngettext','nl_langinfo','nl2br',
            'number_format','ob_clean','ob_end_clean','ob_end_flush','ob_flush',
            'ob_get_clean','ob_get_contents','ob_get_flush','ob_get_length',
            'ob_get_level','ob_get_status','ob_gzhandler','ob_iconv_handler',
            'ob_implicit_flush','ob_list_handlers','ob_start','ob_tidyhandler',
            'octdec','odbc_autocommit','odbc_binmode','odbc_close',
            'odbc_close_all','odbc_columnprivileges','odbc_columns',
            'odbc_commit','odbc_connect','odbc_cursor','odbc_data_source',
            'odbc_do','odbc_error','odbc_errormsg','odbc_exec','odbc_execute',
            'odbc_fetch_array','odbc_fetch_into','odbc_fetch_object',
            'odbc_fetch_row','odbc_field_len','odbc_field_name',
            'odbc_field_num','odbc_field_precision','odbc_field_scale',
            'odbc_field_type','odbc_foreignkeys','odbc_free_result',
            'odbc_gettypeinfo','odbc_longreadlen','odbc_next_result',
            'odbc_num_fields','odbc_num_rows','odbc_pconnect','odbc_prepare',
            'odbc_primarykeys','odbc_procedurecolumns','odbc_procedures',
            'odbc_result','odbc_result_all','odbc_rollback','odbc_setoption',
            'odbc_specialcolumns','odbc_statistics','odbc_tableprivileges',
            'odbc_tables','opendir','openlog','openssl_csr_export',
            'openssl_csr_export_to_file','openssl_csr_new','openssl_csr_sign',
            'openssl_error_string','openssl_free_key','openssl_get_privatekey',
            'openssl_get_publickey','openssl_open','openssl_pkcs7_decrypt',
            'openssl_pkcs7_encrypt','openssl_pkcs7_sign','openssl_pkcs7_verify',
            'openssl_pkey_export','openssl_pkey_export_to_file',
            'openssl_pkey_free','openssl_pkey_get_details',
            'openssl_pkey_get_private','openssl_pkey_get_public',
            'openssl_pkey_new','openssl_private_decrypt',
            'openssl_private_encrypt','openssl_public_decrypt',
            'openssl_public_encrypt','openssl_seal','openssl_sign',
            'openssl_verify','openssl_x509_check_private_key',
            'openssl_x509_checkpurpose','openssl_x509_export',
            'openssl_x509_export_to_file','openssl_x509_free',
            'openssl_x509_parse','openssl_x509_read','ord',
            'output_add_rewrite_var','output_reset_rewrite_vars',
            'outputdebugstring','overload','pack','parse_ini_file','parse_str',
            'parse_url','passthru','pathinfo','pclose','pfsockopen',
            'pg_affected_rows','pg_cancel_query','pg_client_encoding',
            'pg_clientencoding','pg_close','pg_cmdtuples','pg_connect',
            'pg_connection_busy','pg_connection_reset','pg_connection_status',
            'pg_convert','pg_copy_from','pg_copy_to','pg_dbname','pg_delete',
            'pg_end_copy','pg_errormessage','pg_escape_bytea',
            'pg_escape_string','pg_exec','pg_execute','pg_fetch_all',
            'pg_fetch_all_columns','pg_fetch_array','pg_fetch_assoc',
            'pg_fetch_object','pg_fetch_result','pg_fetch_row',
            'pg_field_is_null','pg_field_name','pg_field_num','pg_field_prtlen',
            'pg_field_size','pg_field_type','pg_field_type_oid',
            'pg_fieldisnull','pg_fieldname','pg_fieldnum','pg_fieldprtlen',
            'pg_fieldsize','pg_fieldtype','pg_free_result','pg_freeresult',
            'pg_get_notify','pg_get_pid','pg_get_result','pg_getlastoid',
            'pg_host','pg_insert','pg_last_error','pg_last_notice',
            'pg_last_oid','pg_lo_close','pg_lo_create','pg_lo_export',
            'pg_lo_import','pg_lo_open','pg_lo_read','pg_lo_read_all',
            'pg_lo_seek','pg_lo_tell','pg_lo_unlink','pg_lo_write','pg_loclose',
            'pg_locreate','pg_loexport','pg_loimport','pg_loopen','pg_loread',
            'pg_loreadall','pg_lounlink','pg_lowrite','pg_meta_data',
            'pg_num_fields','pg_num_rows','pg_numfields','pg_numrows',
            'pg_options','pg_parameter_status','pg_pconnect','pg_ping',
            'pg_port','pg_prepare','pg_put_line','pg_query','pg_query_params',
            'pg_result','pg_result_error','pg_result_error_field',
            'pg_result_seek','pg_result_status','pg_select','pg_send_execute',
            'pg_send_prepare','pg_send_query','pg_send_query_params',
            'pg_set_client_encoding','pg_set_error_verbosity',
            'pg_setclientencoding','pg_trace','pg_transaction_status','pg_tty',
            'pg_unescape_bytea','pg_untrace','pg_update','pg_version',
            'php_egg_logo_guid','php_ini_scanned_files','php_logo_guid',
            'php_real_logo_guid','php_sapi_name','php_strip_whitespace',
            'php_uname','phpcredits','phpinfo','phpversion','pi','png2wbmp',
            'popen','pos','posix_ctermid','posix_errno','posix_get_last_error',
            'posix_getcwd','posix_getegid','posix_geteuid','posix_getgid',
            'posix_getgrgid','posix_getgrnam','posix_getgroups',
            'posix_getlogin','posix_getpgid','posix_getpgrp','posix_getpid',
            'posix_getppid','posix_getpwnam','posix_getpwuid','posix_getrlimit',
            'posix_getsid','posix_getuid','posix_isatty','posix_kill',
            'posix_mkfifo','posix_setegid','posix_seteuid','posix_setgid',
            'posix_setpgid','posix_setsid','posix_setuid','posix_strerror',
            'posix_times','posix_ttyname','posix_uname','pow','preg_grep',
            'preg_match','preg_match_all','preg_quote','preg_replace',
            'preg_replace_callback','preg_split','prev','print_r','printf',
            'proc_close','proc_get_status','proc_open','proc_terminate',
            'putenv','quoted_printable_decode','quotemeta','rad2deg','rand',
            'range','rawurldecode','rawurlencode','read_exif_data','readdir',
            'readfile','readgzfile','readlink','realpath',
            'register_shutdown_function','register_tick_function','rename',
            'reset','restore_error_handler','restore_include_path','rewind',
            'rewinddir','rmdir','round','rsort','rtrim','scandir','sem_acquire',
            'sem_get','sem_release','sem_remove','serialize',
            'session_cache_expire','session_cache_limiter','session_commit',
            'session_decode','session_destroy','session_encode',
            'session_get_cookie_params','session_id','session_is_registered',
            'session_module_name','session_name','session_regenerate_id',
            'session_register','session_save_path','session_set_cookie_params',
            'session_set_save_handler','session_start','session_unregister',
            'session_unset','session_write_close','set_error_handler',
            'set_file_buffer','set_include_path','set_magic_quotes_runtime',
            'set_socket_blocking','set_time_limit','setcookie','setlocale',
            'setrawcookie','settype','sha1','sha1_file','shell_exec',
            'shm_attach','shm_detach','shm_get_var','shm_put_var','shm_remove',
            'shm_remove_var','shmop_close','shmop_delete','shmop_open',
            'shmop_read','shmop_size','shmop_write','show_source','shuffle',
            'similar_text','simplexml_import_dom','simplexml_load_file',
            'simplexml_load_string','sin','sinh','sizeof','sleep',
            'socket_accept','socket_bind','socket_clear_error','socket_close',
            'socket_connect','socket_create','socket_create_listen',
            'socket_create_pair','socket_get_option','socket_get_status',
            'socket_getopt','socket_getpeername','socket_getsockname',
            'socket_iovec_add','socket_iovec_alloc','socket_iovec_delete',
            'socket_iovec_fetch','socket_iovec_free','socket_iovec_set',
            'socket_last_error','socket_listen','socket_read','socket_readv',
            'socket_recv','socket_recvfrom','socket_recvmsg','socket_select',
            'socket_send','socket_sendmsg','socket_sendto','socket_set_block',
            'socket_set_blocking','socket_set_nonblock','socket_set_option',
            'socket_set_timeout','socket_setopt','socket_shutdown',
            'socket_strerror','socket_write','socket_writev','sort','soundex',
            'spl_autoload','spl_autoload_call','spl_autoload_extensions',
            'spl_autoload_functions','spl_autoload_register',
            'spl_autoload_unregister','spl_classes','split','spliti','sprintf',
            'sql_regcase','sqrt','srand','sscanf','stat','str_ireplace',
            'str_pad','str_repeat','str_replace','str_rot13','str_shuffle',
            'str_split','str_word_count','strcasecmp','strchr','strcmp',
            'strcoll','strcspn','stream_bucket_append',
            'stream_bucket_make_writeable','stream_bucket_new',
            'stream_bucket_prepend','stream_context_create',
            'stream_context_get_default','stream_context_get_options',
            'stream_context_set_default','stream_context_set_option',
            'stream_context_set_params','stream_copy_to_stream',
            'stream_encoding','stream_filter_append','stream_filter_prepend',
            'stream_filter_register','stream_filter_remove',
            'stream_get_contents','stream_get_filters','stream_get_line',
            'stream_get_meta_data','stream_get_transports',
            'stream_get_wrappers','stream_notification_callback',
            'stream_register_wrapper','stream_resolve_include_path',
            'stream_select','stream_set_blocking','stream_set_timeout',
            'stream_set_write_buffer','stream_socket_accept',
            'stream_socket_client','stream_socket_enable_crypto',
            'stream_socket_get_name','stream_socket_pair',
            'stream_socket_recvfrom','stream_socket_sendto',
            'stream_socket_server','stream_socket_shutdown',
            'stream_supports_lock','stream_wrapper_register',
            'stream_wrapper_restore','stream_wrapper_unregister','strftime',
            'strip_tags','stripcslashes','stripos','stripslashes','stristr',
            'strlen','strnatcasecmp','strnatcmp','strncasecmp','strncmp',
            'strpbrk','strpos','strrchr','strrev','strripos','strrpos','strspn',
            'strstr','strtok','strtolower','strtotime','strtoupper','strtr',
            'strval','substr','substr_compare','substr_count','substr_replace',
            'symlink','syslog','system','tan','tanh','tempnam','textdomain',
            'tidy_access_count','tidy_clean_repair','tidy_config_count',
            'tidy_diagnose','tidy_error_count','tidy_get_body',
            'tidy_get_config','tidy_get_error_buffer','tidy_get_head',
            'tidy_get_html','tidy_get_html_ver','tidy_get_output',
            'tidy_get_release','tidy_get_root','tidy_get_status','tidy_getopt',
            'tidy_is_xhtml','tidy_is_xml','tidy_parse_file','tidy_parse_string',
            'tidy_repair_file','tidy_repair_string','tidy_warning_count','time',
            'tmpfile','token_get_all','token_name','touch','trigger_error',
            'trim','uasort','ucfirst','ucwords','uksort','umask','uniqid',
            'unixtojd','unlink','unpack','unregister_tick_function',
            'unserialize','unset','urldecode','urlencode','user_error','usleep',
            'usort','utf8_decode','utf8_encode','var_dump','var_export',
            'variant_abs','variant_add','variant_and','variant_cast',
            'variant_cat','variant_cmp','variant_date_from_timestamp',
            'variant_date_to_timestamp','variant_div','variant_eqv',
            'variant_fix','variant_get_type','variant_idiv','variant_imp',
            'variant_int','variant_mod','variant_mul','variant_neg',
            'variant_not','variant_or','variant_pow','variant_round',
            'variant_set','variant_set_type','variant_sub','variant_xor',
            'version_compare','vfprintf','virtual','vprintf','vsprintf',
            'wddx_add_vars','wddx_deserialize','wddx_packet_end',
            'wddx_packet_start','wddx_serialize_value','wddx_serialize_vars',
            'wordwrap','xml_error_string','xml_get_current_byte_index',
            'xml_get_current_column_number','xml_get_current_line_number',
            'xml_get_error_code','xml_parse','xml_parse_into_struct',
            'xml_parser_create','xml_parser_create_ns','xml_parser_free',
            'xml_parser_get_option','xml_parser_set_option',
            'xml_set_character_data_handler','xml_set_default_handler',
            'xml_set_element_handler','xml_set_end_namespace_decl_handler',
            'xml_set_external_entity_ref_handler',
            'xml_set_notation_decl_handler','xml_set_object',
            'xml_set_processing_instruction_handler',
            'xml_set_start_namespace_decl_handler',
            'xml_set_unparsed_entity_decl_handler','xmlrpc_decode',
            'xmlrpc_decode_request','xmlrpc_encode','xmlrpc_encode_request',
            'xmlrpc_get_type','xmlrpc_is_fault',
            'xmlrpc_parse_method_descriptions',
            'xmlrpc_server_add_introspection_data','xmlrpc_server_call_method',
            'xmlrpc_server_create','xmlrpc_server_destroy',
            'xmlrpc_server_register_introspection_callback',
            'xmlrpc_server_register_method','xmlrpc_set_type',
            'xmlwriter_end_attribute','xmlwriter_end_cdata',
            'xmlwriter_end_comment','xmlwriter_end_document',
            'xmlwriter_end_dtd','xmlwriter_end_dtd_attlist',
            'xmlwriter_end_dtd_element','xmlwriter_end_element',
            'xmlwriter_end_pi','xmlwriter_flush','xmlwriter_open_memory',
            'xmlwriter_open_uri','xmlwriter_output_memory',
            'xmlwriter_set_indent','xmlwriter_set_indent_string',
            'xmlwriter_start_attribute','xmlwriter_start_attribute_ns',
            'xmlwriter_start_cdata','xmlwriter_start_comment',
            'xmlwriter_start_document','xmlwriter_start_dtd',
            'xmlwriter_start_dtd_attlist','xmlwriter_start_dtd_element',
            'xmlwriter_start_element','xmlwriter_start_element_ns',
            'xmlwriter_start_pi','xmlwriter_text','xmlwriter_write_attribute',
            'xmlwriter_write_attribute_ns','xmlwriter_write_cdata',
            'xmlwriter_write_comment','xmlwriter_write_dtd',
            'xmlwriter_write_dtd_attlist','xmlwriter_write_dtd_element',
            'xmlwriter_write_element','xmlwriter_write_element_ns',
            'xmlwriter_write_pi','yp_all','yp_cat','yp_err_string','yp_errno',
            'yp_first','yp_get_default_domain','yp_master','yp_match','yp_next',
            'yp_order','zend_logo_guid','zend_version','zlib_get_coding_type'
            ),
        4 => array(
            'DEFAULT_INCLUDE_PATH', 'DIRECTORY_SEPARATOR', 'E_ALL',
            'E_COMPILE_ERROR', 'E_COMPILE_WARNING', 'E_CORE_ERROR',
            'E_CORE_WARNING', 'E_ERROR', 'E_NOTICE', 'E_PARSE', 'E_STRICT',
            'E_USER_ERROR', 'E_USER_NOTICE', 'E_USER_WARNING', 'E_WARNING',
            'ENT_COMPAT','ENT_QUOTES','ENT_NOQUOTES',
            'false', 'null', 'PEAR_EXTENSION_DIR', 'PEAR_INSTALL_DIR',
            'PHP_BINDIR', 'PHP_CONFIG_FILE_PATH', 'PHP_DATADIR',
            'PHP_EXTENSION_DIR', 'PHP_LIBDIR',
            'PHP_LOCALSTATEDIR', 'PHP_OS',
            'PHP_OUTPUT_HANDLER_CONT', 'PHP_OUTPUT_HANDLER_END',
            'PHP_OUTPUT_HANDLER_START', 'PHP_SYSCONFDIR',
            'PHP_VERSION', 'true', '__CLASS__', '__FILE__', '__FUNCTION__',
            '__LINE__', '__METHOD__'
            )
        ),
    'SYMBOLS' => array(
        1 => array(
            '<%', '<%=', '%>', '<?', '<?=', '?>'
            ),
        0 => array(
            '(', ')', '[', ']', '{', '}',
            '!', '@', '%', '&', '|', '/',
            '<', '>',
            '=', '-', '+', '*',
            '.', ':', ',', ';'
            )
        ),
    'CASE_SENSITIVE' => array(
        GESHI_COMMENTS => false,
        1 => false,
        2 => false,
        3 => false,
        4 => false
        ),
    'STYLES' => array(
        'KEYWORDS' => array(
            1 => 'color: #b1b100;',
            2 => 'color: #000000; font-weight: bold;',
            3 => 'color: #990000;',
            4 => 'color: #009900; font-weight: bold;'
            ),
        'COMMENTS' => array(
            1 => 'color: #666666; font-style: italic;',
            2 => 'color: #666666; font-style: italic;',
            3 => 'color: #0000cc; font-style: italic;',
            4 => 'color: #009933; font-style: italic;',
            'MULTI' => 'color: #666666; font-style: italic;'
            ),
        'ESCAPE_CHAR' => array(
            0 => 'color: #000099; font-weight: bold;',
            1 => 'color: #000099; font-weight: bold;',
            2 => 'color: #660099; font-weight: bold;',
            3 => 'color: #660099; font-weight: bold;',
            4 => 'color: #006699; font-weight: bold;',
            5 => 'color: #006699; font-weight: bold; font-style: italic;',
            6 => 'color: #009933; font-weight: bold;',
            'HARD' => 'color: #000099; font-weight: bold;'
            ),
        'BRACKETS' => array(
            0 => 'color: #009900;'
            ),
        'STRINGS' => array(
            0 => 'color: #0000ff;',
            'HARD' => 'color: #0000ff;'
            ),
        'NUMBERS' => array(
            0 => 'color: #cc66cc;',
            GESHI_NUMBER_OCT_PREFIX => 'color: #208080;',
            GESHI_NUMBER_HEX_PREFIX => 'color: #208080;',
            GESHI_NUMBER_FLT_SCI_ZERO => 'color:#800080;',
            ),
        'METHODS' => array(
            1 => 'color: #004000;',
            2 => 'color: #004000;'
            ),
        'SYMBOLS' => array(
            0 => 'color: #339933;',
            1 => 'color: #000000; font-weight: bold;'
            ),
        'REGEXPS' => array(
            0 => 'color: #000088;'
            ),
        'SCRIPT' => array(
            0 => '',
            1 => '',
            2 => '',
            3 => '',
            4 => '',
            5 => ''
            )
        ),
    'URLS' => array(
        1 => '',
        2 => '',
        3 => 'http://www.php.net/{FNAMEL}',
        4 => ''
        ),
    'OOLANG' => true,
    'OBJECT_SPLITTERS' => array(
        1 => '-&gt;',
        2 => '::'
        ),
    'REGEXPS' => array(
        //Variables
        0 => "[\\$]{1,2}[a-zA-Z_][a-zA-Z0-9_]*"
        ),
    'STRICT_MODE_APPLIES' => GESHI_MAYBE,
    'SCRIPT_DELIMITERS' => array(
        0 => array(
            '<?php' => '?>'
            ),
        1 => array(
            '<?' => '?>'
            ),
        2 => array(
            '<%' => '%>'
            ),
        3 => array(
            '<script language="php">' => '</script>'
            ),
        4 => "/(<\?(?:php)?)(?:'(?:[^'\\\\]|\\\\.)*?'|\"(?:[^\"\\\\]|\\\\.)*?\"|\/\*(?!\*\/).*?\*\/|.)*?(\?>|\Z)/sm",
        5 => "/(<%)(?:'(?:[^'\\\\]|\\\\.)*?'|\"(?:[^\"\\\\]|\\\\.)*?\"|\/\*(?!\*\/).*?\*\/|.)*?(%>|\Z)/sm"
        ),
    'HIGHLIGHT_STRICT_BLOCK' => array(
        0 => true,
        1 => true,
        2 => true,
        3 => true,
        4 => true,
        5 => true
        ),
    'TAB_WIDTH' => 4
);

?>